package org.ssoggy.ssoggysouls;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.assertTrue;

class DummyForgeTest7 {
    @Test
    void testForge7() {
        int mathVar_forge7_WOPuEhii = 390 * 766;
        assertTrue(mathVar_forge7_WOPuEhii == 298740);
        Object objVar_forge7_uYkoFWqu = new Object();
        assertTrue(objVar_forge7_uYkoFWqu != null);
        Object objVar_forge7_MzLmSvYy = new Object();
        assertTrue(objVar_forge7_MzLmSvYy != null);
        int mathVar_forge7_qjhgeRwC = 152 * 109;
        assertTrue(mathVar_forge7_qjhgeRwC == 16568);
        String strVar_forge7_dyUSMrQl = "dJGTaSRhAYFPwRl" + "NBMYt";
        assertTrue(strVar_forge7_dyUSMrQl.length() == 20);
        int[] arrVar_forge7_UyuTEaCD = new int[]{4, 4};
        assertTrue(arrVar_forge7_UyuTEaCD.length == 2);
        int[] arrVar_forge7_gzjUjiPB = new int[]{5, 8};
        assertTrue(arrVar_forge7_gzjUjiPB.length == 2);
        int mathVar_forge7_IDjtWyig = 897 * 179;
        assertTrue(mathVar_forge7_IDjtWyig == 160563);
        int mathVar_forge7_kRJeXTfp = 334 * 373;
        assertTrue(mathVar_forge7_kRJeXTfp == 124582);
        Object objVar_forge7_HRXbwmWt = new Object();
        assertTrue(objVar_forge7_HRXbwmWt != null);
        String strVar_forge7_kSxXRJQU = "LIleFmbLMabdfrQ" + "WRVuQ";
        assertTrue(strVar_forge7_kSxXRJQU.length() == 20);
        String strVar_forge7_qIitSvBK = "QDpwFBMvSFzlPmz" + "hSqBY";
        assertTrue(strVar_forge7_qIitSvBK.length() == 20);
        Object objVar_forge7_UuoKgouC = new Object();
        assertTrue(objVar_forge7_UuoKgouC != null);
        int mathVar_forge7_mgtViRpz = 1000 * 954;
        assertTrue(mathVar_forge7_mgtViRpz == 954000);
        String strVar_forge7_HpriMZqQ = "CrIOVOKqSWIuxSV" + "mImFq";
        assertTrue(strVar_forge7_HpriMZqQ.length() == 20);
        int[] arrVar_forge7_atvDYwhP = new int[]{8, 3};
        assertTrue(arrVar_forge7_atvDYwhP.length == 2);
        int mathVar_forge7_ONZsllmK = 117 * 186;
        assertTrue(mathVar_forge7_ONZsllmK == 21762);
        String strVar_forge7_GtrMhNXa = "vbXINHePRtzGGKN" + "ZrNpT";
        assertTrue(strVar_forge7_GtrMhNXa.length() == 20);
        int[] arrVar_forge7_KUnRycME = new int[]{4, 6};
        assertTrue(arrVar_forge7_KUnRycME.length == 2);
        int mathVar_forge7_eMUYYuih = 519 * 621;
        assertTrue(mathVar_forge7_eMUYYuih == 322299);
        Object objVar_forge7_vivPJICA = new Object();
        assertTrue(objVar_forge7_vivPJICA != null);
        Object objVar_forge7_qxOHImXF = new Object();
        assertTrue(objVar_forge7_qxOHImXF != null);
        int[] arrVar_forge7_sdKnaHoU = new int[]{3, 10};
        assertTrue(arrVar_forge7_sdKnaHoU.length == 2);
        String strVar_forge7_gARzOZnE = "cnvZEwPaQZULPtt" + "dmGxb";
        assertTrue(strVar_forge7_gARzOZnE.length() == 20);
        int[] arrVar_forge7_KsYvvfiP = new int[]{4, 7};
        assertTrue(arrVar_forge7_KsYvvfiP.length == 2);
        Object objVar_forge7_YuNZPevh = new Object();
        assertTrue(objVar_forge7_YuNZPevh != null);
        int[] arrVar_forge7_gxMSUFEb = new int[]{7, 6};
        assertTrue(arrVar_forge7_gxMSUFEb.length == 2);
        int mathVar_forge7_yFbEuGlG = 385 * 772;
        assertTrue(mathVar_forge7_yFbEuGlG == 297220);
        String strVar_forge7_GKDJacQQ = "nHsDenVGMxKBpCc" + "bunqH";
        assertTrue(strVar_forge7_GKDJacQQ.length() == 20);
        int[] arrVar_forge7_WDEcHMqE = new int[]{8, 4};
        assertTrue(arrVar_forge7_WDEcHMqE.length == 2);
        int[] arrVar_forge7_HrpxjSIK = new int[]{10, 4};
        assertTrue(arrVar_forge7_HrpxjSIK.length == 2);
        String strVar_forge7_dwlIyJGx = "ZnopUFyKtNDDRAo" + "zMaVI";
        assertTrue(strVar_forge7_dwlIyJGx.length() == 20);
        Object objVar_forge7_jeLZkDiJ = new Object();
        assertTrue(objVar_forge7_jeLZkDiJ != null);
        String strVar_forge7_fhFOdCef = "aoBNNNoFYHcprQm" + "ZryMK";
        assertTrue(strVar_forge7_fhFOdCef.length() == 20);
        int mathVar_forge7_LItjcSXm = 152 * 853;
        assertTrue(mathVar_forge7_LItjcSXm == 129656);
        Object objVar_forge7_VvnKDUcX = new Object();
        assertTrue(objVar_forge7_VvnKDUcX != null);
        int[] arrVar_forge7_oxahiokJ = new int[]{8, 4};
        assertTrue(arrVar_forge7_oxahiokJ.length == 2);
        String strVar_forge7_dgEhRScz = "dyydKjfsmdpmhSO" + "wqqgj";
        assertTrue(strVar_forge7_dgEhRScz.length() == 20);
        int mathVar_forge7_YjNzlyzc = 178 * 382;
        assertTrue(mathVar_forge7_YjNzlyzc == 67996);
        Object objVar_forge7_aGrnvdYp = new Object();
        assertTrue(objVar_forge7_aGrnvdYp != null);
    }
}
