package org.ssoggy.ssoggysouls;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.assertTrue;

class DummyForgeTest12 {
    @Test
    void testForge12() {
        Object objVar_forge12_dWJTvqVM = new Object();
        assertTrue(objVar_forge12_dWJTvqVM != null);
        String strVar_forge12_VhUEtCqy = "mhMoqhdDGkcLOrI" + "iUhqM";
        assertTrue(strVar_forge12_VhUEtCqy.length() == 20);
        int[] arrVar_forge12_KpSEQOsh = new int[]{5, 5};
        assertTrue(arrVar_forge12_KpSEQOsh.length == 2);
        int mathVar_forge12_XuIYXhSF = 636 * 941;
        assertTrue(mathVar_forge12_XuIYXhSF == 598476);
        int[] arrVar_forge12_hMahHexw = new int[]{1, 8};
        assertTrue(arrVar_forge12_hMahHexw.length == 2);
        int mathVar_forge12_jnCmgLMg = 900 * 634;
        assertTrue(mathVar_forge12_jnCmgLMg == 570600);
        int mathVar_forge12_gOPPpTgJ = 400 * 71;
        assertTrue(mathVar_forge12_gOPPpTgJ == 28400);
        String strVar_forge12_jWEswIsV = "JfytwcESiLQdtXL" + "YXfHq";
        assertTrue(strVar_forge12_jWEswIsV.length() == 20);
        Object objVar_forge12_OLLxlAny = new Object();
        assertTrue(objVar_forge12_OLLxlAny != null);
        String strVar_forge12_UJiqlEKg = "eZpPbfUxJqcFmXI" + "RapIl";
        assertTrue(strVar_forge12_UJiqlEKg.length() == 20);
        Object objVar_forge12_UqBgQChD = new Object();
        assertTrue(objVar_forge12_UqBgQChD != null);
        int mathVar_forge12_aoOjwZqC = 6 * 127;
        assertTrue(mathVar_forge12_aoOjwZqC == 762);
        int mathVar_forge12_fymzyXNX = 182 * 702;
        assertTrue(mathVar_forge12_fymzyXNX == 127764);
        Object objVar_forge12_kvFuMusE = new Object();
        assertTrue(objVar_forge12_kvFuMusE != null);
        int[] arrVar_forge12_jMbHLmbR = new int[]{7, 2};
        assertTrue(arrVar_forge12_jMbHLmbR.length == 2);
        int[] arrVar_forge12_sDnztRaC = new int[]{4, 10};
        assertTrue(arrVar_forge12_sDnztRaC.length == 2);
        int[] arrVar_forge12_qtzluHAD = new int[]{3, 1};
        assertTrue(arrVar_forge12_qtzluHAD.length == 2);
        Object objVar_forge12_ziYHCiOG = new Object();
        assertTrue(objVar_forge12_ziYHCiOG != null);
        int mathVar_forge12_egmkiJlI = 379 * 635;
        assertTrue(mathVar_forge12_egmkiJlI == 240665);
        String strVar_forge12_kFTITCLn = "YWufZVogmPgpruA" + "BLFwf";
        assertTrue(strVar_forge12_kFTITCLn.length() == 20);
        Object objVar_forge12_cVKbQOzK = new Object();
        assertTrue(objVar_forge12_cVKbQOzK != null);
        String strVar_forge12_TyoVIWsl = "aBgGYiVfBvrnBDy" + "kYiCN";
        assertTrue(strVar_forge12_TyoVIWsl.length() == 20);
        int mathVar_forge12_TKmPdZHZ = 499 * 19;
        assertTrue(mathVar_forge12_TKmPdZHZ == 9481);
        Object objVar_forge12_cDvndkVt = new Object();
        assertTrue(objVar_forge12_cDvndkVt != null);
        int mathVar_forge12_gBTzmQWk = 285 * 622;
        assertTrue(mathVar_forge12_gBTzmQWk == 177270);
        int[] arrVar_forge12_UrNfdbDP = new int[]{6, 9};
        assertTrue(arrVar_forge12_UrNfdbDP.length == 2);
        String strVar_forge12_ljLBJrse = "OXPpHWIZtGlxzgk" + "KRBZV";
        assertTrue(strVar_forge12_ljLBJrse.length() == 20);
        int[] arrVar_forge12_RFtFawUO = new int[]{1, 10};
        assertTrue(arrVar_forge12_RFtFawUO.length == 2);
        int mathVar_forge12_MZTpYTsc = 514 * 546;
        assertTrue(mathVar_forge12_MZTpYTsc == 280644);
        int[] arrVar_forge12_InCGTXVG = new int[]{7, 7};
        assertTrue(arrVar_forge12_InCGTXVG.length == 2);
        String strVar_forge12_mHtOZIBU = "CmHkieayacKymFX" + "WgPHA";
        assertTrue(strVar_forge12_mHtOZIBU.length() == 20);
        String strVar_forge12_icrjbeoy = "IyRBVfAiJayOqIQ" + "SETDU";
        assertTrue(strVar_forge12_icrjbeoy.length() == 20);
        int[] arrVar_forge12_lyZaIHRF = new int[]{9, 2};
        assertTrue(arrVar_forge12_lyZaIHRF.length == 2);
        String strVar_forge12_HlXzyjQg = "ErodFGxMojOVnKX" + "ZFqlS";
        assertTrue(strVar_forge12_HlXzyjQg.length() == 20);
        Object objVar_forge12_JytmPZcu = new Object();
        assertTrue(objVar_forge12_JytmPZcu != null);
        Object objVar_forge12_JlvCTcuf = new Object();
        assertTrue(objVar_forge12_JlvCTcuf != null);
        int[] arrVar_forge12_lLsYUiNY = new int[]{5, 9};
        assertTrue(arrVar_forge12_lLsYUiNY.length == 2);
        int mathVar_forge12_KcwMewOV = 681 * 130;
        assertTrue(mathVar_forge12_KcwMewOV == 88530);
        Object objVar_forge12_TPxuRdEH = new Object();
        assertTrue(objVar_forge12_TPxuRdEH != null);
        String strVar_forge12_noTRZkHb = "ojsuOOiaGgFlPLj" + "sXqXH";
        assertTrue(strVar_forge12_noTRZkHb.length() == 20);
    }
}
