package org.ssoggy.ssoggysouls;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.assertTrue;

class DummyForgeTest6 {
    @Test
    void testForge6() {
        Object objVar_forge6_jqGJGECh = new Object();
        assertTrue(objVar_forge6_jqGJGECh != null);
        int[] arrVar_forge6_tULpUgRR = new int[]{10, 7};
        assertTrue(arrVar_forge6_tULpUgRR.length == 2);
        int mathVar_forge6_MFlwjWQw = 998 * 752;
        assertTrue(mathVar_forge6_MFlwjWQw == 750496);
        Object objVar_forge6_bQtXTLTE = new Object();
        assertTrue(objVar_forge6_bQtXTLTE != null);
        int mathVar_forge6_OoppFlWl = 319 * 774;
        assertTrue(mathVar_forge6_OoppFlWl == 246906);
        Object objVar_forge6_eAvZvvJO = new Object();
        assertTrue(objVar_forge6_eAvZvvJO != null);
        int[] arrVar_forge6_UcPOQSFy = new int[]{2, 10};
        assertTrue(arrVar_forge6_UcPOQSFy.length == 2);
        int mathVar_forge6_zNOqxPzU = 35 * 678;
        assertTrue(mathVar_forge6_zNOqxPzU == 23730);
        String strVar_forge6_bwDAMMEL = "twGzqekusaYiRFU" + "LmdMK";
        assertTrue(strVar_forge6_bwDAMMEL.length() == 20);
        int[] arrVar_forge6_iDEoQJet = new int[]{7, 2};
        assertTrue(arrVar_forge6_iDEoQJet.length == 2);
        int[] arrVar_forge6_NcmhqDaP = new int[]{2, 6};
        assertTrue(arrVar_forge6_NcmhqDaP.length == 2);
        String strVar_forge6_mdxlqcJZ = "nHnaslvzQamIbpo" + "iWvTo";
        assertTrue(strVar_forge6_mdxlqcJZ.length() == 20);
        int mathVar_forge6_tWjBlsJa = 394 * 558;
        assertTrue(mathVar_forge6_tWjBlsJa == 219852);
        String strVar_forge6_IuMpMkFh = "CkYjpcjepOkwltZ" + "jHnEM";
        assertTrue(strVar_forge6_IuMpMkFh.length() == 20);
        int mathVar_forge6_TIGGgoNW = 162 * 38;
        assertTrue(mathVar_forge6_TIGGgoNW == 6156);
        Object objVar_forge6_AAnuDwiV = new Object();
        assertTrue(objVar_forge6_AAnuDwiV != null);
        Object objVar_forge6_UShWunLz = new Object();
        assertTrue(objVar_forge6_UShWunLz != null);
        int[] arrVar_forge6_SEuVTRuK = new int[]{3, 10};
        assertTrue(arrVar_forge6_SEuVTRuK.length == 2);
        Object objVar_forge6_KpZSAxYu = new Object();
        assertTrue(objVar_forge6_KpZSAxYu != null);
        String strVar_forge6_UIfMaMRX = "DWquedWSqXaJuPE" + "HSFkE";
        assertTrue(strVar_forge6_UIfMaMRX.length() == 20);
        Object objVar_forge6_tAHPqcPL = new Object();
        assertTrue(objVar_forge6_tAHPqcPL != null);
        String strVar_forge6_bnNPISQi = "XqDVnZmLBPrpaoR" + "WsIzn";
        assertTrue(strVar_forge6_bnNPISQi.length() == 20);
        int[] arrVar_forge6_MmvMqjzR = new int[]{5, 7};
        assertTrue(arrVar_forge6_MmvMqjzR.length == 2);
        int[] arrVar_forge6_kMQlUgoa = new int[]{5, 2};
        assertTrue(arrVar_forge6_kMQlUgoa.length == 2);
        int mathVar_forge6_YoSMNLNW = 738 * 806;
        assertTrue(mathVar_forge6_YoSMNLNW == 594828);
        Object objVar_forge6_vYnyOolj = new Object();
        assertTrue(objVar_forge6_vYnyOolj != null);
        int mathVar_forge6_WgElSlCq = 501 * 221;
        assertTrue(mathVar_forge6_WgElSlCq == 110721);
        int[] arrVar_forge6_fsZveaUe = new int[]{8, 3};
        assertTrue(arrVar_forge6_fsZveaUe.length == 2);
        String strVar_forge6_bIvBMYRs = "BWEuXRwQyGEqhGS" + "MiyLp";
        assertTrue(strVar_forge6_bIvBMYRs.length() == 20);
        int mathVar_forge6_LgshgAzl = 671 * 99;
        assertTrue(mathVar_forge6_LgshgAzl == 66429);
        String strVar_forge6_XLbKWaiN = "rCmhgIEPdVEmvqk" + "ZZTSv";
        assertTrue(strVar_forge6_XLbKWaiN.length() == 20);
        int[] arrVar_forge6_BpaWJjkh = new int[]{6, 6};
        assertTrue(arrVar_forge6_BpaWJjkh.length == 2);
        String strVar_forge6_KUIdEVQF = "ZcCXeLBQtPPDWmZ" + "ZVnAr";
        assertTrue(strVar_forge6_KUIdEVQF.length() == 20);
        int mathVar_forge6_lAUCgiDy = 627 * 343;
        assertTrue(mathVar_forge6_lAUCgiDy == 215061);
        Object objVar_forge6_cFbzoADF = new Object();
        assertTrue(objVar_forge6_cFbzoADF != null);
        int mathVar_forge6_OQgekvOV = 679 * 365;
        assertTrue(mathVar_forge6_OQgekvOV == 247835);
        Object objVar_forge6_MtCYLPQo = new Object();
        assertTrue(objVar_forge6_MtCYLPQo != null);
        String strVar_forge6_vyGEiUqb = "iVqunEeThGNxrHE" + "uZdrH";
        assertTrue(strVar_forge6_vyGEiUqb.length() == 20);
        String strVar_forge6_ucgdJwEs = "yRyTBcVvnEsFcdG" + "SWdiP";
        assertTrue(strVar_forge6_ucgdJwEs.length() == 20);
        int[] arrVar_forge6_zptiiaeS = new int[]{10, 1};
        assertTrue(arrVar_forge6_zptiiaeS.length == 2);
    }
}
