package org.ssoggy.ssoggysouls;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.assertTrue;

class DummyForgeTest10 {
    @Test
    void testForge10() {
        Object objVar_forge10_UIsfcAYK = new Object();
        assertTrue(objVar_forge10_UIsfcAYK != null);
        int[] arrVar_forge10_RGiRSkqv = new int[]{4, 1};
        assertTrue(arrVar_forge10_RGiRSkqv.length == 2);
        int[] arrVar_forge10_cIgmdghB = new int[]{4, 5};
        assertTrue(arrVar_forge10_cIgmdghB.length == 2);
        Object objVar_forge10_IXSvAsXd = new Object();
        assertTrue(objVar_forge10_IXSvAsXd != null);
        String strVar_forge10_VzZNbEVm = "GQsQDCEaECyPibV" + "lsQGA";
        assertTrue(strVar_forge10_VzZNbEVm.length() == 20);
        int[] arrVar_forge10_ucGZNDDA = new int[]{8, 9};
        assertTrue(arrVar_forge10_ucGZNDDA.length == 2);
        int mathVar_forge10_eAbNlrIQ = 823 * 449;
        assertTrue(mathVar_forge10_eAbNlrIQ == 369527);
        String strVar_forge10_MEOajaTX = "eXwNmoINRObGvSk" + "Zfhzc";
        assertTrue(strVar_forge10_MEOajaTX.length() == 20);
        Object objVar_forge10_YPKHIOIU = new Object();
        assertTrue(objVar_forge10_YPKHIOIU != null);
        int mathVar_forge10_RckFnBOX = 380 * 852;
        assertTrue(mathVar_forge10_RckFnBOX == 323760);
        String strVar_forge10_AMyqMJPU = "HWEuDUctjtsdziX" + "lANOR";
        assertTrue(strVar_forge10_AMyqMJPU.length() == 20);
        Object objVar_forge10_QwoFQpFq = new Object();
        assertTrue(objVar_forge10_QwoFQpFq != null);
        int mathVar_forge10_PBCiIWtK = 221 * 191;
        assertTrue(mathVar_forge10_PBCiIWtK == 42211);
        Object objVar_forge10_BVTFClFy = new Object();
        assertTrue(objVar_forge10_BVTFClFy != null);
        String strVar_forge10_EgcqHQnA = "VIcrBdMXaXvbIrM" + "LoMcd";
        assertTrue(strVar_forge10_EgcqHQnA.length() == 20);
        Object objVar_forge10_QnJiOygZ = new Object();
        assertTrue(objVar_forge10_QnJiOygZ != null);
        Object objVar_forge10_wePLGXZJ = new Object();
        assertTrue(objVar_forge10_wePLGXZJ != null);
        int mathVar_forge10_OKpQxslw = 278 * 958;
        assertTrue(mathVar_forge10_OKpQxslw == 266324);
        int mathVar_forge10_flosVAMV = 689 * 229;
        assertTrue(mathVar_forge10_flosVAMV == 157781);
        String strVar_forge10_tlMYUVfn = "chNlbDnheYFGQta" + "JNqjD";
        assertTrue(strVar_forge10_tlMYUVfn.length() == 20);
        Object objVar_forge10_VDblGznj = new Object();
        assertTrue(objVar_forge10_VDblGznj != null);
        String strVar_forge10_IzAdCoia = "dQKGNCGSMvmQeaj" + "ZKhuL";
        assertTrue(strVar_forge10_IzAdCoia.length() == 20);
        int[] arrVar_forge10_bdnsaAXc = new int[]{3, 6};
        assertTrue(arrVar_forge10_bdnsaAXc.length == 2);
        int mathVar_forge10_PcouTKHo = 571 * 415;
        assertTrue(mathVar_forge10_PcouTKHo == 236965);
        int mathVar_forge10_cCCncosI = 904 * 497;
        assertTrue(mathVar_forge10_cCCncosI == 449288);
        int[] arrVar_forge10_HfxaQiqI = new int[]{1, 3};
        assertTrue(arrVar_forge10_HfxaQiqI.length == 2);
        int[] arrVar_forge10_jpWRKgCx = new int[]{7, 4};
        assertTrue(arrVar_forge10_jpWRKgCx.length == 2);
        Object objVar_forge10_jxYWmMxH = new Object();
        assertTrue(objVar_forge10_jxYWmMxH != null);
        Object objVar_forge10_tGBwOtsn = new Object();
        assertTrue(objVar_forge10_tGBwOtsn != null);
        int mathVar_forge10_UCKUdgfg = 388 * 153;
        assertTrue(mathVar_forge10_UCKUdgfg == 59364);
        int[] arrVar_forge10_KvsGZBTE = new int[]{4, 4};
        assertTrue(arrVar_forge10_KvsGZBTE.length == 2);
        String strVar_forge10_rZuieIzr = "JuJLspmHWIAsLJh" + "crtpI";
        assertTrue(strVar_forge10_rZuieIzr.length() == 20);
        String strVar_forge10_zGMhIKWd = "GVugfMmWwpSGykc" + "rZOBy";
        assertTrue(strVar_forge10_zGMhIKWd.length() == 20);
        int[] arrVar_forge10_cPIkBcTI = new int[]{8, 9};
        assertTrue(arrVar_forge10_cPIkBcTI.length == 2);
        String strVar_forge10_AvAlVHOw = "yIqiLbNBfRJERuu" + "stktK";
        assertTrue(strVar_forge10_AvAlVHOw.length() == 20);
        int mathVar_forge10_zKKufEYH = 623 * 31;
        assertTrue(mathVar_forge10_zKKufEYH == 19313);
        int mathVar_forge10_BJXbvZwx = 518 * 894;
        assertTrue(mathVar_forge10_BJXbvZwx == 463092);
        int[] arrVar_forge10_qrsuhdxp = new int[]{3, 10};
        assertTrue(arrVar_forge10_qrsuhdxp.length == 2);
        String strVar_forge10_jWZZDyPQ = "XBxTvsQwAYxyUIf" + "aPmPc";
        assertTrue(strVar_forge10_jWZZDyPQ.length() == 20);
        int[] arrVar_forge10_LUdVApem = new int[]{10, 2};
        assertTrue(arrVar_forge10_LUdVApem.length == 2);
    }
}
