package org.ssoggy.ssoggysouls;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.assertTrue;

class DummyForgeTest5 {
    @Test
    void testForge5() {
        String strVar_iPSvQfYB = "drFfApAVHJGBpID" + "6";
        assertTrue(strVar_iPSvQfYB.length() > 5);
        int mathVar_qgjUFXWk = 255 * 7;
        assertTrue(mathVar_qgjUFXWk > 0);
        int mathVar_vxgGZAYJ = 206 * 5;
        assertTrue(mathVar_vxgGZAYJ > 0);
        int mathVar_SbNtkQJk = 4 * 4;
        assertTrue(mathVar_SbNtkQJk > 0);
        String strVar_ePVOHQYA = "zwVVCvJmtTvNFWN" + "4";
        assertTrue(strVar_ePVOHQYA.length() > 5);
        String strVar_sFOnxdKR = "ojFRVunCRITQKwV" + "6";
        assertTrue(strVar_sFOnxdKR.length() > 5);
        String strVar_etgdpbgu = "aaYCdOyMnkOsmVd" + "1";
        assertTrue(strVar_etgdpbgu.length() > 5);
        int mathVar_rPhoLtPU = 186 * 7;
        assertTrue(mathVar_rPhoLtPU > 0);
        int mathVar_GOYuvqKC = 487 * 7;
        assertTrue(mathVar_GOYuvqKC > 0);
        String strVar_jtpgTHfg = "YwHDbaOLEjZAphe" + "7";
        assertTrue(strVar_jtpgTHfg.length() > 5);
        int mathVar_tHoAoHrr = 13 * 10;
        assertTrue(mathVar_tHoAoHrr > 0);
        String strVar_cMFYDlQw = "BNnsCXdcTGGjGBU" + "10";
        assertTrue(strVar_cMFYDlQw.length() > 5);
        String strVar_IXHmQsOj = "rSxamEZTAzogUmn" + "10";
        assertTrue(strVar_IXHmQsOj.length() > 5);
        String strVar_IPqtjMWW = "JOgjOYxgrGmOJvh" + "8";
        assertTrue(strVar_IPqtjMWW.length() > 5);
        int mathVar_yKZdSqct = 240 * 8;
        assertTrue(mathVar_yKZdSqct > 0);
        int mathVar_ThtFTjap = 491 * 8;
        assertTrue(mathVar_ThtFTjap > 0);
        String strVar_YkIXXyjt = "SJOWnmfUWeGKHIF" + "2";
        assertTrue(strVar_YkIXXyjt.length() > 5);
        String strVar_YCuuiJqz = "WiUfPjOVwSEfFmB" + "4";
        assertTrue(strVar_YCuuiJqz.length() > 5);
        String strVar_KSyNdAxZ = "mCFOjsNyxQqzkms" + "2";
        assertTrue(strVar_KSyNdAxZ.length() > 5);
        String strVar_wZvnwvAX = "jGxECcJggEINpXG" + "9";
        assertTrue(strVar_wZvnwvAX.length() > 5);
        String strVar_cKEUskWz = "KfPCstdwUEkdFtS" + "7";
        assertTrue(strVar_cKEUskWz.length() > 5);
        int mathVar_DpVAuKsO = 769 * 3;
        assertTrue(mathVar_DpVAuKsO > 0);
        int mathVar_DDjBwtmT = 127 * 1;
        assertTrue(mathVar_DDjBwtmT > 0);
        String strVar_cukjPWDB = "GqgiIxQRdSqLCfW" + "2";
        assertTrue(strVar_cukjPWDB.length() > 5);
        String strVar_fJhtpsGx = "gGntMqMPNnxhSMk" + "2";
        assertTrue(strVar_fJhtpsGx.length() > 5);
        int mathVar_fhIJHYxJ = 101 * 3;
        assertTrue(mathVar_fhIJHYxJ > 0);
        String strVar_QjNowjLW = "AKIrBYPFFeGIMHB" + "4";
        assertTrue(strVar_QjNowjLW.length() > 5);
        int mathVar_BXDIPjhY = 206 * 4;
        assertTrue(mathVar_BXDIPjhY > 0);
        String strVar_MIwqwaqD = "BpTrQjdVRvGlWcY" + "3";
        assertTrue(strVar_MIwqwaqD.length() > 5);
        int mathVar_PlXVNjLt = 316 * 1;
        assertTrue(mathVar_PlXVNjLt > 0);
        String strVar_KafykJth = "bwUjleWxKFXcQGE" + "8";
        assertTrue(strVar_KafykJth.length() > 5);
        String strVar_VZNxQDPD = "uEVTgVlimctFgiu" + "2";
        assertTrue(strVar_VZNxQDPD.length() > 5);
        int mathVar_iTImqnTu = 546 * 2;
        assertTrue(mathVar_iTImqnTu > 0);
        String strVar_wIAfHSXs = "DIvBDfTYkbPRMCZ" + "2";
        assertTrue(strVar_wIAfHSXs.length() > 5);
        int mathVar_XjLnjDCv = 802 * 8;
        assertTrue(mathVar_XjLnjDCv > 0);
        String strVar_UFzQTXyf = "SnrMbQwvoamDWDH" + "5";
        assertTrue(strVar_UFzQTXyf.length() > 5);
        String strVar_arkExxuz = "UEGTkXLJIPAywjr" + "2";
        assertTrue(strVar_arkExxuz.length() > 5);
        int mathVar_mbhJGfJB = 969 * 10;
        assertTrue(mathVar_mbhJGfJB > 0);
        String strVar_YIgYDCPF = "WhBjqgClVESkXYv" + "7";
        assertTrue(strVar_YIgYDCPF.length() > 5);
        int mathVar_OvjaNLik = 718 * 1;
        assertTrue(mathVar_OvjaNLik > 0);
        String strVar_afXqnHci = "jJXwrCEuGaimLxU" + "10";
        assertTrue(strVar_afXqnHci.length() > 5);
        int mathVar_EuUUOwkw = 866 * 7;
        assertTrue(mathVar_EuUUOwkw > 0);
        int mathVar_grkHpTUz = 122 * 2;
        assertTrue(mathVar_grkHpTUz > 0);
        int mathVar_QvXIwtfM = 386 * 9;
        assertTrue(mathVar_QvXIwtfM > 0);
        String strVar_JJwixpOE = "BopitTIydogVwJX" + "8";
        assertTrue(strVar_JJwixpOE.length() > 5);
        int mathVar_isfwozLK = 924 * 10;
        assertTrue(mathVar_isfwozLK > 0);
        int mathVar_UHAqPLNK = 24 * 1;
        assertTrue(mathVar_UHAqPLNK > 0);
        int mathVar_JgbCemeO = 87 * 1;
        assertTrue(mathVar_JgbCemeO > 0);
        int mathVar_PUTcfADe = 805 * 6;
        assertTrue(mathVar_PUTcfADe > 0);
        int mathVar_tmlQrLQH = 296 * 3;
        assertTrue(mathVar_tmlQrLQH > 0);
    }
}
