package org.ssoggy.ssoggysouls;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.assertTrue;

class DummyForgeTest4 {
    @Test
    void testForge4() {
        String strVar_EueytYPd = "BRHJvuvrEELHRLy" + "8";
        assertTrue(strVar_EueytYPd.length() > 5);
        int mathVar_opNjfqhv = 442 * 2;
        assertTrue(mathVar_opNjfqhv > 0);
        int mathVar_aVmGUije = 848 * 2;
        assertTrue(mathVar_aVmGUije > 0);
        int mathVar_XlcOYTNP = 90 * 7;
        assertTrue(mathVar_XlcOYTNP > 0);
        int mathVar_nEahMQSP = 428 * 4;
        assertTrue(mathVar_nEahMQSP > 0);
        String strVar_oalOIfyE = "xMwnjsJACEHPXIR" + "5";
        assertTrue(strVar_oalOIfyE.length() > 5);
        String strVar_TGMASJEm = "mLiLqoSHDUkNgGh" + "6";
        assertTrue(strVar_TGMASJEm.length() > 5);
        int mathVar_xaNTPeOF = 461 * 1;
        assertTrue(mathVar_xaNTPeOF > 0);
        int mathVar_khjlfuYj = 740 * 9;
        assertTrue(mathVar_khjlfuYj > 0);
        String strVar_VkhWwaxe = "hmbhEONWjuHbQVA" + "10";
        assertTrue(strVar_VkhWwaxe.length() > 5);
        int mathVar_nyflALsz = 239 * 9;
        assertTrue(mathVar_nyflALsz > 0);
        String strVar_hiadgDYd = "CbzlbHKiSPajsGz" + "3";
        assertTrue(strVar_hiadgDYd.length() > 5);
        String strVar_DMWswTdi = "XtMfzLqwFslZAYJ" + "7";
        assertTrue(strVar_DMWswTdi.length() > 5);
        int mathVar_eprDMquX = 160 * 3;
        assertTrue(mathVar_eprDMquX > 0);
        String strVar_nHKDevhj = "VyJQjmjtURJyyBk" + "6";
        assertTrue(strVar_nHKDevhj.length() > 5);
        String strVar_LmfrBKpo = "ayVFnweQMTvwdBP" + "8";
        assertTrue(strVar_LmfrBKpo.length() > 5);
        int mathVar_tZpyGsEU = 355 * 4;
        assertTrue(mathVar_tZpyGsEU > 0);
        int mathVar_kNuaykxk = 436 * 4;
        assertTrue(mathVar_kNuaykxk > 0);
        String strVar_PzctgYum = "lyngJKRYfOhVzfR" + "3";
        assertTrue(strVar_PzctgYum.length() > 5);
        int mathVar_ctjCQdNp = 478 * 8;
        assertTrue(mathVar_ctjCQdNp > 0);
        String strVar_hYBMHdaR = "lUwsnyfTeVNEjef" + "3";
        assertTrue(strVar_hYBMHdaR.length() > 5);
        String strVar_ifPWfJTL = "gKNfgcXWGMVswLp" + "4";
        assertTrue(strVar_ifPWfJTL.length() > 5);
        int mathVar_gHnYePlf = 756 * 1;
        assertTrue(mathVar_gHnYePlf > 0);
        int mathVar_lzDrBfmf = 587 * 4;
        assertTrue(mathVar_lzDrBfmf > 0);
        String strVar_MIyUbuhH = "JPOcXOKYlsILriN" + "9";
        assertTrue(strVar_MIyUbuhH.length() > 5);
        String strVar_RFerVXPn = "lKuHSGzrbzPglTQ" + "2";
        assertTrue(strVar_RFerVXPn.length() > 5);
        String strVar_tlcdmqRI = "AuDnaPLOIefLMCG" + "3";
        assertTrue(strVar_tlcdmqRI.length() > 5);
        int mathVar_JsCAbhwa = 555 * 9;
        assertTrue(mathVar_JsCAbhwa > 0);
        int mathVar_kNZihafK = 469 * 3;
        assertTrue(mathVar_kNZihafK > 0);
        int mathVar_ndeXsDoJ = 636 * 8;
        assertTrue(mathVar_ndeXsDoJ > 0);
        int mathVar_UskDEAsb = 674 * 5;
        assertTrue(mathVar_UskDEAsb > 0);
        int mathVar_XQZLBMOo = 186 * 8;
        assertTrue(mathVar_XQZLBMOo > 0);
        String strVar_HHoRBkMA = "GEuxuVKnNDDVShq" + "9";
        assertTrue(strVar_HHoRBkMA.length() > 5);
        String strVar_nEJxdLSy = "EfbmWyJZtXfevEs" + "2";
        assertTrue(strVar_nEJxdLSy.length() > 5);
        String strVar_DOnVnyAw = "dbzCzggvsNnFIsn" + "8";
        assertTrue(strVar_DOnVnyAw.length() > 5);
        int mathVar_gJjXuZkK = 651 * 1;
        assertTrue(mathVar_gJjXuZkK > 0);
        String strVar_KWjHuiuB = "mCOsixMSsQRzjoG" + "4";
        assertTrue(strVar_KWjHuiuB.length() > 5);
        int mathVar_CHimUQzR = 367 * 10;
        assertTrue(mathVar_CHimUQzR > 0);
        String strVar_ZcEPexoj = "AyGpaBkQGUFjSgu" + "9";
        assertTrue(strVar_ZcEPexoj.length() > 5);
        int mathVar_JqYKRzKw = 191 * 1;
        assertTrue(mathVar_JqYKRzKw > 0);
        String strVar_CAANqjSG = "BoQYKakxCkAPXIw" + "7";
        assertTrue(strVar_CAANqjSG.length() > 5);
        String strVar_AdQhxAON = "GnUcrkeDjoxEnXG" + "4";
        assertTrue(strVar_AdQhxAON.length() > 5);
        int mathVar_RYNLgmNj = 681 * 10;
        assertTrue(mathVar_RYNLgmNj > 0);
        String strVar_qZJHuZPA = "QdLZBroKIPIkGVD" + "4";
        assertTrue(strVar_qZJHuZPA.length() > 5);
        int mathVar_UQYKNpoy = 394 * 10;
        assertTrue(mathVar_UQYKNpoy > 0);
        int mathVar_uvIRVRPZ = 747 * 9;
        assertTrue(mathVar_uvIRVRPZ > 0);
        String strVar_JoXypRyg = "VfoEtnsirqgZZak" + "9";
        assertTrue(strVar_JoXypRyg.length() > 5);
        String strVar_SbbMyWGQ = "VBbjJGTIbbkKugL" + "3";
        assertTrue(strVar_SbbMyWGQ.length() > 5);
        String strVar_QUObvUpO = "nBYYyyGtBEeDdme" + "7";
        assertTrue(strVar_QUObvUpO.length() > 5);
        int mathVar_YAIkXCtl = 456 * 4;
        assertTrue(mathVar_YAIkXCtl > 0);
    }
}
