package org.ssoggy.ssoggysouls;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.assertTrue;

class DummyForgeTest14 {
    @Test
    void testForge14() {
        String strVar_forge14_XMnbYlvs = "CAvZgPuwDyJSzqo" + "aTYAr";
        assertTrue(strVar_forge14_XMnbYlvs.length() == 20);
        Object objVar_forge14_JJqvVBCs = new Object();
        assertTrue(objVar_forge14_JJqvVBCs != null);
        String strVar_forge14_HQrFCrCe = "yoWkYHeNBIYwFrc" + "Aeqxe";
        assertTrue(strVar_forge14_HQrFCrCe.length() == 20);
        int[] arrVar_forge14_TzbiTYCr = new int[]{1, 10};
        assertTrue(arrVar_forge14_TzbiTYCr.length == 2);
        String strVar_forge14_HOGLfqGR = "eATgqepOMGfwaCm" + "xENGE";
        assertTrue(strVar_forge14_HOGLfqGR.length() == 20);
        String strVar_forge14_WovvmMVN = "DHrTkeVZyAwGivr" + "lMlEW";
        assertTrue(strVar_forge14_WovvmMVN.length() == 20);
        Object objVar_forge14_uqJgZpEo = new Object();
        assertTrue(objVar_forge14_uqJgZpEo != null);
        int mathVar_forge14_clZbmrLL = 861 * 803;
        assertTrue(mathVar_forge14_clZbmrLL == 691383);
        int[] arrVar_forge14_vNVpFMsa = new int[]{5, 5};
        assertTrue(arrVar_forge14_vNVpFMsa.length == 2);
        int mathVar_forge14_zXKEGRPH = 294 * 265;
        assertTrue(mathVar_forge14_zXKEGRPH == 77910);
        int mathVar_forge14_QBwjbIDd = 669 * 606;
        assertTrue(mathVar_forge14_QBwjbIDd == 405414);
        int mathVar_forge14_WYsShdYx = 438 * 952;
        assertTrue(mathVar_forge14_WYsShdYx == 416976);
        int mathVar_forge14_JyyLGUnQ = 750 * 595;
        assertTrue(mathVar_forge14_JyyLGUnQ == 446250);
        int mathVar_forge14_ilqgwOxk = 931 * 80;
        assertTrue(mathVar_forge14_ilqgwOxk == 74480);
        int[] arrVar_forge14_wwYESwDd = new int[]{10, 1};
        assertTrue(arrVar_forge14_wwYESwDd.length == 2);
        String strVar_forge14_mKrHjQcn = "MTRhEmwDlbIjsfF" + "emCEH";
        assertTrue(strVar_forge14_mKrHjQcn.length() == 20);
        Object objVar_forge14_TxNeJcOJ = new Object();
        assertTrue(objVar_forge14_TxNeJcOJ != null);
        int[] arrVar_forge14_QkWKDWlZ = new int[]{4, 9};
        assertTrue(arrVar_forge14_QkWKDWlZ.length == 2);
        String strVar_forge14_iJeVwZTE = "AJiYWfLRtGvWgYc" + "mISIW";
        assertTrue(strVar_forge14_iJeVwZTE.length() == 20);
        String strVar_forge14_yavYqDuX = "PuyJHrtDUfBYwQn" + "POKvS";
        assertTrue(strVar_forge14_yavYqDuX.length() == 20);
        String strVar_forge14_yEEgHjcR = "FjqMyqRMxlGKrjx" + "USrsL";
        assertTrue(strVar_forge14_yEEgHjcR.length() == 20);
        Object objVar_forge14_utOwZSgU = new Object();
        assertTrue(objVar_forge14_utOwZSgU != null);
        Object objVar_forge14_WdazskMA = new Object();
        assertTrue(objVar_forge14_WdazskMA != null);
        String strVar_forge14_DYoSFueJ = "clXDMudNXFKbMYE" + "BjoGZ";
        assertTrue(strVar_forge14_DYoSFueJ.length() == 20);
        String strVar_forge14_JMtCiTOX = "bhwwcobtIMfmJgG" + "UDsSR";
        assertTrue(strVar_forge14_JMtCiTOX.length() == 20);
        Object objVar_forge14_ZBkTBdbe = new Object();
        assertTrue(objVar_forge14_ZBkTBdbe != null);
        int mathVar_forge14_YHRnllwa = 44 * 2;
        assertTrue(mathVar_forge14_YHRnllwa == 88);
        int mathVar_forge14_QRjMIyUh = 915 * 297;
        assertTrue(mathVar_forge14_QRjMIyUh == 271755);
        Object objVar_forge14_nQLAPuhT = new Object();
        assertTrue(objVar_forge14_nQLAPuhT != null);
        int[] arrVar_forge14_HfEItAFg = new int[]{1, 4};
        assertTrue(arrVar_forge14_HfEItAFg.length == 2);
        int[] arrVar_forge14_FaZglyrP = new int[]{1, 10};
        assertTrue(arrVar_forge14_FaZglyrP.length == 2);
        Object objVar_forge14_JtwGfraK = new Object();
        assertTrue(objVar_forge14_JtwGfraK != null);
        Object objVar_forge14_OOcaAboE = new Object();
        assertTrue(objVar_forge14_OOcaAboE != null);
        int[] arrVar_forge14_IORbwUKg = new int[]{1, 9};
        assertTrue(arrVar_forge14_IORbwUKg.length == 2);
        Object objVar_forge14_JiymuAde = new Object();
        assertTrue(objVar_forge14_JiymuAde != null);
        int[] arrVar_forge14_ohzxzitE = new int[]{2, 4};
        assertTrue(arrVar_forge14_ohzxzitE.length == 2);
        int mathVar_forge14_IyLGKctr = 998 * 276;
        assertTrue(mathVar_forge14_IyLGKctr == 275448);
        int[] arrVar_forge14_uSvYyApW = new int[]{8, 3};
        assertTrue(arrVar_forge14_uSvYyApW.length == 2);
        int[] arrVar_forge14_KMbvFBUm = new int[]{9, 4};
        assertTrue(arrVar_forge14_KMbvFBUm.length == 2);
        int mathVar_forge14_pMYbpevz = 883 * 928;
        assertTrue(mathVar_forge14_pMYbpevz == 819424);
    }
}
