package org.ssoggy.ssoggysouls;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.assertTrue;

class DummyForgeTest2 {
    @Test
    void testForge2() {
        int mathVar_zGSndKCF = 342 * 1;
        assertTrue(mathVar_zGSndKCF > 0);
        int mathVar_XiRYtOSe = 193 * 8;
        assertTrue(mathVar_XiRYtOSe > 0);
        String strVar_FxTQYljN = "uycXuEIMlpcmfhV" + "8";
        assertTrue(strVar_FxTQYljN.length() > 5);
        String strVar_CySoEqOm = "jzoBbnkRREqWmkg" + "7";
        assertTrue(strVar_CySoEqOm.length() > 5);
        int mathVar_WBUANLnL = 457 * 7;
        assertTrue(mathVar_WBUANLnL > 0);
        int mathVar_goAiIFus = 677 * 4;
        assertTrue(mathVar_goAiIFus > 0);
        int mathVar_xNVVzfEc = 481 * 1;
        assertTrue(mathVar_xNVVzfEc > 0);
        int mathVar_aqFlbejV = 616 * 10;
        assertTrue(mathVar_aqFlbejV > 0);
        int mathVar_znkwWFft = 226 * 5;
        assertTrue(mathVar_znkwWFft > 0);
        int mathVar_GNmfmEPk = 386 * 7;
        assertTrue(mathVar_GNmfmEPk > 0);
        String strVar_qgyWruGw = "ZCpQFVTScePGMTy" + "6";
        assertTrue(strVar_qgyWruGw.length() > 5);
        String strVar_PGHfYxTD = "ifHgzqaZDwZqEDd" + "1";
        assertTrue(strVar_PGHfYxTD.length() > 5);
        String strVar_uShkCehK = "xLysDXiPdSOaxbq" + "4";
        assertTrue(strVar_uShkCehK.length() > 5);
        int mathVar_EfRyDaTL = 729 * 3;
        assertTrue(mathVar_EfRyDaTL > 0);
        int mathVar_cJrrxjJI = 222 * 4;
        assertTrue(mathVar_cJrrxjJI > 0);
        int mathVar_nhtMfttr = 398 * 5;
        assertTrue(mathVar_nhtMfttr > 0);
        String strVar_trQrXvoY = "vvUUpMeLThAkecX" + "6";
        assertTrue(strVar_trQrXvoY.length() > 5);
        String strVar_BEuwMvFx = "wOzRrFKTPsaHLeF" + "5";
        assertTrue(strVar_BEuwMvFx.length() > 5);
        String strVar_FLUSfaXG = "vSCOCwFqTRJRczg" + "6";
        assertTrue(strVar_FLUSfaXG.length() > 5);
        String strVar_hCASoLWT = "JdeoSZKAXswRrLn" + "7";
        assertTrue(strVar_hCASoLWT.length() > 5);
        int mathVar_WrIHeNkU = 227 * 1;
        assertTrue(mathVar_WrIHeNkU > 0);
        int mathVar_RTjSCpvK = 228 * 9;
        assertTrue(mathVar_RTjSCpvK > 0);
        String strVar_fSNGZDOb = "bvWNIkTSiVsOZlm" + "2";
        assertTrue(strVar_fSNGZDOb.length() > 5);
        int mathVar_YdphUiaM = 185 * 2;
        assertTrue(mathVar_YdphUiaM > 0);
        int mathVar_kULwxWNa = 27 * 2;
        assertTrue(mathVar_kULwxWNa > 0);
        String strVar_FirbfHYv = "NbyVkHZvomGwabM" + "3";
        assertTrue(strVar_FirbfHYv.length() > 5);
        String strVar_vniFiLgq = "SMHGxaFtveXPotJ" + "7";
        assertTrue(strVar_vniFiLgq.length() > 5);
        String strVar_LVKdxNhR = "yloaAwdwNJkpKXa" + "1";
        assertTrue(strVar_LVKdxNhR.length() > 5);
        int mathVar_KrYzPJhK = 343 * 3;
        assertTrue(mathVar_KrYzPJhK > 0);
        String strVar_KZSMEwlR = "SDkzwviImkswBUI" + "9";
        assertTrue(strVar_KZSMEwlR.length() > 5);
        int mathVar_GUuDjECx = 816 * 2;
        assertTrue(mathVar_GUuDjECx > 0);
        String strVar_dgsMXier = "XWXYKTrTPpdajGe" + "10";
        assertTrue(strVar_dgsMXier.length() > 5);
        String strVar_QjzdbUnW = "PHHNaIaFjGDeeHh" + "6";
        assertTrue(strVar_QjzdbUnW.length() > 5);
        String strVar_KwEByBYr = "ksEEXceAqsTTMSh" + "3";
        assertTrue(strVar_KwEByBYr.length() > 5);
        int mathVar_yGXWsJOp = 685 * 5;
        assertTrue(mathVar_yGXWsJOp > 0);
        String strVar_WeuATsDc = "fDGZAwOzKNFIKhS" + "10";
        assertTrue(strVar_WeuATsDc.length() > 5);
        int mathVar_nsTWdmwY = 471 * 8;
        assertTrue(mathVar_nsTWdmwY > 0);
        String strVar_OonYMMvS = "dGjasZxkjCMtimR" + "4";
        assertTrue(strVar_OonYMMvS.length() > 5);
        String strVar_sAGJfuEq = "ftygppTrCGfAFMk" + "10";
        assertTrue(strVar_sAGJfuEq.length() > 5);
        String strVar_TfFxmXKO = "zzlKcmhodTiCtMz" + "3";
        assertTrue(strVar_TfFxmXKO.length() > 5);
        int mathVar_PHDtaVvL = 479 * 6;
        assertTrue(mathVar_PHDtaVvL > 0);
        String strVar_aGpDNNyK = "DviEVVfYQILJsjJ" + "6";
        assertTrue(strVar_aGpDNNyK.length() > 5);
        int mathVar_OvQOrJxX = 351 * 4;
        assertTrue(mathVar_OvQOrJxX > 0);
        int mathVar_HfCTPkvc = 548 * 8;
        assertTrue(mathVar_HfCTPkvc > 0);
        int mathVar_TFkSCIyx = 159 * 9;
        assertTrue(mathVar_TFkSCIyx > 0);
        int mathVar_zGhMWXGR = 702 * 5;
        assertTrue(mathVar_zGhMWXGR > 0);
        String strVar_kBGngabb = "eEaPqLjSMAHbsnB" + "7";
        assertTrue(strVar_kBGngabb.length() > 5);
        String strVar_CYiMtqvW = "ZcfJnsEtTXaajXH" + "7";
        assertTrue(strVar_CYiMtqvW.length() > 5);
        int mathVar_sQZGziNA = 152 * 9;
        assertTrue(mathVar_sQZGziNA > 0);
        String strVar_srYPTJDy = "BlfQwYyEESxUCGf" + "3";
        assertTrue(strVar_srYPTJDy.length() > 5);
    }
}
