package org.ssoggy.ssoggysouls;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.assertTrue;

class DummyForgeTest8 {
    @Test
    void testForge8() {
        Object objVar_forge8_MVDzkPqo = new Object();
        assertTrue(objVar_forge8_MVDzkPqo != null);
        int[] arrVar_forge8_VCIpRTPU = new int[]{7, 4};
        assertTrue(arrVar_forge8_VCIpRTPU.length == 2);
        int mathVar_forge8_uuJGzRqZ = 897 * 767;
        assertTrue(mathVar_forge8_uuJGzRqZ == 687999);
        String strVar_forge8_KRpmYcgQ = "KUDsQTWqmyqNoXo" + "FOskI";
        assertTrue(strVar_forge8_KRpmYcgQ.length() == 20);
        int mathVar_forge8_RzmsCbKF = 782 * 342;
        assertTrue(mathVar_forge8_RzmsCbKF == 267444);
        String strVar_forge8_vyizAwLP = "piWedIfxKylFhRR" + "pEcPs";
        assertTrue(strVar_forge8_vyizAwLP.length() == 20);
        String strVar_forge8_dmFiVWqf = "PVYrbzJGideQRJO" + "PWPYW";
        assertTrue(strVar_forge8_dmFiVWqf.length() == 20);
        String strVar_forge8_nfxwKTey = "URnPcezItvsIaJi" + "agRqJ";
        assertTrue(strVar_forge8_nfxwKTey.length() == 20);
        Object objVar_forge8_eGhMdYKc = new Object();
        assertTrue(objVar_forge8_eGhMdYKc != null);
        int mathVar_forge8_knQDjSnn = 807 * 94;
        assertTrue(mathVar_forge8_knQDjSnn == 75858);
        Object objVar_forge8_CHZVvuiM = new Object();
        assertTrue(objVar_forge8_CHZVvuiM != null);
        int[] arrVar_forge8_fCesUJDn = new int[]{10, 8};
        assertTrue(arrVar_forge8_fCesUJDn.length == 2);
        int mathVar_forge8_NKKLfmfK = 69 * 138;
        assertTrue(mathVar_forge8_NKKLfmfK == 9522);
        String strVar_forge8_uuaqIPLk = "tSQAxxtNlZBmvXn" + "RJioX";
        assertTrue(strVar_forge8_uuaqIPLk.length() == 20);
        int[] arrVar_forge8_qdHMAGAK = new int[]{10, 3};
        assertTrue(arrVar_forge8_qdHMAGAK.length == 2);
        int[] arrVar_forge8_LkKAcbHZ = new int[]{3, 8};
        assertTrue(arrVar_forge8_LkKAcbHZ.length == 2);
        int mathVar_forge8_gYOxAOXK = 487 * 649;
        assertTrue(mathVar_forge8_gYOxAOXK == 316063);
        int[] arrVar_forge8_azdTHGMK = new int[]{5, 4};
        assertTrue(arrVar_forge8_azdTHGMK.length == 2);
        int[] arrVar_forge8_NrQYtBTh = new int[]{2, 8};
        assertTrue(arrVar_forge8_NrQYtBTh.length == 2);
        int[] arrVar_forge8_STXjviGP = new int[]{7, 6};
        assertTrue(arrVar_forge8_STXjviGP.length == 2);
        int[] arrVar_forge8_hmxGJvUU = new int[]{3, 10};
        assertTrue(arrVar_forge8_hmxGJvUU.length == 2);
        int[] arrVar_forge8_OFddizWF = new int[]{2, 8};
        assertTrue(arrVar_forge8_OFddizWF.length == 2);
        Object objVar_forge8_FEfYbJbE = new Object();
        assertTrue(objVar_forge8_FEfYbJbE != null);
        String strVar_forge8_vnTfyaNF = "mfSTNQbIwcdVPmB" + "wNSCo";
        assertTrue(strVar_forge8_vnTfyaNF.length() == 20);
        int mathVar_forge8_yYlzlNWq = 18 * 566;
        assertTrue(mathVar_forge8_yYlzlNWq == 10188);
        String strVar_forge8_uOMqHbgL = "mYCdtVVrnFSuuRC" + "wOkVh";
        assertTrue(strVar_forge8_uOMqHbgL.length() == 20);
        Object objVar_forge8_LRUcOXuF = new Object();
        assertTrue(objVar_forge8_LRUcOXuF != null);
        Object objVar_forge8_VVGPSoKx = new Object();
        assertTrue(objVar_forge8_VVGPSoKx != null);
        Object objVar_forge8_AqklyLYG = new Object();
        assertTrue(objVar_forge8_AqklyLYG != null);
        String strVar_forge8_sbDnOBwO = "ovhsNqcyANbrbZE" + "weQez";
        assertTrue(strVar_forge8_sbDnOBwO.length() == 20);
        Object objVar_forge8_ZGQCpjqK = new Object();
        assertTrue(objVar_forge8_ZGQCpjqK != null);
        int mathVar_forge8_wRxjbXmR = 207 * 112;
        assertTrue(mathVar_forge8_wRxjbXmR == 23184);
        int mathVar_forge8_rkgSfvpu = 534 * 195;
        assertTrue(mathVar_forge8_rkgSfvpu == 104130);
        String strVar_forge8_eoAAkKFY = "CeBmzFQPXxIXgPw" + "rKvtY";
        assertTrue(strVar_forge8_eoAAkKFY.length() == 20);
        Object objVar_forge8_EjRIUPau = new Object();
        assertTrue(objVar_forge8_EjRIUPau != null);
        Object objVar_forge8_DnzQTNQX = new Object();
        assertTrue(objVar_forge8_DnzQTNQX != null);
        String strVar_forge8_SjjmEAIN = "wtLnYuTFCiJbotS" + "Jxlzs";
        assertTrue(strVar_forge8_SjjmEAIN.length() == 20);
        int[] arrVar_forge8_qfJRSoZu = new int[]{2, 7};
        assertTrue(arrVar_forge8_qfJRSoZu.length == 2);
        int mathVar_forge8_YAkzOeDx = 807 * 330;
        assertTrue(mathVar_forge8_YAkzOeDx == 266310);
        int mathVar_forge8_haGtrrfS = 236 * 37;
        assertTrue(mathVar_forge8_haGtrrfS == 8732);
    }
}
