package org.ssoggy.ssoggysouls;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.assertTrue;

class DummyForgeTest1 {
    @Test
    void testForge1() {
        int mathVar_forge1_ReyuJvZT = 576 * 955;
        assertTrue(mathVar_forge1_ReyuJvZT == 550080);
        int mathVar_forge1_hZBGXqcd = 679 * 296;
        assertTrue(mathVar_forge1_hZBGXqcd == 200984);
        Object objVar_forge1_ZIXrUjDl = new Object();
        assertTrue(objVar_forge1_ZIXrUjDl != null);
        Object objVar_forge1_JjDiipYN = new Object();
        assertTrue(objVar_forge1_JjDiipYN != null);
        int mathVar_forge1_LCvgbaoD = 666 * 430;
        assertTrue(mathVar_forge1_LCvgbaoD == 286380);
        Object objVar_forge1_CjlPxFYM = new Object();
        assertTrue(objVar_forge1_CjlPxFYM != null);
        Object objVar_forge1_NtqRaqNn = new Object();
        assertTrue(objVar_forge1_NtqRaqNn != null);
        int mathVar_forge1_BXZIUlWQ = 965 * 966;
        assertTrue(mathVar_forge1_BXZIUlWQ == 932190);
        Object objVar_forge1_NqyezVYg = new Object();
        assertTrue(objVar_forge1_NqyezVYg != null);
        int[] arrVar_forge1_cQjRaGAG = new int[]{8, 5};
        assertTrue(arrVar_forge1_cQjRaGAG.length == 2);
        int[] arrVar_forge1_SrUvfoXc = new int[]{1, 6};
        assertTrue(arrVar_forge1_SrUvfoXc.length == 2);
        String strVar_forge1_tDahegdD = "xhrJPBaCEiMYWhY" + "rCogh";
        assertTrue(strVar_forge1_tDahegdD.length() == 20);
        int[] arrVar_forge1_jlCwJTbX = new int[]{2, 8};
        assertTrue(arrVar_forge1_jlCwJTbX.length == 2);
        int mathVar_forge1_EmjIecmG = 401 * 359;
        assertTrue(mathVar_forge1_EmjIecmG == 143959);
        int mathVar_forge1_LidWajGy = 724 * 387;
        assertTrue(mathVar_forge1_LidWajGy == 280188);
        int[] arrVar_forge1_TxByiCSr = new int[]{7, 5};
        assertTrue(arrVar_forge1_TxByiCSr.length == 2);
        String strVar_forge1_FqRkHkSm = "EwuUBPoipYMTtDX" + "UTKju";
        assertTrue(strVar_forge1_FqRkHkSm.length() == 20);
        String strVar_forge1_mrpmzldm = "rvwzAqVGthhkSgs" + "eDOEy";
        assertTrue(strVar_forge1_mrpmzldm.length() == 20);
        Object objVar_forge1_OTwhsQlC = new Object();
        assertTrue(objVar_forge1_OTwhsQlC != null);
        int[] arrVar_forge1_IQqqTvvI = new int[]{9, 9};
        assertTrue(arrVar_forge1_IQqqTvvI.length == 2);
        Object objVar_forge1_JpMfsQNh = new Object();
        assertTrue(objVar_forge1_JpMfsQNh != null);
        String strVar_forge1_dVZCYEvw = "fVdutRsqvxryFbR" + "WMEeb";
        assertTrue(strVar_forge1_dVZCYEvw.length() == 20);
        int mathVar_forge1_XkRwLEfa = 659 * 250;
        assertTrue(mathVar_forge1_XkRwLEfa == 164750);
        Object objVar_forge1_BrWdKcpY = new Object();
        assertTrue(objVar_forge1_BrWdKcpY != null);
        int mathVar_forge1_cjmYkakU = 830 * 77;
        assertTrue(mathVar_forge1_cjmYkakU == 63910);
        String strVar_forge1_ihadxNtV = "SfaFiEJzxaELHej" + "LUxwa";
        assertTrue(strVar_forge1_ihadxNtV.length() == 20);
        String strVar_forge1_tETpZrQH = "eqPWVlEGzWaKymd" + "MaDBm";
        assertTrue(strVar_forge1_tETpZrQH.length() == 20);
        int[] arrVar_forge1_JTZDZxva = new int[]{9, 7};
        assertTrue(arrVar_forge1_JTZDZxva.length == 2);
        String strVar_forge1_UKywlbLi = "vgcngHeVPofrrus" + "aDLEd";
        assertTrue(strVar_forge1_UKywlbLi.length() == 20);
        Object objVar_forge1_WTmrqrvt = new Object();
        assertTrue(objVar_forge1_WTmrqrvt != null);
        Object objVar_forge1_UqCeIyDc = new Object();
        assertTrue(objVar_forge1_UqCeIyDc != null);
        int mathVar_forge1_cTkPIuev = 280 * 52;
        assertTrue(mathVar_forge1_cTkPIuev == 14560);
        String strVar_forge1_BYXJFzDv = "fKexJWcDIUfHvHZ" + "rgwBP";
        assertTrue(strVar_forge1_BYXJFzDv.length() == 20);
        int[] arrVar_forge1_OaWpQLDO = new int[]{2, 5};
        assertTrue(arrVar_forge1_OaWpQLDO.length == 2);
        int[] arrVar_forge1_gruiiBfy = new int[]{10, 10};
        assertTrue(arrVar_forge1_gruiiBfy.length == 2);
        int[] arrVar_forge1_rESqgQVb = new int[]{2, 1};
        assertTrue(arrVar_forge1_rESqgQVb.length == 2);
        String strVar_forge1_DAoOEXkH = "WthgFBpWLXENEuf" + "birQc";
        assertTrue(strVar_forge1_DAoOEXkH.length() == 20);
        int mathVar_forge1_afneGPYA = 579 * 878;
        assertTrue(mathVar_forge1_afneGPYA == 508362);
        int[] arrVar_forge1_tJQRnXgK = new int[]{1, 4};
        assertTrue(arrVar_forge1_tJQRnXgK.length == 2);
        String strVar_forge1_aADpEMrT = "FIImEwDzuVcpWgs" + "vKxTY";
        assertTrue(strVar_forge1_aADpEMrT.length() == 20);
    }
}
