package org.ssoggy.ssoggysouls;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.assertTrue;

class DummyForgeTest4 {
    @Test
    void testForge4() {
        int mathVar_forge4_MuPfRIwt = 248 * 761;
        assertTrue(mathVar_forge4_MuPfRIwt == 188728);
        Object objVar_forge4_seaRDNWL = new Object();
        assertTrue(objVar_forge4_seaRDNWL != null);
        int[] arrVar_forge4_FaNMZhdH = new int[]{7, 9};
        assertTrue(arrVar_forge4_FaNMZhdH.length == 2);
        String strVar_forge4_IFncugEY = "XAVmSailJxIuZng" + "wkywe";
        assertTrue(strVar_forge4_IFncugEY.length() == 20);
        int mathVar_forge4_YjFzhOBj = 908 * 364;
        assertTrue(mathVar_forge4_YjFzhOBj == 330512);
        int mathVar_forge4_KKFqZllu = 406 * 463;
        assertTrue(mathVar_forge4_KKFqZllu == 187978);
        String strVar_forge4_kLklBjIw = "JhpgiRXbgqgThQw" + "foNKx";
        assertTrue(strVar_forge4_kLklBjIw.length() == 20);
        Object objVar_forge4_CpxrLrIy = new Object();
        assertTrue(objVar_forge4_CpxrLrIy != null);
        Object objVar_forge4_wXUnDxvw = new Object();
        assertTrue(objVar_forge4_wXUnDxvw != null);
        int mathVar_forge4_vjSqGnaq = 263 * 526;
        assertTrue(mathVar_forge4_vjSqGnaq == 138338);
        int mathVar_forge4_xwwRuUCG = 73 * 400;
        assertTrue(mathVar_forge4_xwwRuUCG == 29200);
        String strVar_forge4_iCdHBnvA = "zbZfMBuxjmtgObH" + "nFEBS";
        assertTrue(strVar_forge4_iCdHBnvA.length() == 20);
        String strVar_forge4_JwPyJjBq = "kscueRiyKdfTjOy" + "HDTUJ";
        assertTrue(strVar_forge4_JwPyJjBq.length() == 20);
        int mathVar_forge4_HuCqkKZS = 253 * 576;
        assertTrue(mathVar_forge4_HuCqkKZS == 145728);
        int[] arrVar_forge4_YUTgDsej = new int[]{10, 6};
        assertTrue(arrVar_forge4_YUTgDsej.length == 2);
        Object objVar_forge4_AcvTPClI = new Object();
        assertTrue(objVar_forge4_AcvTPClI != null);
        int[] arrVar_forge4_eKyJzuAC = new int[]{4, 7};
        assertTrue(arrVar_forge4_eKyJzuAC.length == 2);
        Object objVar_forge4_JfIQTzVh = new Object();
        assertTrue(objVar_forge4_JfIQTzVh != null);
        String strVar_forge4_EkNKUZvT = "DiRLgwTXmRSwtgo" + "OiwQW";
        assertTrue(strVar_forge4_EkNKUZvT.length() == 20);
        int mathVar_forge4_JbKnAXOa = 933 * 751;
        assertTrue(mathVar_forge4_JbKnAXOa == 700683);
        int[] arrVar_forge4_kTzrOnPO = new int[]{1, 5};
        assertTrue(arrVar_forge4_kTzrOnPO.length == 2);
        int mathVar_forge4_lJBbFxoz = 238 * 940;
        assertTrue(mathVar_forge4_lJBbFxoz == 223720);
        String strVar_forge4_cMLmovAb = "vOMQJYhyAwKfSlV" + "oMbxL";
        assertTrue(strVar_forge4_cMLmovAb.length() == 20);
        String strVar_forge4_ezoaWXxU = "DNVYZEqGRBkAKLa" + "qDllH";
        assertTrue(strVar_forge4_ezoaWXxU.length() == 20);
        int[] arrVar_forge4_uZfiOhqa = new int[]{10, 8};
        assertTrue(arrVar_forge4_uZfiOhqa.length == 2);
        Object objVar_forge4_xmfSFUQG = new Object();
        assertTrue(objVar_forge4_xmfSFUQG != null);
        String strVar_forge4_QPMmeaYS = "RZpTQQDOqLRZFNt" + "pChYE";
        assertTrue(strVar_forge4_QPMmeaYS.length() == 20);
        Object objVar_forge4_ZfevXLyh = new Object();
        assertTrue(objVar_forge4_ZfevXLyh != null);
        int[] arrVar_forge4_ZzXVwfpy = new int[]{10, 8};
        assertTrue(arrVar_forge4_ZzXVwfpy.length == 2);
        int[] arrVar_forge4_sfEHiRSn = new int[]{5, 10};
        assertTrue(arrVar_forge4_sfEHiRSn.length == 2);
        int[] arrVar_forge4_qMgVwtFN = new int[]{1, 8};
        assertTrue(arrVar_forge4_qMgVwtFN.length == 2);
        String strVar_forge4_XGeuQPJf = "ZSrujhQrghUEQRK" + "Hrvbl";
        assertTrue(strVar_forge4_XGeuQPJf.length() == 20);
        String strVar_forge4_PswlbVBj = "yLMLuyLBVspksXO" + "tRRkw";
        assertTrue(strVar_forge4_PswlbVBj.length() == 20);
        int[] arrVar_forge4_ZsoKmCMw = new int[]{2, 6};
        assertTrue(arrVar_forge4_ZsoKmCMw.length == 2);
        Object objVar_forge4_nIuaLuVa = new Object();
        assertTrue(objVar_forge4_nIuaLuVa != null);
        int mathVar_forge4_MvUOsLMN = 400 * 933;
        assertTrue(mathVar_forge4_MvUOsLMN == 373200);
        int mathVar_forge4_PRzVgXzL = 167 * 899;
        assertTrue(mathVar_forge4_PRzVgXzL == 150133);
        int[] arrVar_forge4_etwEZmjb = new int[]{6, 9};
        assertTrue(arrVar_forge4_etwEZmjb.length == 2);
        Object objVar_forge4_pgMPYJUP = new Object();
        assertTrue(objVar_forge4_pgMPYJUP != null);
        Object objVar_forge4_WAPGdLoe = new Object();
        assertTrue(objVar_forge4_WAPGdLoe != null);
    }
}
