package org.ssoggy.ssoggysouls;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.assertTrue;

class DummyForgeTest11 {
    @Test
    void testForge11() {
        String strVar_forge11_rFLwRhhW = "ZRPvDasAJGIFrSh" + "FSklR";
        assertTrue(strVar_forge11_rFLwRhhW.length() == 20);
        int mathVar_forge11_jzleYGBv = 600 * 36;
        assertTrue(mathVar_forge11_jzleYGBv == 21600);
        int mathVar_forge11_AxSddFLS = 979 * 247;
        assertTrue(mathVar_forge11_AxSddFLS == 241813);
        Object objVar_forge11_nVPjzKLV = new Object();
        assertTrue(objVar_forge11_nVPjzKLV != null);
        int[] arrVar_forge11_OngBCPUn = new int[]{6, 1};
        assertTrue(arrVar_forge11_OngBCPUn.length == 2);
        String strVar_forge11_KUFvSIfG = "BzfgjWQYEPSgDVT" + "VjnzI";
        assertTrue(strVar_forge11_KUFvSIfG.length() == 20);
        Object objVar_forge11_nevzWdsn = new Object();
        assertTrue(objVar_forge11_nevzWdsn != null);
        String strVar_forge11_Glmhkmiu = "GgvoMMupXMfHfyJ" + "EjqJq";
        assertTrue(strVar_forge11_Glmhkmiu.length() == 20);
        int mathVar_forge11_AQOmCXDV = 224 * 489;
        assertTrue(mathVar_forge11_AQOmCXDV == 109536);
        int mathVar_forge11_JQVvIbFV = 151 * 812;
        assertTrue(mathVar_forge11_JQVvIbFV == 122612);
        Object objVar_forge11_lCCPudXL = new Object();
        assertTrue(objVar_forge11_lCCPudXL != null);
        Object objVar_forge11_kqIpEmTW = new Object();
        assertTrue(objVar_forge11_kqIpEmTW != null);
        int[] arrVar_forge11_CAuZzZZF = new int[]{7, 2};
        assertTrue(arrVar_forge11_CAuZzZZF.length == 2);
        int mathVar_forge11_JHHHiBvy = 872 * 628;
        assertTrue(mathVar_forge11_JHHHiBvy == 547616);
        String strVar_forge11_kaplFapR = "OOyaWikgaiHoyTo" + "gQlqt";
        assertTrue(strVar_forge11_kaplFapR.length() == 20);
        int mathVar_forge11_tvmJuEtF = 197 * 753;
        assertTrue(mathVar_forge11_tvmJuEtF == 148341);
        String strVar_forge11_CkPsrDVK = "CFMtriBpqaDmAjz" + "rXWCJ";
        assertTrue(strVar_forge11_CkPsrDVK.length() == 20);
        String strVar_forge11_cQumCUgd = "vetNzFNXDRLRGmi" + "xFLDv";
        assertTrue(strVar_forge11_cQumCUgd.length() == 20);
        int mathVar_forge11_wmmUlUMe = 218 * 427;
        assertTrue(mathVar_forge11_wmmUlUMe == 93086);
        int mathVar_forge11_xdLFFCYf = 502 * 388;
        assertTrue(mathVar_forge11_xdLFFCYf == 194776);
        Object objVar_forge11_DPiJmUPv = new Object();
        assertTrue(objVar_forge11_DPiJmUPv != null);
        Object objVar_forge11_JIOjwguZ = new Object();
        assertTrue(objVar_forge11_JIOjwguZ != null);
        Object objVar_forge11_xyOrMJQK = new Object();
        assertTrue(objVar_forge11_xyOrMJQK != null);
        String strVar_forge11_IEVlOUqi = "XjxbiJBMLetPKMl" + "DWtAI";
        assertTrue(strVar_forge11_IEVlOUqi.length() == 20);
        int mathVar_forge11_zzmocnoc = 458 * 796;
        assertTrue(mathVar_forge11_zzmocnoc == 364568);
        int[] arrVar_forge11_domARCCF = new int[]{2, 4};
        assertTrue(arrVar_forge11_domARCCF.length == 2);
        String strVar_forge11_MimpMtAz = "bdaHCMHqinxYaqw" + "AeqIB";
        assertTrue(strVar_forge11_MimpMtAz.length() == 20);
        Object objVar_forge11_nBHqdyAQ = new Object();
        assertTrue(objVar_forge11_nBHqdyAQ != null);
        int[] arrVar_forge11_XwXRxACQ = new int[]{9, 7};
        assertTrue(arrVar_forge11_XwXRxACQ.length == 2);
        int mathVar_forge11_IkGmfcLf = 549 * 331;
        assertTrue(mathVar_forge11_IkGmfcLf == 181719);
        String strVar_forge11_BmYyXYLR = "YPMRUYJvxNmmVHe" + "Mxzkr";
        assertTrue(strVar_forge11_BmYyXYLR.length() == 20);
        int[] arrVar_forge11_qbOOjkKN = new int[]{4, 10};
        assertTrue(arrVar_forge11_qbOOjkKN.length == 2);
        int[] arrVar_forge11_GDDlxHhv = new int[]{2, 3};
        assertTrue(arrVar_forge11_GDDlxHhv.length == 2);
        int[] arrVar_forge11_iBBVdqcL = new int[]{4, 1};
        assertTrue(arrVar_forge11_iBBVdqcL.length == 2);
        String strVar_forge11_AYUFoisE = "rMWiiSdkhvOfhkK" + "fOsRf";
        assertTrue(strVar_forge11_AYUFoisE.length() == 20);
        Object objVar_forge11_XWhIElVi = new Object();
        assertTrue(objVar_forge11_XWhIElVi != null);
        Object objVar_forge11_UGyCtkCl = new Object();
        assertTrue(objVar_forge11_UGyCtkCl != null);
        int[] arrVar_forge11_ZrehexZB = new int[]{3, 1};
        assertTrue(arrVar_forge11_ZrehexZB.length == 2);
        int[] arrVar_forge11_MilbVIRY = new int[]{10, 8};
        assertTrue(arrVar_forge11_MilbVIRY.length == 2);
        int[] arrVar_forge11_uaXaMxQE = new int[]{2, 10};
        assertTrue(arrVar_forge11_uaXaMxQE.length == 2);
    }
}
