package org.ssoggy.ssoggysouls;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.assertTrue;

class DummyForgeTest5 {
    @Test
    void testForge5() {
        int[] arrVar_forge5_aiFahnvP = new int[]{8, 6};
        assertTrue(arrVar_forge5_aiFahnvP.length == 2);
        String strVar_forge5_ZPsSECWz = "BiEWzZilimxrMoM" + "BbxTj";
        assertTrue(strVar_forge5_ZPsSECWz.length() == 20);
        String strVar_forge5_jWlemLYX = "MbqkrhLGdDojowO" + "XLbbU";
        assertTrue(strVar_forge5_jWlemLYX.length() == 20);
        String strVar_forge5_RCXYDDOM = "LYxJEVJoawmSjZt" + "faGOq";
        assertTrue(strVar_forge5_RCXYDDOM.length() == 20);
        int mathVar_forge5_fCPGcvFx = 954 * 537;
        assertTrue(mathVar_forge5_fCPGcvFx == 512298);
        int mathVar_forge5_HziQVIht = 576 * 474;
        assertTrue(mathVar_forge5_HziQVIht == 273024);
        Object objVar_forge5_qspLKkXg = new Object();
        assertTrue(objVar_forge5_qspLKkXg != null);
        Object objVar_forge5_SckoGmUv = new Object();
        assertTrue(objVar_forge5_SckoGmUv != null);
        int mathVar_forge5_nsHvSvth = 684 * 710;
        assertTrue(mathVar_forge5_nsHvSvth == 485640);
        String strVar_forge5_PWbZRaJn = "hQDUlsLYAmnmhdr" + "loIkh";
        assertTrue(strVar_forge5_PWbZRaJn.length() == 20);
        int mathVar_forge5_OAVLXWMZ = 785 * 982;
        assertTrue(mathVar_forge5_OAVLXWMZ == 770870);
        String strVar_forge5_nYMnsdsu = "QteaNrtfbcLlAib" + "UOJoC";
        assertTrue(strVar_forge5_nYMnsdsu.length() == 20);
        int mathVar_forge5_metrILMS = 237 * 65;
        assertTrue(mathVar_forge5_metrILMS == 15405);
        int[] arrVar_forge5_KJOlYdYH = new int[]{6, 10};
        assertTrue(arrVar_forge5_KJOlYdYH.length == 2);
        Object objVar_forge5_uImxvWdw = new Object();
        assertTrue(objVar_forge5_uImxvWdw != null);
        Object objVar_forge5_ZaHrJjTe = new Object();
        assertTrue(objVar_forge5_ZaHrJjTe != null);
        String strVar_forge5_QRDPAJSz = "EbCvaVpGWbZfJfy" + "XReUC";
        assertTrue(strVar_forge5_QRDPAJSz.length() == 20);
        String strVar_forge5_rungCLID = "kpJPwPLaOrpljHo" + "tBspY";
        assertTrue(strVar_forge5_rungCLID.length() == 20);
        int mathVar_forge5_XbqaBmse = 133 * 561;
        assertTrue(mathVar_forge5_XbqaBmse == 74613);
        int[] arrVar_forge5_XOONXqCS = new int[]{2, 10};
        assertTrue(arrVar_forge5_XOONXqCS.length == 2);
        Object objVar_forge5_iUzRBlgd = new Object();
        assertTrue(objVar_forge5_iUzRBlgd != null);
        Object objVar_forge5_DNgTajjZ = new Object();
        assertTrue(objVar_forge5_DNgTajjZ != null);
        Object objVar_forge5_geFCKgnI = new Object();
        assertTrue(objVar_forge5_geFCKgnI != null);
        int[] arrVar_forge5_lRnJtOMT = new int[]{4, 5};
        assertTrue(arrVar_forge5_lRnJtOMT.length == 2);
        Object objVar_forge5_cuAxhYCv = new Object();
        assertTrue(objVar_forge5_cuAxhYCv != null);
        int[] arrVar_forge5_tIcHjNvc = new int[]{3, 2};
        assertTrue(arrVar_forge5_tIcHjNvc.length == 2);
        String strVar_forge5_NNibjxnv = "GbDfrxXleOkRpqG" + "YaQvA";
        assertTrue(strVar_forge5_NNibjxnv.length() == 20);
        int mathVar_forge5_OIosHJFk = 818 * 249;
        assertTrue(mathVar_forge5_OIosHJFk == 203682);
        int mathVar_forge5_vZRosUIQ = 959 * 302;
        assertTrue(mathVar_forge5_vZRosUIQ == 289618);
        int[] arrVar_forge5_kDZarXsh = new int[]{3, 10};
        assertTrue(arrVar_forge5_kDZarXsh.length == 2);
        String strVar_forge5_FbVelVQf = "yBvdSnqDOjAenea" + "kjSXx";
        assertTrue(strVar_forge5_FbVelVQf.length() == 20);
        String strVar_forge5_qWmbYFCO = "uMchHtQtJjPnGjl" + "Lrvel";
        assertTrue(strVar_forge5_qWmbYFCO.length() == 20);
        int[] arrVar_forge5_nyTXxJWE = new int[]{6, 9};
        assertTrue(arrVar_forge5_nyTXxJWE.length == 2);
        int[] arrVar_forge5_oZNBLTER = new int[]{4, 9};
        assertTrue(arrVar_forge5_oZNBLTER.length == 2);
        int[] arrVar_forge5_JwbdFdql = new int[]{7, 2};
        assertTrue(arrVar_forge5_JwbdFdql.length == 2);
        int mathVar_forge5_qmnWqjVD = 407 * 333;
        assertTrue(mathVar_forge5_qmnWqjVD == 135531);
        int[] arrVar_forge5_KmRskCOg = new int[]{7, 10};
        assertTrue(arrVar_forge5_KmRskCOg.length == 2);
        int mathVar_forge5_qwQnjuDI = 359 * 611;
        assertTrue(mathVar_forge5_qwQnjuDI == 219349);
        Object objVar_forge5_DpOIxDpE = new Object();
        assertTrue(objVar_forge5_DpOIxDpE != null);
        Object objVar_forge5_LgzmcNCT = new Object();
        assertTrue(objVar_forge5_LgzmcNCT != null);
    }
}
