package org.ssoggy.ssoggysouls;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.assertTrue;

class DummyForgeTest1 {
    @Test
    void testForge1() {
        int mathVar_IMqLgsOc = 901 * 6;
        assertTrue(mathVar_IMqLgsOc > 0);
        int mathVar_qEYXPtUD = 283 * 3;
        assertTrue(mathVar_qEYXPtUD > 0);
        int mathVar_eGqhCjqh = 126 * 10;
        assertTrue(mathVar_eGqhCjqh > 0);
        int mathVar_pZugvKAD = 828 * 6;
        assertTrue(mathVar_pZugvKAD > 0);
        int mathVar_lTrCfmjN = 217 * 9;
        assertTrue(mathVar_lTrCfmjN > 0);
        String strVar_siGKfvMw = "xeocAOEaoorRXID" + "7";
        assertTrue(strVar_siGKfvMw.length() > 5);
        int mathVar_OJOrFuTC = 315 * 6;
        assertTrue(mathVar_OJOrFuTC > 0);
        String strVar_XRjgbgpa = "FwXmmMjoKKDsoHT" + "6";
        assertTrue(strVar_XRjgbgpa.length() > 5);
        int mathVar_IFgLjkmW = 624 * 8;
        assertTrue(mathVar_IFgLjkmW > 0);
        int mathVar_CWxyHMyw = 241 * 1;
        assertTrue(mathVar_CWxyHMyw > 0);
        int mathVar_LcHPoFHg = 259 * 3;
        assertTrue(mathVar_LcHPoFHg > 0);
        String strVar_OJwCLyrV = "vKNQOvHVWITwsog" + "8";
        assertTrue(strVar_OJwCLyrV.length() > 5);
        String strVar_xNsXOwOT = "tMaloqrUszmOJVF" + "9";
        assertTrue(strVar_xNsXOwOT.length() > 5);
        String strVar_NMtvZxAB = "afQrVMjxUipuPAG" + "5";
        assertTrue(strVar_NMtvZxAB.length() > 5);
        int mathVar_TyrtgjPm = 977 * 4;
        assertTrue(mathVar_TyrtgjPm > 0);
        int mathVar_noUWXOCf = 69 * 2;
        assertTrue(mathVar_noUWXOCf > 0);
        String strVar_lFHGzeCH = "AdnJfLJIdvHgczg" + "7";
        assertTrue(strVar_lFHGzeCH.length() > 5);
        int mathVar_WjJnHMkO = 207 * 4;
        assertTrue(mathVar_WjJnHMkO > 0);
        String strVar_NUhAxXUU = "dXnbZOjLSdEWABc" + "5";
        assertTrue(strVar_NUhAxXUU.length() > 5);
        String strVar_zkpRdHET = "VVKGcfLPnIFNEQm" + "1";
        assertTrue(strVar_zkpRdHET.length() > 5);
        String strVar_knkLlTcE = "mfliyURIcqideMA" + "5";
        assertTrue(strVar_knkLlTcE.length() > 5);
        String strVar_mMNkNpDO = "HgMHqQtNdaYSvfC" + "3";
        assertTrue(strVar_mMNkNpDO.length() > 5);
        int mathVar_YJeoiGUZ = 833 * 1;
        assertTrue(mathVar_YJeoiGUZ > 0);
        String strVar_swRXMfpm = "XjdMYPboMLcVoup" + "8";
        assertTrue(strVar_swRXMfpm.length() > 5);
        int mathVar_sWqGEScz = 438 * 5;
        assertTrue(mathVar_sWqGEScz > 0);
        String strVar_RxtqOatt = "MclPbOtaXqqJDip" + "2";
        assertTrue(strVar_RxtqOatt.length() > 5);
        int mathVar_yAiZpJIE = 265 * 9;
        assertTrue(mathVar_yAiZpJIE > 0);
        String strVar_ItxLzeHU = "gRpnNliIPdDUzCu" + "8";
        assertTrue(strVar_ItxLzeHU.length() > 5);
        int mathVar_gOtyvBnP = 668 * 6;
        assertTrue(mathVar_gOtyvBnP > 0);
        String strVar_tULwFfhM = "pHHlnTclqwZEboq" + "9";
        assertTrue(strVar_tULwFfhM.length() > 5);
        String strVar_yvogIoSK = "kepDKFbgnlTGPDr" + "6";
        assertTrue(strVar_yvogIoSK.length() > 5);
        int mathVar_GFLaYTMh = 367 * 1;
        assertTrue(mathVar_GFLaYTMh > 0);
        int mathVar_lNABUDeG = 280 * 10;
        assertTrue(mathVar_lNABUDeG > 0);
        String strVar_cOLkUXvv = "VQyhXyhsxJinGrd" + "8";
        assertTrue(strVar_cOLkUXvv.length() > 5);
        String strVar_mdqJiWpG = "IBKLTJAsLevcnmr" + "9";
        assertTrue(strVar_mdqJiWpG.length() > 5);
        int mathVar_aRZjrDxf = 436 * 7;
        assertTrue(mathVar_aRZjrDxf > 0);
        String strVar_vdFsUKMG = "nPsaePygDMDQSZh" + "9";
        assertTrue(strVar_vdFsUKMG.length() > 5);
        String strVar_HwQAPFyM = "ELEbDjbJKISKxGk" + "6";
        assertTrue(strVar_HwQAPFyM.length() > 5);
        int mathVar_KxGiZmQj = 986 * 9;
        assertTrue(mathVar_KxGiZmQj > 0);
        String strVar_hvQKgVAO = "mPoRXUHmOsRiVRA" + "5";
        assertTrue(strVar_hvQKgVAO.length() > 5);
        int mathVar_QkKtVejI = 507 * 9;
        assertTrue(mathVar_QkKtVejI > 0);
        String strVar_fBiabLtm = "ITtKavehFrpBTFt" + "3";
        assertTrue(strVar_fBiabLtm.length() > 5);
        String strVar_WTHfZBYu = "VzZQxHXBevNgidw" + "3";
        assertTrue(strVar_WTHfZBYu.length() > 5);
        int mathVar_udyIwAkT = 752 * 5;
        assertTrue(mathVar_udyIwAkT > 0);
        String strVar_JfhSylvS = "XPBMCCTrAcgknOa" + "7";
        assertTrue(strVar_JfhSylvS.length() > 5);
        int mathVar_IIBIyCyk = 483 * 10;
        assertTrue(mathVar_IIBIyCyk > 0);
        int mathVar_tIFcpuoX = 224 * 3;
        assertTrue(mathVar_tIFcpuoX > 0);
        int mathVar_FTtbKJfl = 441 * 8;
        assertTrue(mathVar_FTtbKJfl > 0);
        String strVar_PqyWCJAg = "IUOlFzOkYlVulqB" + "9";
        assertTrue(strVar_PqyWCJAg.length() > 5);
        String strVar_bSFKnwgE = "CQMtpFAeaRGFcHY" + "1";
        assertTrue(strVar_bSFKnwgE.length() > 5);
    }
}
