package org.ssoggy.ssoggysouls;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.assertTrue;

class DummyForgeTest3 {
    @Test
    void testForge3() {
        int[] arrVar_forge3_rpKnlGkX = new int[]{4, 3};
        assertTrue(arrVar_forge3_rpKnlGkX.length == 2);
        int[] arrVar_forge3_DhAYKAwD = new int[]{8, 6};
        assertTrue(arrVar_forge3_DhAYKAwD.length == 2);
        int mathVar_forge3_MNUseNEJ = 64 * 120;
        assertTrue(mathVar_forge3_MNUseNEJ == 7680);
        String strVar_forge3_MpBCdvps = "ZhxBQpQChyrIRgB" + "PbTHN";
        assertTrue(strVar_forge3_MpBCdvps.length() == 20);
        String strVar_forge3_WJpDPfog = "gWEfrNRREdzcRBr" + "MgHMF";
        assertTrue(strVar_forge3_WJpDPfog.length() == 20);
        int mathVar_forge3_MGYhiaik = 805 * 466;
        assertTrue(mathVar_forge3_MGYhiaik == 375130);
        Object objVar_forge3_omtrCYRF = new Object();
        assertTrue(objVar_forge3_omtrCYRF != null);
        Object objVar_forge3_KvuDVWcI = new Object();
        assertTrue(objVar_forge3_KvuDVWcI != null);
        String strVar_forge3_fueTLeyu = "xouTvItbRiansqV" + "ThOoY";
        assertTrue(strVar_forge3_fueTLeyu.length() == 20);
        int mathVar_forge3_bhFvBkrH = 587 * 175;
        assertTrue(mathVar_forge3_bhFvBkrH == 102725);
        Object objVar_forge3_ISzMURqC = new Object();
        assertTrue(objVar_forge3_ISzMURqC != null);
        Object objVar_forge3_cIHibgBT = new Object();
        assertTrue(objVar_forge3_cIHibgBT != null);
        int mathVar_forge3_qrUwVLkd = 561 * 156;
        assertTrue(mathVar_forge3_qrUwVLkd == 87516);
        int[] arrVar_forge3_EFdbRqTD = new int[]{1, 5};
        assertTrue(arrVar_forge3_EFdbRqTD.length == 2);
        Object objVar_forge3_kgOIwzeq = new Object();
        assertTrue(objVar_forge3_kgOIwzeq != null);
        int[] arrVar_forge3_pesnUFoM = new int[]{5, 9};
        assertTrue(arrVar_forge3_pesnUFoM.length == 2);
        int mathVar_forge3_CAVimVHF = 804 * 682;
        assertTrue(mathVar_forge3_CAVimVHF == 548328);
        int[] arrVar_forge3_CKyxDmmy = new int[]{5, 3};
        assertTrue(arrVar_forge3_CKyxDmmy.length == 2);
        int[] arrVar_forge3_nIgyHvyh = new int[]{7, 8};
        assertTrue(arrVar_forge3_nIgyHvyh.length == 2);
        String strVar_forge3_znKyhKhm = "YqBmTPAPPxQabGA" + "UQkrN";
        assertTrue(strVar_forge3_znKyhKhm.length() == 20);
        int[] arrVar_forge3_lUNCfZan = new int[]{4, 5};
        assertTrue(arrVar_forge3_lUNCfZan.length == 2);
        int mathVar_forge3_WTprVPdY = 99 * 309;
        assertTrue(mathVar_forge3_WTprVPdY == 30591);
        String strVar_forge3_huxJajGJ = "VAEbBEurSpqHTmf" + "mdFDe";
        assertTrue(strVar_forge3_huxJajGJ.length() == 20);
        String strVar_forge3_tbkJLgKF = "eceSmZXEvxYQVZP" + "zFEff";
        assertTrue(strVar_forge3_tbkJLgKF.length() == 20);
        Object objVar_forge3_uHfamqBx = new Object();
        assertTrue(objVar_forge3_uHfamqBx != null);
        String strVar_forge3_arajKLmU = "ZGKGbHIWzRedDvL" + "UzqJF";
        assertTrue(strVar_forge3_arajKLmU.length() == 20);
        int[] arrVar_forge3_HKIgsnDk = new int[]{5, 9};
        assertTrue(arrVar_forge3_HKIgsnDk.length == 2);
        int mathVar_forge3_OFehewHI = 605 * 718;
        assertTrue(mathVar_forge3_OFehewHI == 434390);
        Object objVar_forge3_ajSYUFWg = new Object();
        assertTrue(objVar_forge3_ajSYUFWg != null);
        Object objVar_forge3_xyCjIQyI = new Object();
        assertTrue(objVar_forge3_xyCjIQyI != null);
        String strVar_forge3_CHTtQJZq = "UGgVFHooZAhEiHa" + "OhzOy";
        assertTrue(strVar_forge3_CHTtQJZq.length() == 20);
        String strVar_forge3_DrOrgsRD = "BuLwHWnJdWijAft" + "TtDjs";
        assertTrue(strVar_forge3_DrOrgsRD.length() == 20);
        int mathVar_forge3_xJCAoBMb = 257 * 99;
        assertTrue(mathVar_forge3_xJCAoBMb == 25443);
        String strVar_forge3_fdFJmAXs = "ColJANXBEnTIJiK" + "cEfGu";
        assertTrue(strVar_forge3_fdFJmAXs.length() == 20);
        int[] arrVar_forge3_oDYgUuCo = new int[]{9, 3};
        assertTrue(arrVar_forge3_oDYgUuCo.length == 2);
        int[] arrVar_forge3_DJvpvnCD = new int[]{4, 2};
        assertTrue(arrVar_forge3_DJvpvnCD.length == 2);
        Object objVar_forge3_VSzoHrxK = new Object();
        assertTrue(objVar_forge3_VSzoHrxK != null);
        Object objVar_forge3_CYkZPuBQ = new Object();
        assertTrue(objVar_forge3_CYkZPuBQ != null);
        int mathVar_forge3_KbeTNaqo = 684 * 571;
        assertTrue(mathVar_forge3_KbeTNaqo == 390564);
        int mathVar_forge3_JxGBcfzz = 58 * 883;
        assertTrue(mathVar_forge3_JxGBcfzz == 51214);
    }
}
