package org.ssoggy.ssoggysouls;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.assertTrue;

class DummyForgeTest3 {
    @Test
    void testForge3() {
        int mathVar_dpoGcUia = 747 * 7;
        assertTrue(mathVar_dpoGcUia > 0);
        int mathVar_arxPvoOf = 553 * 9;
        assertTrue(mathVar_arxPvoOf > 0);
        String strVar_LqTOFRdc = "zGRiWnRzHUZPRrE" + "4";
        assertTrue(strVar_LqTOFRdc.length() > 5);
        int mathVar_EKkylcEa = 920 * 1;
        assertTrue(mathVar_EKkylcEa > 0);
        int mathVar_HQBTXaGy = 103 * 8;
        assertTrue(mathVar_HQBTXaGy > 0);
        String strVar_wCFeFdQt = "YcSGWADiauulEMM" + "1";
        assertTrue(strVar_wCFeFdQt.length() > 5);
        int mathVar_mCqGVoJl = 181 * 9;
        assertTrue(mathVar_mCqGVoJl > 0);
        int mathVar_hqnAvacc = 298 * 4;
        assertTrue(mathVar_hqnAvacc > 0);
        String strVar_LElZkeFd = "dYZyNDBhSsBIFTU" + "7";
        assertTrue(strVar_LElZkeFd.length() > 5);
        String strVar_WYatheqG = "mVBlXxngpxWgvlU" + "4";
        assertTrue(strVar_WYatheqG.length() > 5);
        String strVar_ilevTvpk = "ZtfPHTpkCVJmIvA" + "4";
        assertTrue(strVar_ilevTvpk.length() > 5);
        String strVar_CnMVdfDM = "dnkpZsMmOlAforj" + "8";
        assertTrue(strVar_CnMVdfDM.length() > 5);
        String strVar_qzxvsLXz = "dJgiPSlHuhNawWN" + "2";
        assertTrue(strVar_qzxvsLXz.length() > 5);
        int mathVar_oXzoLBES = 801 * 7;
        assertTrue(mathVar_oXzoLBES > 0);
        String strVar_moopqvAq = "xtRJWrvZUcqeOel" + "2";
        assertTrue(strVar_moopqvAq.length() > 5);
        int mathVar_RinmBxCM = 259 * 1;
        assertTrue(mathVar_RinmBxCM > 0);
        int mathVar_JexkBAAh = 951 * 8;
        assertTrue(mathVar_JexkBAAh > 0);
        String strVar_fVNmhuCK = "tKiWOyfFAbNzcbh" + "10";
        assertTrue(strVar_fVNmhuCK.length() > 5);
        int mathVar_qLtXqjFh = 58 * 5;
        assertTrue(mathVar_qLtXqjFh > 0);
        int mathVar_UfvhcvwB = 70 * 8;
        assertTrue(mathVar_UfvhcvwB > 0);
        String strVar_ZDWjyLEw = "STiATvThoygTtwN" + "2";
        assertTrue(strVar_ZDWjyLEw.length() > 5);
        int mathVar_wMHgQZkU = 760 * 2;
        assertTrue(mathVar_wMHgQZkU > 0);
        int mathVar_dvLBolBh = 312 * 6;
        assertTrue(mathVar_dvLBolBh > 0);
        int mathVar_OIVUafnR = 996 * 3;
        assertTrue(mathVar_OIVUafnR > 0);
        String strVar_tuxHxSPe = "ggKdSARInYWnxFj" + "5";
        assertTrue(strVar_tuxHxSPe.length() > 5);
        int mathVar_cupytZOH = 894 * 7;
        assertTrue(mathVar_cupytZOH > 0);
        String strVar_NyUHzrLi = "wmvyEiRWfcvvkbl" + "3";
        assertTrue(strVar_NyUHzrLi.length() > 5);
        int mathVar_aVmWNCJa = 396 * 10;
        assertTrue(mathVar_aVmWNCJa > 0);
        String strVar_LpbjSpTy = "qvsJQnikmVEictj" + "3";
        assertTrue(strVar_LpbjSpTy.length() > 5);
        String strVar_jEhqTOVC = "cHPxtpjkRuASFlT" + "7";
        assertTrue(strVar_jEhqTOVC.length() > 5);
        String strVar_xmvFoSGO = "vixWAyuFtkFzOkY" + "2";
        assertTrue(strVar_xmvFoSGO.length() > 5);
        int mathVar_gZGuEzBQ = 68 * 8;
        assertTrue(mathVar_gZGuEzBQ > 0);
        String strVar_KqzAOYLg = "YIycDjMsWlYswYO" + "9";
        assertTrue(strVar_KqzAOYLg.length() > 5);
        int mathVar_gHvvIiJX = 146 * 9;
        assertTrue(mathVar_gHvvIiJX > 0);
        String strVar_RlYSmCOg = "pUbHPtZCcKUWpoR" + "9";
        assertTrue(strVar_RlYSmCOg.length() > 5);
        String strVar_IkhMwWFU = "UsBFmtMnsfPnyyi" + "6";
        assertTrue(strVar_IkhMwWFU.length() > 5);
        int mathVar_smbkEFUq = 410 * 7;
        assertTrue(mathVar_smbkEFUq > 0);
        int mathVar_gdCdhkgx = 670 * 8;
        assertTrue(mathVar_gdCdhkgx > 0);
        int mathVar_OINUZkWU = 861 * 8;
        assertTrue(mathVar_OINUZkWU > 0);
        int mathVar_vDhYiVBo = 454 * 5;
        assertTrue(mathVar_vDhYiVBo > 0);
        String strVar_yiaUgyFq = "XZjvNoHIIYPXxQu" + "3";
        assertTrue(strVar_yiaUgyFq.length() > 5);
        int mathVar_pHjmuADl = 907 * 1;
        assertTrue(mathVar_pHjmuADl > 0);
        String strVar_dhhlHxWg = "UFFYWPhSGUioqzH" + "8";
        assertTrue(strVar_dhhlHxWg.length() > 5);
        int mathVar_XypVhJjb = 944 * 4;
        assertTrue(mathVar_XypVhJjb > 0);
        String strVar_zBCjmAiv = "NbtJecIRwvULbjV" + "9";
        assertTrue(strVar_zBCjmAiv.length() > 5);
        String strVar_RfBiRNxA = "bdgiTPRTlVbRGPn" + "1";
        assertTrue(strVar_RfBiRNxA.length() > 5);
        int mathVar_lfnfwSiT = 291 * 6;
        assertTrue(mathVar_lfnfwSiT > 0);
        String strVar_OXRtBmdw = "hZsAGVNpHmBWYkc" + "1";
        assertTrue(strVar_OXRtBmdw.length() > 5);
        String strVar_wVgYAMWw = "bTQFnCLrbSpqoCn" + "10";
        assertTrue(strVar_wVgYAMWw.length() > 5);
        String strVar_bkwNSlTz = "fKZnNFdsxSKdJWm" + "5";
        assertTrue(strVar_bkwNSlTz.length() > 5);
    }
}
