package org.ssoggy.ssoggysouls;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.assertTrue;

class DummyForgeTest13 {
    @Test
    void testForge13() {
        int[] arrVar_forge13_qtElTugT = new int[]{1, 3};
        assertTrue(arrVar_forge13_qtElTugT.length == 2);
        Object objVar_forge13_ncFnPlmW = new Object();
        assertTrue(objVar_forge13_ncFnPlmW != null);
        String strVar_forge13_hBZyZurY = "YTMuWRDCYBdSlsO" + "qgBDy";
        assertTrue(strVar_forge13_hBZyZurY.length() == 20);
        int mathVar_forge13_iLkytYhX = 989 * 696;
        assertTrue(mathVar_forge13_iLkytYhX == 688344);
        int mathVar_forge13_NJuNgqCt = 737 * 827;
        assertTrue(mathVar_forge13_NJuNgqCt == 609499);
        int mathVar_forge13_rRjmkbcd = 821 * 989;
        assertTrue(mathVar_forge13_rRjmkbcd == 811969);
        Object objVar_forge13_jLHYBhJr = new Object();
        assertTrue(objVar_forge13_jLHYBhJr != null);
        String strVar_forge13_WFmWGIjr = "IYMHIcguCTDxGQi" + "MzPWZ";
        assertTrue(strVar_forge13_WFmWGIjr.length() == 20);
        int mathVar_forge13_GQhzEvUX = 842 * 189;
        assertTrue(mathVar_forge13_GQhzEvUX == 159138);
        Object objVar_forge13_VeMVGKoq = new Object();
        assertTrue(objVar_forge13_VeMVGKoq != null);
        int mathVar_forge13_GTVKeeYQ = 483 * 806;
        assertTrue(mathVar_forge13_GTVKeeYQ == 389298);
        String strVar_forge13_VKKTdxtO = "QqMppgOwBtGFAwE" + "LgXRj";
        assertTrue(strVar_forge13_VKKTdxtO.length() == 20);
        Object objVar_forge13_NUToSAjt = new Object();
        assertTrue(objVar_forge13_NUToSAjt != null);
        String strVar_forge13_xjBERBQd = "NrwwZZjZMsrESBo" + "zezjp";
        assertTrue(strVar_forge13_xjBERBQd.length() == 20);
        int[] arrVar_forge13_DbNwAhrg = new int[]{1, 7};
        assertTrue(arrVar_forge13_DbNwAhrg.length == 2);
        int[] arrVar_forge13_mDynRvpU = new int[]{2, 2};
        assertTrue(arrVar_forge13_mDynRvpU.length == 2);
        String strVar_forge13_IoFcgECq = "wJayGqmiCtyQrCi" + "ZTOnb";
        assertTrue(strVar_forge13_IoFcgECq.length() == 20);
        int[] arrVar_forge13_KdfYkzKc = new int[]{9, 8};
        assertTrue(arrVar_forge13_KdfYkzKc.length == 2);
        int[] arrVar_forge13_DvTvZfsg = new int[]{9, 2};
        assertTrue(arrVar_forge13_DvTvZfsg.length == 2);
        int mathVar_forge13_QJXEtlHY = 878 * 592;
        assertTrue(mathVar_forge13_QJXEtlHY == 519776);
        String strVar_forge13_BUtRpjuZ = "jKtvpudPwVVIdtA" + "uAKXM";
        assertTrue(strVar_forge13_BUtRpjuZ.length() == 20);
        int mathVar_forge13_QRhXiKyI = 332 * 820;
        assertTrue(mathVar_forge13_QRhXiKyI == 272240);
        String strVar_forge13_tzDEoYdU = "sNejZaZObVmGuQj" + "FWNsO";
        assertTrue(strVar_forge13_tzDEoYdU.length() == 20);
        int[] arrVar_forge13_wxMFlqJZ = new int[]{10, 7};
        assertTrue(arrVar_forge13_wxMFlqJZ.length == 2);
        int[] arrVar_forge13_FswdwMeA = new int[]{6, 6};
        assertTrue(arrVar_forge13_FswdwMeA.length == 2);
        int mathVar_forge13_BErOjRHX = 884 * 407;
        assertTrue(mathVar_forge13_BErOjRHX == 359788);
        Object objVar_forge13_WPJsppJg = new Object();
        assertTrue(objVar_forge13_WPJsppJg != null);
        int mathVar_forge13_EUcrffNo = 438 * 104;
        assertTrue(mathVar_forge13_EUcrffNo == 45552);
        Object objVar_forge13_KykCATTw = new Object();
        assertTrue(objVar_forge13_KykCATTw != null);
        Object objVar_forge13_MQTQuCBS = new Object();
        assertTrue(objVar_forge13_MQTQuCBS != null);
        Object objVar_forge13_idCYhaOj = new Object();
        assertTrue(objVar_forge13_idCYhaOj != null);
        String strVar_forge13_xEZGAKjm = "lSLUmsfCeTBTPxF" + "iukRe";
        assertTrue(strVar_forge13_xEZGAKjm.length() == 20);
        Object objVar_forge13_UZZyxOdW = new Object();
        assertTrue(objVar_forge13_UZZyxOdW != null);
        int[] arrVar_forge13_bSfFiRLZ = new int[]{9, 10};
        assertTrue(arrVar_forge13_bSfFiRLZ.length == 2);
        int mathVar_forge13_YCKNDjsr = 317 * 772;
        assertTrue(mathVar_forge13_YCKNDjsr == 244724);
        Object objVar_forge13_WfgraHBe = new Object();
        assertTrue(objVar_forge13_WfgraHBe != null);
        String strVar_forge13_bbGzdDaC = "JaRCegOzbNUtDAF" + "YNZqG";
        assertTrue(strVar_forge13_bbGzdDaC.length() == 20);
        int[] arrVar_forge13_KzOvpLSY = new int[]{10, 1};
        assertTrue(arrVar_forge13_KzOvpLSY.length == 2);
        String strVar_forge13_SvnsDyCH = "cTcCxCJzfoHjZof" + "EtZlT";
        assertTrue(strVar_forge13_SvnsDyCH.length() == 20);
        int[] arrVar_forge13_vWVqwbJj = new int[]{3, 7};
        assertTrue(arrVar_forge13_vWVqwbJj.length == 2);
    }
}
