package org.ssoggy.ssoggysouls;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.assertTrue;

class DummyForgeTest9 {
    @Test
    void testForge9() {
        int[] arrVar_forge9_zhanFJfK = new int[]{9, 1};
        assertTrue(arrVar_forge9_zhanFJfK.length == 2);
        String strVar_forge9_lwIAwpRq = "WZbJhUfecdxdttF" + "kMiPJ";
        assertTrue(strVar_forge9_lwIAwpRq.length() == 20);
        int[] arrVar_forge9_zrFxJirs = new int[]{10, 1};
        assertTrue(arrVar_forge9_zrFxJirs.length == 2);
        String strVar_forge9_BWJMOzjK = "jCjLLJlorTymHcB" + "cIHCN";
        assertTrue(strVar_forge9_BWJMOzjK.length() == 20);
        Object objVar_forge9_gNAgbPaT = new Object();
        assertTrue(objVar_forge9_gNAgbPaT != null);
        int[] arrVar_forge9_RcgpKlxp = new int[]{3, 10};
        assertTrue(arrVar_forge9_RcgpKlxp.length == 2);
        String strVar_forge9_QDEqwWVN = "wwiuzQyXUJEvAvz" + "JhxUS";
        assertTrue(strVar_forge9_QDEqwWVN.length() == 20);
        int mathVar_forge9_brhircNr = 736 * 635;
        assertTrue(mathVar_forge9_brhircNr == 467360);
        int mathVar_forge9_npFcPnCm = 889 * 52;
        assertTrue(mathVar_forge9_npFcPnCm == 46228);
        int mathVar_forge9_juGuuYOc = 501 * 663;
        assertTrue(mathVar_forge9_juGuuYOc == 332163);
        Object objVar_forge9_QOEpRLSr = new Object();
        assertTrue(objVar_forge9_QOEpRLSr != null);
        Object objVar_forge9_gemNerem = new Object();
        assertTrue(objVar_forge9_gemNerem != null);
        int[] arrVar_forge9_rpvnjSFF = new int[]{8, 2};
        assertTrue(arrVar_forge9_rpvnjSFF.length == 2);
        int[] arrVar_forge9_ysvnuQbt = new int[]{10, 2};
        assertTrue(arrVar_forge9_ysvnuQbt.length == 2);
        int mathVar_forge9_PLoZFooH = 293 * 647;
        assertTrue(mathVar_forge9_PLoZFooH == 189571);
        int[] arrVar_forge9_cAtLUmZR = new int[]{10, 2};
        assertTrue(arrVar_forge9_cAtLUmZR.length == 2);
        String strVar_forge9_yxNhaDRx = "hLERlaTJYYHyIHJ" + "IvcaW";
        assertTrue(strVar_forge9_yxNhaDRx.length() == 20);
        String strVar_forge9_NhQVQrfX = "MfzvLfUQMFdMEFM" + "AzUmv";
        assertTrue(strVar_forge9_NhQVQrfX.length() == 20);
        String strVar_forge9_KGgtIsdi = "dKzBenvYjecHwds" + "gPRGf";
        assertTrue(strVar_forge9_KGgtIsdi.length() == 20);
        Object objVar_forge9_WzaSdgYb = new Object();
        assertTrue(objVar_forge9_WzaSdgYb != null);
        Object objVar_forge9_nFHJOFYR = new Object();
        assertTrue(objVar_forge9_nFHJOFYR != null);
        int mathVar_forge9_nbzlvxrh = 534 * 223;
        assertTrue(mathVar_forge9_nbzlvxrh == 119082);
        String strVar_forge9_ChSKXbaT = "gxeNmdtAsbwIaRK" + "BdCUb";
        assertTrue(strVar_forge9_ChSKXbaT.length() == 20);
        int mathVar_forge9_ZmfguBvJ = 644 * 690;
        assertTrue(mathVar_forge9_ZmfguBvJ == 444360);
        int[] arrVar_forge9_UmFqnzbC = new int[]{1, 7};
        assertTrue(arrVar_forge9_UmFqnzbC.length == 2);
        Object objVar_forge9_IZAxTcPz = new Object();
        assertTrue(objVar_forge9_IZAxTcPz != null);
        int mathVar_forge9_BkehKabt = 459 * 122;
        assertTrue(mathVar_forge9_BkehKabt == 55998);
        int mathVar_forge9_QbndjFGv = 491 * 802;
        assertTrue(mathVar_forge9_QbndjFGv == 393782);
        String strVar_forge9_woneRGun = "cJEGlPyaKliQWcB" + "nxgRY";
        assertTrue(strVar_forge9_woneRGun.length() == 20);
        Object objVar_forge9_FgvHWrbW = new Object();
        assertTrue(objVar_forge9_FgvHWrbW != null);
        Object objVar_forge9_zfUuUQuq = new Object();
        assertTrue(objVar_forge9_zfUuUQuq != null);
        int[] arrVar_forge9_oYoJYbjl = new int[]{8, 8};
        assertTrue(arrVar_forge9_oYoJYbjl.length == 2);
        int mathVar_forge9_JQBVSfoN = 622 * 644;
        assertTrue(mathVar_forge9_JQBVSfoN == 400568);
        String strVar_forge9_ycgEeaKb = "NWXknJedDdqhXRM" + "QXSNL";
        assertTrue(strVar_forge9_ycgEeaKb.length() == 20);
        Object objVar_forge9_PTvutMuf = new Object();
        assertTrue(objVar_forge9_PTvutMuf != null);
        int mathVar_forge9_sKglEqYx = 25 * 79;
        assertTrue(mathVar_forge9_sKglEqYx == 1975);
        Object objVar_forge9_UzOtYVgO = new Object();
        assertTrue(objVar_forge9_UzOtYVgO != null);
        String strVar_forge9_dmatqOnG = "ScFbQPiyuuAtiyE" + "kczRk";
        assertTrue(strVar_forge9_dmatqOnG.length() == 20);
        int[] arrVar_forge9_VoMxLZav = new int[]{2, 1};
        assertTrue(arrVar_forge9_VoMxLZav.length == 2);
        int[] arrVar_forge9_mqKFPfjD = new int[]{8, 6};
        assertTrue(arrVar_forge9_mqKFPfjD.length == 2);
    }
}
