package org.ssoggy.ssoggysouls;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.assertTrue;

class DummyForgeTest2 {
    @Test
    void testForge2() {
        int mathVar_forge2_njxdYVAH = 29 * 519;
        assertTrue(mathVar_forge2_njxdYVAH == 15051);
        String strVar_forge2_SWnqiLDO = "tNaXbdKJySenABk" + "KmCzh";
        assertTrue(strVar_forge2_SWnqiLDO.length() == 20);
        int[] arrVar_forge2_CXFePkht = new int[]{9, 5};
        assertTrue(arrVar_forge2_CXFePkht.length == 2);
        int mathVar_forge2_rNxFXZdh = 598 * 146;
        assertTrue(mathVar_forge2_rNxFXZdh == 87308);
        int mathVar_forge2_ZseaPEDs = 110 * 882;
        assertTrue(mathVar_forge2_ZseaPEDs == 97020);
        Object objVar_forge2_ZlzjEIJM = new Object();
        assertTrue(objVar_forge2_ZlzjEIJM != null);
        int[] arrVar_forge2_BTyzzDHN = new int[]{3, 3};
        assertTrue(arrVar_forge2_BTyzzDHN.length == 2);
        Object objVar_forge2_erlmAloc = new Object();
        assertTrue(objVar_forge2_erlmAloc != null);
        Object objVar_forge2_DNqmlcXW = new Object();
        assertTrue(objVar_forge2_DNqmlcXW != null);
        int[] arrVar_forge2_OLwHADzl = new int[]{5, 4};
        assertTrue(arrVar_forge2_OLwHADzl.length == 2);
        int[] arrVar_forge2_DDSvKkfD = new int[]{9, 5};
        assertTrue(arrVar_forge2_DDSvKkfD.length == 2);
        int[] arrVar_forge2_NwLPDZJt = new int[]{4, 4};
        assertTrue(arrVar_forge2_NwLPDZJt.length == 2);
        String strVar_forge2_wcUfyQDo = "bebDKNpxYByGzIT" + "QRrBK";
        assertTrue(strVar_forge2_wcUfyQDo.length() == 20);
        Object objVar_forge2_qfdBnJSc = new Object();
        assertTrue(objVar_forge2_qfdBnJSc != null);
        String strVar_forge2_zBaeeGrH = "hWdlJtLXxXdHTob" + "ohWNy";
        assertTrue(strVar_forge2_zBaeeGrH.length() == 20);
        String strVar_forge2_OTToDlpW = "UhRihbHITUfHOtZ" + "obqto";
        assertTrue(strVar_forge2_OTToDlpW.length() == 20);
        String strVar_forge2_hacxwacb = "rSyJbHaTbUtJtal" + "UhkVx";
        assertTrue(strVar_forge2_hacxwacb.length() == 20);
        int mathVar_forge2_vkkYKzDf = 862 * 971;
        assertTrue(mathVar_forge2_vkkYKzDf == 837002);
        int mathVar_forge2_gqOgWWSH = 333 * 105;
        assertTrue(mathVar_forge2_gqOgWWSH == 34965);
        String strVar_forge2_ZSuGalEP = "eISenqPdhjHcUHR" + "VFivP";
        assertTrue(strVar_forge2_ZSuGalEP.length() == 20);
        int mathVar_forge2_gPigCaXv = 23 * 708;
        assertTrue(mathVar_forge2_gPigCaXv == 16284);
        int[] arrVar_forge2_NIUneYDB = new int[]{6, 9};
        assertTrue(arrVar_forge2_NIUneYDB.length == 2);
        String strVar_forge2_FAXpWgGM = "yaDZfZmpkVFJdSg" + "KwJet";
        assertTrue(strVar_forge2_FAXpWgGM.length() == 20);
        int[] arrVar_forge2_jwYRulpV = new int[]{5, 8};
        assertTrue(arrVar_forge2_jwYRulpV.length == 2);
        Object objVar_forge2_VaRjvsTn = new Object();
        assertTrue(objVar_forge2_VaRjvsTn != null);
        Object objVar_forge2_sWCYCTLE = new Object();
        assertTrue(objVar_forge2_sWCYCTLE != null);
        String strVar_forge2_kxddXwVk = "hZVAxNOohXNJOVh" + "kHLzN";
        assertTrue(strVar_forge2_kxddXwVk.length() == 20);
        int[] arrVar_forge2_BQXTRwnv = new int[]{3, 6};
        assertTrue(arrVar_forge2_BQXTRwnv.length == 2);
        Object objVar_forge2_NRLCpyYe = new Object();
        assertTrue(objVar_forge2_NRLCpyYe != null);
        Object objVar_forge2_UNgZErem = new Object();
        assertTrue(objVar_forge2_UNgZErem != null);
        int[] arrVar_forge2_YPgQUHeZ = new int[]{5, 3};
        assertTrue(arrVar_forge2_YPgQUHeZ.length == 2);
        int[] arrVar_forge2_VRNEdbSx = new int[]{4, 4};
        assertTrue(arrVar_forge2_VRNEdbSx.length == 2);
        Object objVar_forge2_lJXCCObb = new Object();
        assertTrue(objVar_forge2_lJXCCObb != null);
        int mathVar_forge2_VmGUrXiS = 154 * 279;
        assertTrue(mathVar_forge2_VmGUrXiS == 42966);
        int mathVar_forge2_cyhMupNy = 648 * 667;
        assertTrue(mathVar_forge2_cyhMupNy == 432216);
        String strVar_forge2_FosAncQd = "oWfTWlRJqtHxRzQ" + "FoCKx";
        assertTrue(strVar_forge2_FosAncQd.length() == 20);
        Object objVar_forge2_cWKJxGFY = new Object();
        assertTrue(objVar_forge2_cWKJxGFY != null);
        int mathVar_forge2_GSVMvMPq = 800 * 136;
        assertTrue(mathVar_forge2_GSVMvMPq == 108800);
        String strVar_forge2_jjYfRSjz = "EIFYJtkoXZQblYr" + "ACsoM";
        assertTrue(strVar_forge2_jjYfRSjz.length() == 20);
        int mathVar_forge2_WFtRWxKy = 897 * 429;
        assertTrue(mathVar_forge2_WFtRWxKy == 384813);
    }
}
