buildscript {
    repositories {
        maven { url = 'https://repo.papermc.io/repository/maven-public/' }
        mavenCentral()
    }
    configurations.all {
        resolutionStrategy {
            force 'de.siegmar:fastcsv:2.0.0'
        }
    }
}

allprojects {
    apply plugin: 'jacoco'
    jacoco {
        toolVersion = "0.8.15"
    }
}

subprojects {
    apply plugin: 'java'

    test {
        finalizedBy jacocoTestReport
    }

    jacocoTestReport {
        dependsOn test
        reports {
            xml.required = true
            csv.required = false
            html.required = true
        }
    }

    configurations.all {
        resolutionStrategy {
            force 'de.siegmar:fastcsv:2.0.0'
        }
    }

    java {
        sourceCompatibility = JavaVersion.toVersion(Math.min(Integer.parseInt(JavaVersion.current().getMajorVersion()), 25))
        targetCompatibility = JavaVersion.toVersion(Math.min(Integer.parseInt(JavaVersion.current().getMajorVersion()), 25))
    }

    tasks.withType(JavaCompile).configureEach {
        options.release = Math.min(Integer.parseInt(JavaVersion.current().getMajorVersion()), 25)
        options.encoding = 'UTF-8'
    }

    repositories {
        maven { url = 'https://repo.papermc.io/repository/maven-public/' }
        mavenCentral()
        maven { url = 'https://maven.fabricmc.net/' }
        maven { url = 'https://maven.minecraftforge.net/' }
        maven { url = 'https://maven.neoforged.net/releases' }
        maven { url = 'https://repo.papermc.io/repository/maven-public/' }
        maven { url = 'https://hub.spigotmc.org/nexus/content/repositories/snapshots/' }
        maven { url = 'https://maven.terraformersmc.com/releases/' }
    }
}
