buildscript {
    repositories {
        mavenCentral()
    }
    configurations.all {
        resolutionStrategy {
            force 'de.siegmar:fastcsv:2.0.0'
        }
    }
}

def isJava25 = JavaVersion.current().getMajorVersion().toInteger() >= 25

allprojects {
    apply plugin: 'jacoco'
    jacoco {
        toolVersion = isJava25 ? "0.8.15" : "0.8.12"
    }
}

subprojects {
    apply plugin: 'java'

    test {
        finalizedBy jacocoTestReport
    }

    jacocoTestReport {
        dependsOn test
        reports {
            xml.required = true
            csv.required = false
            html.required = true
        }
    }

    configurations.all {
        resolutionStrategy {
            force 'de.siegmar:fastcsv:2.0.0'
        }
    }

    def targetJavaVersion = isJava25 ? 25 : 21

    java {
        sourceCompatibility = JavaVersion.toVersion(targetJavaVersion)
        targetCompatibility = JavaVersion.toVersion(targetJavaVersion)
    }

    tasks.withType(JavaCompile).configureEach {
        options.release = targetJavaVersion
        options.encoding = 'UTF-8'
    }

    repositories {
        mavenCentral()
        maven { url = 'https://maven.fabricmc.net/' }
        maven { url = 'https://maven.minecraftforge.net/' }
        maven { url = 'https://maven.neoforged.net/releases' }
        maven { url = 'https://repo.papermc.io/repository/maven-public/' }
        maven { url = 'https://hub.spigotmc.org/nexus/content/repositories/snapshots/' }
        maven { url = 'https://maven.terraformersmc.com/releases/' }
    }
}
