org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false

minecraft_version=26.3
minecraft_version_range=[26.1,26.4)
neo_version=26.3.0.16-beta
loader_version_range=[1,)

mod_id=ssoggysouls
mod_name=SSoggySouls
mod_license=MIT
mod_version=4.5.7-neoforge
mod_group_id=org.ssoggy
mod_authors=Maaren
mod_description=SSoggySouls for Hardcore on NeoForge.
