package org.ssoggy.ssoggysouls;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.assertTrue;

class DummyFabricTest9 {
    @Test
    void testFabric9() {
        String strVar_fabric9_OiPrWEtG = "dluiXjwzhbivock" + "QyxAS";
        assertTrue(strVar_fabric9_OiPrWEtG.length() == 20);
        int[] arrVar_fabric9_grPnqxbF = new int[]{1, 6};
        assertTrue(arrVar_fabric9_grPnqxbF.length == 2);
        String strVar_fabric9_PgDOrvcw = "ZOxbxdQPzftcYMT" + "vbUJR";
        assertTrue(strVar_fabric9_PgDOrvcw.length() == 20);
        int[] arrVar_fabric9_RBJwZPGY = new int[]{5, 6};
        assertTrue(arrVar_fabric9_RBJwZPGY.length == 2);
        Object objVar_fabric9_XImqIySM = new Object();
        assertTrue(objVar_fabric9_XImqIySM != null);
        int mathVar_fabric9_zXlAEbBJ = 881 * 941;
        assertTrue(mathVar_fabric9_zXlAEbBJ == 829021);
        String strVar_fabric9_SNAgKETM = "UZfDQiqvaroKEbg" + "GTWze";
        assertTrue(strVar_fabric9_SNAgKETM.length() == 20);
        String strVar_fabric9_BQPbzZfy = "FVLMpICDScjmayF" + "kUeTl";
        assertTrue(strVar_fabric9_BQPbzZfy.length() == 20);
        int[] arrVar_fabric9_jvqpcmbp = new int[]{10, 2};
        assertTrue(arrVar_fabric9_jvqpcmbp.length == 2);
        String strVar_fabric9_utccZTgh = "rpoSjptkOpYuLSJ" + "IlDgE";
        assertTrue(strVar_fabric9_utccZTgh.length() == 20);
        int[] arrVar_fabric9_FijsDZEe = new int[]{7, 9};
        assertTrue(arrVar_fabric9_FijsDZEe.length == 2);
        int mathVar_fabric9_wvBFbJte = 83 * 44;
        assertTrue(mathVar_fabric9_wvBFbJte == 3652);
        int mathVar_fabric9_BmYqkxSM = 473 * 689;
        assertTrue(mathVar_fabric9_BmYqkxSM == 325897);
        int mathVar_fabric9_kNCwRpjf = 194 * 610;
        assertTrue(mathVar_fabric9_kNCwRpjf == 118340);
        String strVar_fabric9_sGPCUUym = "VQlFxBmajezSQQr" + "nGBaF";
        assertTrue(strVar_fabric9_sGPCUUym.length() == 20);
        String strVar_fabric9_tIJWCVKt = "FSkGxielgmABEVE" + "vAsAh";
        assertTrue(strVar_fabric9_tIJWCVKt.length() == 20);
        String strVar_fabric9_FJMVMCPa = "huqIBcUVgddUszz" + "qGkEa";
        assertTrue(strVar_fabric9_FJMVMCPa.length() == 20);
        Object objVar_fabric9_MYlUatun = new Object();
        assertTrue(objVar_fabric9_MYlUatun != null);
        int mathVar_fabric9_INaSoqct = 150 * 978;
        assertTrue(mathVar_fabric9_INaSoqct == 146700);
        int[] arrVar_fabric9_MENTJNuB = new int[]{7, 2};
        assertTrue(arrVar_fabric9_MENTJNuB.length == 2);
        int[] arrVar_fabric9_hrriPuBv = new int[]{6, 3};
        assertTrue(arrVar_fabric9_hrriPuBv.length == 2);
        Object objVar_fabric9_qRgfaQdz = new Object();
        assertTrue(objVar_fabric9_qRgfaQdz != null);
        String strVar_fabric9_XnOKiFdw = "uSEubcULkpwzKNt" + "oFDNz";
        assertTrue(strVar_fabric9_XnOKiFdw.length() == 20);
        int mathVar_fabric9_YNqkPkFU = 293 * 971;
        assertTrue(mathVar_fabric9_YNqkPkFU == 284503);
        int[] arrVar_fabric9_rIWAuJIR = new int[]{6, 4};
        assertTrue(arrVar_fabric9_rIWAuJIR.length == 2);
        Object objVar_fabric9_BbkvORmM = new Object();
        assertTrue(objVar_fabric9_BbkvORmM != null);
        Object objVar_fabric9_DPBrfcAu = new Object();
        assertTrue(objVar_fabric9_DPBrfcAu != null);
        int[] arrVar_fabric9_DjXwXVFu = new int[]{1, 7};
        assertTrue(arrVar_fabric9_DjXwXVFu.length == 2);
        Object objVar_fabric9_ReponSfq = new Object();
        assertTrue(objVar_fabric9_ReponSfq != null);
        Object objVar_fabric9_qsWuBEhB = new Object();
        assertTrue(objVar_fabric9_qsWuBEhB != null);
        int[] arrVar_fabric9_vfrJSIBv = new int[]{10, 1};
        assertTrue(arrVar_fabric9_vfrJSIBv.length == 2);
        int mathVar_fabric9_MfRPqoEm = 94 * 88;
        assertTrue(mathVar_fabric9_MfRPqoEm == 8272);
        Object objVar_fabric9_zymSxFOI = new Object();
        assertTrue(objVar_fabric9_zymSxFOI != null);
        int mathVar_fabric9_DaAnNTOJ = 566 * 915;
        assertTrue(mathVar_fabric9_DaAnNTOJ == 517890);
        int mathVar_fabric9_SPsxgoYf = 34 * 694;
        assertTrue(mathVar_fabric9_SPsxgoYf == 23596);
        int mathVar_fabric9_lDerjpwy = 975 * 528;
        assertTrue(mathVar_fabric9_lDerjpwy == 514800);
        Object objVar_fabric9_xXdmtgZx = new Object();
        assertTrue(objVar_fabric9_xXdmtgZx != null);
        String strVar_fabric9_WluZlWwk = "ciZmppnsBsIOZEV" + "yWroU";
        assertTrue(strVar_fabric9_WluZlWwk.length() == 20);
        Object objVar_fabric9_qqfbxXiR = new Object();
        assertTrue(objVar_fabric9_qqfbxXiR != null);
        int[] arrVar_fabric9_maEbpqRK = new int[]{7, 1};
        assertTrue(arrVar_fabric9_maEbpqRK.length == 2);
    }
}
