package org.ssoggy.ssoggysouls;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.assertTrue;

class DummyFabricTest10 {
    @Test
    void testFabric10() {
        String strVar_fabric10_cNahhqsa = "pehPQUXhwFzekgR" + "vTDSG";
        assertTrue(strVar_fabric10_cNahhqsa.length() == 20);
        int mathVar_fabric10_dDOyLreq = 952 * 216;
        assertTrue(mathVar_fabric10_dDOyLreq == 205632);
        String strVar_fabric10_FyiQJBlh = "zNaZHxezWyVBwmD" + "nltdh";
        assertTrue(strVar_fabric10_FyiQJBlh.length() == 20);
        Object objVar_fabric10_XoBFBTlG = new Object();
        assertTrue(objVar_fabric10_XoBFBTlG != null);
        String strVar_fabric10_GrNnZffd = "PXmxZeIASlxUOcO" + "zrOlE";
        assertTrue(strVar_fabric10_GrNnZffd.length() == 20);
        String strVar_fabric10_UoaCaNUi = "FrdsOEJXyxJZGaX" + "XHAfv";
        assertTrue(strVar_fabric10_UoaCaNUi.length() == 20);
        int mathVar_fabric10_qAEhaoqR = 758 * 294;
        assertTrue(mathVar_fabric10_qAEhaoqR == 222852);
        Object objVar_fabric10_oFRnOVyK = new Object();
        assertTrue(objVar_fabric10_oFRnOVyK != null);
        String strVar_fabric10_QcaCilPY = "bxmZQkJjsSWXCGX" + "gEUet";
        assertTrue(strVar_fabric10_QcaCilPY.length() == 20);
        Object objVar_fabric10_zxMTANSi = new Object();
        assertTrue(objVar_fabric10_zxMTANSi != null);
        Object objVar_fabric10_BKZbHIcf = new Object();
        assertTrue(objVar_fabric10_BKZbHIcf != null);
        int[] arrVar_fabric10_VJVqdmGJ = new int[]{4, 5};
        assertTrue(arrVar_fabric10_VJVqdmGJ.length == 2);
        int[] arrVar_fabric10_JYewhQac = new int[]{4, 1};
        assertTrue(arrVar_fabric10_JYewhQac.length == 2);
        Object objVar_fabric10_DMbnRRPS = new Object();
        assertTrue(objVar_fabric10_DMbnRRPS != null);
        int[] arrVar_fabric10_nQYiirUZ = new int[]{5, 5};
        assertTrue(arrVar_fabric10_nQYiirUZ.length == 2);
        int[] arrVar_fabric10_zwATYvrY = new int[]{4, 4};
        assertTrue(arrVar_fabric10_zwATYvrY.length == 2);
        String strVar_fabric10_BsMESBnH = "fShVzQnUFZORrLH" + "vSDEv";
        assertTrue(strVar_fabric10_BsMESBnH.length() == 20);
        int[] arrVar_fabric10_rUSKAIZe = new int[]{3, 9};
        assertTrue(arrVar_fabric10_rUSKAIZe.length == 2);
        int mathVar_fabric10_KwMBcTKD = 86 * 772;
        assertTrue(mathVar_fabric10_KwMBcTKD == 66392);
        int mathVar_fabric10_YuYVfcyL = 50 * 458;
        assertTrue(mathVar_fabric10_YuYVfcyL == 22900);
        Object objVar_fabric10_ZLSWvdKw = new Object();
        assertTrue(objVar_fabric10_ZLSWvdKw != null);
        int[] arrVar_fabric10_TbPovoWY = new int[]{3, 9};
        assertTrue(arrVar_fabric10_TbPovoWY.length == 2);
        String strVar_fabric10_WodGnpYK = "ofgbLWrsKdcmBYB" + "ZYNRg";
        assertTrue(strVar_fabric10_WodGnpYK.length() == 20);
        int mathVar_fabric10_CQKguIyK = 734 * 646;
        assertTrue(mathVar_fabric10_CQKguIyK == 474164);
        int[] arrVar_fabric10_TSpobluH = new int[]{10, 9};
        assertTrue(arrVar_fabric10_TSpobluH.length == 2);
        Object objVar_fabric10_epIHCzFe = new Object();
        assertTrue(objVar_fabric10_epIHCzFe != null);
        int[] arrVar_fabric10_dTwXaCai = new int[]{1, 5};
        assertTrue(arrVar_fabric10_dTwXaCai.length == 2);
        String strVar_fabric10_KxdaqApC = "KyVMJDxNaJfuqKt" + "mvXdD";
        assertTrue(strVar_fabric10_KxdaqApC.length() == 20);
        Object objVar_fabric10_jNuewfFv = new Object();
        assertTrue(objVar_fabric10_jNuewfFv != null);
        int mathVar_fabric10_yvWvrRQf = 903 * 62;
        assertTrue(mathVar_fabric10_yvWvrRQf == 55986);
        int mathVar_fabric10_SpIywipt = 917 * 813;
        assertTrue(mathVar_fabric10_SpIywipt == 745521);
        Object objVar_fabric10_gGxFwzeW = new Object();
        assertTrue(objVar_fabric10_gGxFwzeW != null);
        String strVar_fabric10_JXcmYhDU = "dXlcsnSzdNTyunR" + "CpdTG";
        assertTrue(strVar_fabric10_JXcmYhDU.length() == 20);
        Object objVar_fabric10_MAFWtoNl = new Object();
        assertTrue(objVar_fabric10_MAFWtoNl != null);
        int mathVar_fabric10_DMyQSXWO = 697 * 144;
        assertTrue(mathVar_fabric10_DMyQSXWO == 100368);
        int[] arrVar_fabric10_watbxfpT = new int[]{4, 2};
        assertTrue(arrVar_fabric10_watbxfpT.length == 2);
        int mathVar_fabric10_MhlzhIat = 487 * 110;
        assertTrue(mathVar_fabric10_MhlzhIat == 53570);
        String strVar_fabric10_LaDvEdQD = "TPOHHsXOOOtZful" + "dSjjs";
        assertTrue(strVar_fabric10_LaDvEdQD.length() == 20);
        int mathVar_fabric10_cIRDizKI = 201 * 746;
        assertTrue(mathVar_fabric10_cIRDizKI == 149946);
        int[] arrVar_fabric10_RrOvOahJ = new int[]{2, 6};
        assertTrue(arrVar_fabric10_RrOvOahJ.length == 2);
    }
}
