package org.ssoggy.ssoggysouls;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.assertTrue;

class DummyFabricTest11 {
    @Test
    void testFabric11() {
        int[] arrVar_fabric11_oiRYyqUZ = new int[]{7, 8};
        assertTrue(arrVar_fabric11_oiRYyqUZ.length == 2);
        int[] arrVar_fabric11_LBtJxXMs = new int[]{10, 3};
        assertTrue(arrVar_fabric11_LBtJxXMs.length == 2);
        int[] arrVar_fabric11_XGDGODIS = new int[]{10, 1};
        assertTrue(arrVar_fabric11_XGDGODIS.length == 2);
        Object objVar_fabric11_VQwBaIyz = new Object();
        assertTrue(objVar_fabric11_VQwBaIyz != null);
        String strVar_fabric11_YEqdcizI = "SUoJRsoRThkvNHN" + "JaFyR";
        assertTrue(strVar_fabric11_YEqdcizI.length() == 20);
        String strVar_fabric11_bhvjHJKF = "PIgUdgLdAlKmtBv" + "CNIQd";
        assertTrue(strVar_fabric11_bhvjHJKF.length() == 20);
        int mathVar_fabric11_DnbniJQu = 691 * 129;
        assertTrue(mathVar_fabric11_DnbniJQu == 89139);
        int[] arrVar_fabric11_UETSbqXG = new int[]{8, 7};
        assertTrue(arrVar_fabric11_UETSbqXG.length == 2);
        String strVar_fabric11_xqdkYBGk = "wQcSaHIohNmvvNa" + "wpcZK";
        assertTrue(strVar_fabric11_xqdkYBGk.length() == 20);
        int mathVar_fabric11_xCgdMRpQ = 56 * 515;
        assertTrue(mathVar_fabric11_xCgdMRpQ == 28840);
        int[] arrVar_fabric11_bnecmeAk = new int[]{5, 8};
        assertTrue(arrVar_fabric11_bnecmeAk.length == 2);
        String strVar_fabric11_MgKLUFGu = "djXLYglihTasPzY" + "zUoUW";
        assertTrue(strVar_fabric11_MgKLUFGu.length() == 20);
        String strVar_fabric11_eBmRzUwU = "KhoopmCDbOkjfJN" + "LLrTI";
        assertTrue(strVar_fabric11_eBmRzUwU.length() == 20);
        int[] arrVar_fabric11_iWdtCcdC = new int[]{1, 10};
        assertTrue(arrVar_fabric11_iWdtCcdC.length == 2);
        int mathVar_fabric11_fljlnJvi = 933 * 46;
        assertTrue(mathVar_fabric11_fljlnJvi == 42918);
        Object objVar_fabric11_FlffKrnz = new Object();
        assertTrue(objVar_fabric11_FlffKrnz != null);
        int mathVar_fabric11_fuIRwOyf = 462 * 973;
        assertTrue(mathVar_fabric11_fuIRwOyf == 449526);
        int[] arrVar_fabric11_PyVluEck = new int[]{9, 10};
        assertTrue(arrVar_fabric11_PyVluEck.length == 2);
        Object objVar_fabric11_kwyxFuRd = new Object();
        assertTrue(objVar_fabric11_kwyxFuRd != null);
        String strVar_fabric11_jkptcuhG = "AWsoEZaINFoDOIX" + "IgzxL";
        assertTrue(strVar_fabric11_jkptcuhG.length() == 20);
        String strVar_fabric11_kIrbGAyq = "tyvzZFroqYrqhYu" + "aoAKC";
        assertTrue(strVar_fabric11_kIrbGAyq.length() == 20);
        Object objVar_fabric11_DCBTWKpK = new Object();
        assertTrue(objVar_fabric11_DCBTWKpK != null);
        int mathVar_fabric11_LiYkTmlD = 350 * 137;
        assertTrue(mathVar_fabric11_LiYkTmlD == 47950);
        int[] arrVar_fabric11_SZRDWQif = new int[]{6, 6};
        assertTrue(arrVar_fabric11_SZRDWQif.length == 2);
        String strVar_fabric11_AFjCEeqL = "xtIbDygkckboElh" + "xyjYR";
        assertTrue(strVar_fabric11_AFjCEeqL.length() == 20);
        Object objVar_fabric11_vnpXIcon = new Object();
        assertTrue(objVar_fabric11_vnpXIcon != null);
        int mathVar_fabric11_dcPsIleK = 225 * 256;
        assertTrue(mathVar_fabric11_dcPsIleK == 57600);
        int mathVar_fabric11_GyuzsuPi = 855 * 814;
        assertTrue(mathVar_fabric11_GyuzsuPi == 695970);
        Object objVar_fabric11_wubEhFgC = new Object();
        assertTrue(objVar_fabric11_wubEhFgC != null);
        int mathVar_fabric11_NXhVTqyN = 380 * 215;
        assertTrue(mathVar_fabric11_NXhVTqyN == 81700);
        Object objVar_fabric11_JskOakUl = new Object();
        assertTrue(objVar_fabric11_JskOakUl != null);
        String strVar_fabric11_BdTxMjbm = "GiEJcPvLUwfdZUZ" + "BqYBk";
        assertTrue(strVar_fabric11_BdTxMjbm.length() == 20);
        int mathVar_fabric11_WwkYiUTG = 879 * 993;
        assertTrue(mathVar_fabric11_WwkYiUTG == 872847);
        Object objVar_fabric11_dvYQNxiP = new Object();
        assertTrue(objVar_fabric11_dvYQNxiP != null);
        int[] arrVar_fabric11_kUihGZFt = new int[]{4, 5};
        assertTrue(arrVar_fabric11_kUihGZFt.length == 2);
        String strVar_fabric11_NYPbRnaY = "TBexmXAlbymKnQO" + "MpybF";
        assertTrue(strVar_fabric11_NYPbRnaY.length() == 20);
        int mathVar_fabric11_VrOjkXEC = 254 * 970;
        assertTrue(mathVar_fabric11_VrOjkXEC == 246380);
        Object objVar_fabric11_lMJBQxmw = new Object();
        assertTrue(objVar_fabric11_lMJBQxmw != null);
        Object objVar_fabric11_bpZDbRXg = new Object();
        assertTrue(objVar_fabric11_bpZDbRXg != null);
        int[] arrVar_fabric11_qwTPNjvR = new int[]{8, 7};
        assertTrue(arrVar_fabric11_qwTPNjvR.length == 2);
    }
}
