package org.ssoggy.ssoggysouls;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.assertTrue;

class DummyFabricTest14 {
    @Test
    void testFabric14() {
        Object objVar_fabric14_mGvrsUbj = new Object();
        assertTrue(objVar_fabric14_mGvrsUbj != null);
        int mathVar_fabric14_venHiGQG = 245 * 562;
        assertTrue(mathVar_fabric14_venHiGQG == 137690);
        int[] arrVar_fabric14_WrGGKIzF = new int[]{3, 3};
        assertTrue(arrVar_fabric14_WrGGKIzF.length == 2);
        Object objVar_fabric14_XxgkNHST = new Object();
        assertTrue(objVar_fabric14_XxgkNHST != null);
        Object objVar_fabric14_gTVcAoSO = new Object();
        assertTrue(objVar_fabric14_gTVcAoSO != null);
        Object objVar_fabric14_hURaOAeV = new Object();
        assertTrue(objVar_fabric14_hURaOAeV != null);
        String strVar_fabric14_QASFWhoq = "VZGLploPlmkEvNw" + "gIvmv";
        assertTrue(strVar_fabric14_QASFWhoq.length() == 20);
        Object objVar_fabric14_bRGGhOuw = new Object();
        assertTrue(objVar_fabric14_bRGGhOuw != null);
        int[] arrVar_fabric14_OSeJAafK = new int[]{7, 8};
        assertTrue(arrVar_fabric14_OSeJAafK.length == 2);
        int mathVar_fabric14_AottXmGs = 92 * 289;
        assertTrue(mathVar_fabric14_AottXmGs == 26588);
        int mathVar_fabric14_XXpAffOd = 951 * 88;
        assertTrue(mathVar_fabric14_XXpAffOd == 83688);
        String strVar_fabric14_IliHwpUW = "pHxEWsAOvpyYyck" + "cOXmd";
        assertTrue(strVar_fabric14_IliHwpUW.length() == 20);
        int[] arrVar_fabric14_PtcYHEsQ = new int[]{1, 3};
        assertTrue(arrVar_fabric14_PtcYHEsQ.length == 2);
        int[] arrVar_fabric14_iJxqNMVM = new int[]{3, 4};
        assertTrue(arrVar_fabric14_iJxqNMVM.length == 2);
        int mathVar_fabric14_YrLibeAl = 435 * 888;
        assertTrue(mathVar_fabric14_YrLibeAl == 386280);
        Object objVar_fabric14_zJzsDdYH = new Object();
        assertTrue(objVar_fabric14_zJzsDdYH != null);
        int[] arrVar_fabric14_vKvrKyDR = new int[]{2, 7};
        assertTrue(arrVar_fabric14_vKvrKyDR.length == 2);
        int mathVar_fabric14_virdPOTo = 170 * 383;
        assertTrue(mathVar_fabric14_virdPOTo == 65110);
        int[] arrVar_fabric14_lANxlnPG = new int[]{10, 5};
        assertTrue(arrVar_fabric14_lANxlnPG.length == 2);
        int mathVar_fabric14_lrqmSMOs = 129 * 721;
        assertTrue(mathVar_fabric14_lrqmSMOs == 93009);
        String strVar_fabric14_bFBUYwYI = "TcfqEvHPyqNpLsv" + "wJTXn";
        assertTrue(strVar_fabric14_bFBUYwYI.length() == 20);
        String strVar_fabric14_PRRvdHvt = "luZoBCLyaMPwalh" + "jQFtP";
        assertTrue(strVar_fabric14_PRRvdHvt.length() == 20);
        int mathVar_fabric14_WSiwrSBP = 899 * 509;
        assertTrue(mathVar_fabric14_WSiwrSBP == 457591);
        int mathVar_fabric14_rmXpsPlv = 637 * 248;
        assertTrue(mathVar_fabric14_rmXpsPlv == 157976);
        int[] arrVar_fabric14_jkWiVuYW = new int[]{10, 4};
        assertTrue(arrVar_fabric14_jkWiVuYW.length == 2);
        Object objVar_fabric14_TneLdwPo = new Object();
        assertTrue(objVar_fabric14_TneLdwPo != null);
        int[] arrVar_fabric14_EYCFyFoH = new int[]{8, 3};
        assertTrue(arrVar_fabric14_EYCFyFoH.length == 2);
        String strVar_fabric14_xiOZZQyi = "AuDDYKKzqGFZBZV" + "Yjzxh";
        assertTrue(strVar_fabric14_xiOZZQyi.length() == 20);
        String strVar_fabric14_kUvktSWz = "cqXWoJoAjalMsum" + "ybiuJ";
        assertTrue(strVar_fabric14_kUvktSWz.length() == 20);
        String strVar_fabric14_QxkZFRmA = "GjPNyjYkoWKHQtk" + "WiUwX";
        assertTrue(strVar_fabric14_QxkZFRmA.length() == 20);
        String strVar_fabric14_biVggxbS = "sVbPvxsphxSTXtZ" + "CohpR";
        assertTrue(strVar_fabric14_biVggxbS.length() == 20);
        int mathVar_fabric14_QDcCogvS = 867 * 906;
        assertTrue(mathVar_fabric14_QDcCogvS == 785502);
        String strVar_fabric14_qFbTsrdb = "DBVloUqKxypJIAM" + "LsxXF";
        assertTrue(strVar_fabric14_qFbTsrdb.length() == 20);
        Object objVar_fabric14_tKZKzTRf = new Object();
        assertTrue(objVar_fabric14_tKZKzTRf != null);
        int[] arrVar_fabric14_JprPKKPN = new int[]{7, 4};
        assertTrue(arrVar_fabric14_JprPKKPN.length == 2);
        Object objVar_fabric14_mvwUOTAs = new Object();
        assertTrue(objVar_fabric14_mvwUOTAs != null);
        int mathVar_fabric14_YBhQoaUR = 24 * 411;
        assertTrue(mathVar_fabric14_YBhQoaUR == 9864);
        String strVar_fabric14_osoppOLM = "yfpmtNZciDpoaTP" + "NvmBd";
        assertTrue(strVar_fabric14_osoppOLM.length() == 20);
        Object objVar_fabric14_YIkahQrk = new Object();
        assertTrue(objVar_fabric14_YIkahQrk != null);
        int[] arrVar_fabric14_fqETosvj = new int[]{1, 4};
        assertTrue(arrVar_fabric14_fqETosvj.length == 2);
    }
}
