package org.ssoggy.ssoggysouls;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.assertTrue;

class DummyFabricTest1 {
    @Test
    void testFabric1() {
        int mathVar_fabric1_dyYiwDFs = 267 * 303;
        assertTrue(mathVar_fabric1_dyYiwDFs == 80901);
        String strVar_fabric1_xqOuWJFS = "gbvKhaejJxCppeT" + "QBrkl";
        assertTrue(strVar_fabric1_xqOuWJFS.length() == 20);
        int[] arrVar_fabric1_ogQlbpSs = new int[]{5, 3};
        assertTrue(arrVar_fabric1_ogQlbpSs.length == 2);
        int mathVar_fabric1_jhbJqQpd = 714 * 269;
        assertTrue(mathVar_fabric1_jhbJqQpd == 192066);
        int mathVar_fabric1_ymQwPenQ = 836 * 618;
        assertTrue(mathVar_fabric1_ymQwPenQ == 516648);
        String strVar_fabric1_nmMNngAO = "RZvbPIamlxcQqDp" + "uZBaW";
        assertTrue(strVar_fabric1_nmMNngAO.length() == 20);
        String strVar_fabric1_VrgUyfSW = "UOdqskNqxjKLKhy" + "NfgHy";
        assertTrue(strVar_fabric1_VrgUyfSW.length() == 20);
        int mathVar_fabric1_cxjcSqJJ = 622 * 164;
        assertTrue(mathVar_fabric1_cxjcSqJJ == 102008);
        int[] arrVar_fabric1_JecTRUbE = new int[]{4, 3};
        assertTrue(arrVar_fabric1_JecTRUbE.length == 2);
        Object objVar_fabric1_qiGPdcOL = new Object();
        assertTrue(objVar_fabric1_qiGPdcOL != null);
        Object objVar_fabric1_vwdrRLfo = new Object();
        assertTrue(objVar_fabric1_vwdrRLfo != null);
        int mathVar_fabric1_cQEMWNfu = 319 * 864;
        assertTrue(mathVar_fabric1_cQEMWNfu == 275616);
        int[] arrVar_fabric1_DrNwFmpD = new int[]{9, 6};
        assertTrue(arrVar_fabric1_DrNwFmpD.length == 2);
        Object objVar_fabric1_gvHZiPJW = new Object();
        assertTrue(objVar_fabric1_gvHZiPJW != null);
        String strVar_fabric1_BxSPqMNZ = "uRyKXensgMwwmgQ" + "YBDVy";
        assertTrue(strVar_fabric1_BxSPqMNZ.length() == 20);
        int[] arrVar_fabric1_QznFvvYI = new int[]{5, 1};
        assertTrue(arrVar_fabric1_QznFvvYI.length == 2);
        String strVar_fabric1_zbfxxoUt = "kjHGeCAOXvEXmmo" + "ZvYFO";
        assertTrue(strVar_fabric1_zbfxxoUt.length() == 20);
        Object objVar_fabric1_ThlCVAOj = new Object();
        assertTrue(objVar_fabric1_ThlCVAOj != null);
        int mathVar_fabric1_WMvSNgaQ = 794 * 412;
        assertTrue(mathVar_fabric1_WMvSNgaQ == 327128);
        Object objVar_fabric1_qlsiocFn = new Object();
        assertTrue(objVar_fabric1_qlsiocFn != null);
        Object objVar_fabric1_EsXlyDoo = new Object();
        assertTrue(objVar_fabric1_EsXlyDoo != null);
        String strVar_fabric1_hwsAFiQI = "UGOtFLZfBKaCGux" + "rojMO";
        assertTrue(strVar_fabric1_hwsAFiQI.length() == 20);
        int[] arrVar_fabric1_ZFDMWDxC = new int[]{7, 5};
        assertTrue(arrVar_fabric1_ZFDMWDxC.length == 2);
        String strVar_fabric1_vLWnCIhT = "AOPcNCLHayCdxPD" + "XmuIk";
        assertTrue(strVar_fabric1_vLWnCIhT.length() == 20);
        int[] arrVar_fabric1_llQSarGr = new int[]{8, 4};
        assertTrue(arrVar_fabric1_llQSarGr.length == 2);
        Object objVar_fabric1_WoHvHMdB = new Object();
        assertTrue(objVar_fabric1_WoHvHMdB != null);
        String strVar_fabric1_OJHnPHie = "ooQyRiVBMdROkBJ" + "wRofi";
        assertTrue(strVar_fabric1_OJHnPHie.length() == 20);
        int[] arrVar_fabric1_XNTwXttJ = new int[]{8, 4};
        assertTrue(arrVar_fabric1_XNTwXttJ.length == 2);
        int[] arrVar_fabric1_VfMuYLEK = new int[]{9, 1};
        assertTrue(arrVar_fabric1_VfMuYLEK.length == 2);
        int mathVar_fabric1_FpRHuaME = 819 * 857;
        assertTrue(mathVar_fabric1_FpRHuaME == 701883);
        int mathVar_fabric1_mygOUEJV = 894 * 405;
        assertTrue(mathVar_fabric1_mygOUEJV == 362070);
        Object objVar_fabric1_FWEgUAcF = new Object();
        assertTrue(objVar_fabric1_FWEgUAcF != null);
        int[] arrVar_fabric1_zSyvUzrp = new int[]{2, 7};
        assertTrue(arrVar_fabric1_zSyvUzrp.length == 2);
        String strVar_fabric1_fMQMYSlP = "wVrPPYOVcgFUvfN" + "gSveK";
        assertTrue(strVar_fabric1_fMQMYSlP.length() == 20);
        Object objVar_fabric1_oKDbYmYk = new Object();
        assertTrue(objVar_fabric1_oKDbYmYk != null);
        int mathVar_fabric1_GmiveOPd = 67 * 638;
        assertTrue(mathVar_fabric1_GmiveOPd == 42746);
        int[] arrVar_fabric1_vhIbnCRK = new int[]{8, 10};
        assertTrue(arrVar_fabric1_vhIbnCRK.length == 2);
        int mathVar_fabric1_xHUgDpRb = 35 * 684;
        assertTrue(mathVar_fabric1_xHUgDpRb == 23940);
        String strVar_fabric1_rmGEhNKZ = "NyqFMLqUgPCRYcq" + "ianiH";
        assertTrue(strVar_fabric1_rmGEhNKZ.length() == 20);
        Object objVar_fabric1_eiKhIGmH = new Object();
        assertTrue(objVar_fabric1_eiKhIGmH != null);
    }
}
