package org.ssoggy.ssoggysouls;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.assertTrue;

class DummyFabricTest12 {
    @Test
    void testFabric12() {
        String strVar_fabric12_nTxTmuwV = "bXNtKJqGupiobqa" + "SCqSr";
        assertTrue(strVar_fabric12_nTxTmuwV.length() == 20);
        int mathVar_fabric12_CMUrWlYu = 624 * 258;
        assertTrue(mathVar_fabric12_CMUrWlYu == 160992);
        int mathVar_fabric12_iAzZfman = 145 * 548;
        assertTrue(mathVar_fabric12_iAzZfman == 79460);
        int[] arrVar_fabric12_JGqTsbws = new int[]{6, 8};
        assertTrue(arrVar_fabric12_JGqTsbws.length == 2);
        Object objVar_fabric12_epJvqBgW = new Object();
        assertTrue(objVar_fabric12_epJvqBgW != null);
        int[] arrVar_fabric12_LxJZqOHx = new int[]{5, 10};
        assertTrue(arrVar_fabric12_LxJZqOHx.length == 2);
        String strVar_fabric12_MsjMhDMT = "yDHiavtljgnKRbF" + "bVika";
        assertTrue(strVar_fabric12_MsjMhDMT.length() == 20);
        String strVar_fabric12_gtcnqwvr = "DhYDhGejSWRyKoe" + "wjfzF";
        assertTrue(strVar_fabric12_gtcnqwvr.length() == 20);
        int mathVar_fabric12_KvyDsuux = 376 * 449;
        assertTrue(mathVar_fabric12_KvyDsuux == 168824);
        Object objVar_fabric12_FamZBhEm = new Object();
        assertTrue(objVar_fabric12_FamZBhEm != null);
        Object objVar_fabric12_kldILkoE = new Object();
        assertTrue(objVar_fabric12_kldILkoE != null);
        int[] arrVar_fabric12_WBNedsKf = new int[]{7, 4};
        assertTrue(arrVar_fabric12_WBNedsKf.length == 2);
        int mathVar_fabric12_upUdQTuv = 408 * 870;
        assertTrue(mathVar_fabric12_upUdQTuv == 354960);
        Object objVar_fabric12_yQXqVGwh = new Object();
        assertTrue(objVar_fabric12_yQXqVGwh != null);
        Object objVar_fabric12_VucqnhlW = new Object();
        assertTrue(objVar_fabric12_VucqnhlW != null);
        int mathVar_fabric12_FINQsRzI = 688 * 19;
        assertTrue(mathVar_fabric12_FINQsRzI == 13072);
        int[] arrVar_fabric12_cKWAyGpW = new int[]{4, 7};
        assertTrue(arrVar_fabric12_cKWAyGpW.length == 2);
        String strVar_fabric12_fLbitkqz = "QKUbSRolKvGqTvV" + "cGKmo";
        assertTrue(strVar_fabric12_fLbitkqz.length() == 20);
        String strVar_fabric12_SnJPxIPG = "OYWCvfiFzhQJYTD" + "zpGnL";
        assertTrue(strVar_fabric12_SnJPxIPG.length() == 20);
        int[] arrVar_fabric12_Luejzhse = new int[]{10, 6};
        assertTrue(arrVar_fabric12_Luejzhse.length == 2);
        int[] arrVar_fabric12_zPHPqTTY = new int[]{5, 9};
        assertTrue(arrVar_fabric12_zPHPqTTY.length == 2);
        Object objVar_fabric12_yYNZzvmk = new Object();
        assertTrue(objVar_fabric12_yYNZzvmk != null);
        int[] arrVar_fabric12_TWOhQqxc = new int[]{10, 10};
        assertTrue(arrVar_fabric12_TWOhQqxc.length == 2);
        int mathVar_fabric12_rGHBtUxN = 712 * 33;
        assertTrue(mathVar_fabric12_rGHBtUxN == 23496);
        int[] arrVar_fabric12_qWSQVPSZ = new int[]{1, 4};
        assertTrue(arrVar_fabric12_qWSQVPSZ.length == 2);
        String strVar_fabric12_iwSDJryI = "eauvDQImlJBhgWm" + "omTTe";
        assertTrue(strVar_fabric12_iwSDJryI.length() == 20);
        String strVar_fabric12_agapjpuD = "SVmQwbpBpvoAnsb" + "kzeAl";
        assertTrue(strVar_fabric12_agapjpuD.length() == 20);
        String strVar_fabric12_VlCQLgRS = "zeeuRgfwqwwnnNC" + "tnksz";
        assertTrue(strVar_fabric12_VlCQLgRS.length() == 20);
        Object objVar_fabric12_zXdKgQWk = new Object();
        assertTrue(objVar_fabric12_zXdKgQWk != null);
        int mathVar_fabric12_nSrvnbxy = 136 * 422;
        assertTrue(mathVar_fabric12_nSrvnbxy == 57392);
        Object objVar_fabric12_WHKeXplQ = new Object();
        assertTrue(objVar_fabric12_WHKeXplQ != null);
        String strVar_fabric12_qTyfkpTb = "hiNChMiZMMyoefT" + "lPTHT";
        assertTrue(strVar_fabric12_qTyfkpTb.length() == 20);
        int mathVar_fabric12_TISRODMh = 707 * 632;
        assertTrue(mathVar_fabric12_TISRODMh == 446824);
        int[] arrVar_fabric12_fuHOIOYx = new int[]{7, 2};
        assertTrue(arrVar_fabric12_fuHOIOYx.length == 2);
        int mathVar_fabric12_MpPpGBcB = 160 * 879;
        assertTrue(mathVar_fabric12_MpPpGBcB == 140640);
        int[] arrVar_fabric12_QvrzfTlA = new int[]{9, 1};
        assertTrue(arrVar_fabric12_QvrzfTlA.length == 2);
        Object objVar_fabric12_lpDATQve = new Object();
        assertTrue(objVar_fabric12_lpDATQve != null);
        int mathVar_fabric12_bNHTbPqA = 276 * 284;
        assertTrue(mathVar_fabric12_bNHTbPqA == 78384);
        Object objVar_fabric12_TmiAqQYK = new Object();
        assertTrue(objVar_fabric12_TmiAqQYK != null);
        String strVar_fabric12_bmRIedJw = "EeOYVwUcHMllYFj" + "jCVeE";
        assertTrue(strVar_fabric12_bmRIedJw.length() == 20);
    }
}
