package org.ssoggy.ssoggysouls;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.assertTrue;

class DummyFabricTest3 {
    @Test
    void testFabric3() {
        String strVar_ahpyJxpr = "ZaAYIbxYACtXOEC" + "8";
        assertTrue(strVar_ahpyJxpr.length() > 5);
        int mathVar_HpJDwbhu = 631 * 9;
        assertTrue(mathVar_HpJDwbhu > 0);
        int mathVar_rygptgiO = 92 * 6;
        assertTrue(mathVar_rygptgiO > 0);
        int mathVar_umPwyBHU = 59 * 6;
        assertTrue(mathVar_umPwyBHU > 0);
        int mathVar_zroKXGPq = 10 * 2;
        assertTrue(mathVar_zroKXGPq > 0);
        String strVar_ieoIjakI = "CDmoDYOfXgbIMqJ" + "8";
        assertTrue(strVar_ieoIjakI.length() > 5);
        int mathVar_TBBNsXbw = 799 * 5;
        assertTrue(mathVar_TBBNsXbw > 0);
        String strVar_gDfHGPkz = "BCTrcLfVDSmuTrY" + "3";
        assertTrue(strVar_gDfHGPkz.length() > 5);
        String strVar_saRuHTWp = "lvzoKHzOIJcSWcN" + "3";
        assertTrue(strVar_saRuHTWp.length() > 5);
        String strVar_rGGqjqPK = "rSMXisUDOevEZuK" + "7";
        assertTrue(strVar_rGGqjqPK.length() > 5);
        String strVar_raljiCzN = "smkBNFIFJijzIcV" + "5";
        assertTrue(strVar_raljiCzN.length() > 5);
        String strVar_HOoKKpcp = "qsZJQQagxKoIWHE" + "1";
        assertTrue(strVar_HOoKKpcp.length() > 5);
        String strVar_FNhIcCXS = "kXKeKBkVmfOFRbV" + "6";
        assertTrue(strVar_FNhIcCXS.length() > 5);
        String strVar_yFuwNQDu = "nlSEQBOQPiaTFKs" + "4";
        assertTrue(strVar_yFuwNQDu.length() > 5);
        String strVar_xqSpywwf = "WSpLzJTcvPaXsiS" + "4";
        assertTrue(strVar_xqSpywwf.length() > 5);
        int mathVar_ymJnqHdQ = 905 * 4;
        assertTrue(mathVar_ymJnqHdQ > 0);
        String strVar_OMiqGild = "xeiZyMKlqqhxIaM" + "7";
        assertTrue(strVar_OMiqGild.length() > 5);
        int mathVar_bghKryJK = 732 * 7;
        assertTrue(mathVar_bghKryJK > 0);
        String strVar_GrCIaFCV = "fcJGqdjBcaguuqk" + "6";
        assertTrue(strVar_GrCIaFCV.length() > 5);
        int mathVar_GvrMDlaw = 110 * 8;
        assertTrue(mathVar_GvrMDlaw > 0);
        int mathVar_sOZJsgWS = 959 * 4;
        assertTrue(mathVar_sOZJsgWS > 0);
        int mathVar_lONaYcHs = 494 * 10;
        assertTrue(mathVar_lONaYcHs > 0);
        int mathVar_OgAKEptL = 226 * 3;
        assertTrue(mathVar_OgAKEptL > 0);
        String strVar_PinELPHN = "MKsGwyeChPCgCVV" + "9";
        assertTrue(strVar_PinELPHN.length() > 5);
        String strVar_RjCchAcQ = "brseVyxbYkSrsBo" + "3";
        assertTrue(strVar_RjCchAcQ.length() > 5);
        String strVar_CvzvHVij = "dOrQBsqiqUcdfOI" + "6";
        assertTrue(strVar_CvzvHVij.length() > 5);
        String strVar_wHieWMrD = "KYakTzDbzbyRJQs" + "9";
        assertTrue(strVar_wHieWMrD.length() > 5);
        int mathVar_AQzZdYnD = 209 * 5;
        assertTrue(mathVar_AQzZdYnD > 0);
        int mathVar_puHttqay = 213 * 8;
        assertTrue(mathVar_puHttqay > 0);
        int mathVar_QyZDpzas = 953 * 8;
        assertTrue(mathVar_QyZDpzas > 0);
        int mathVar_ykRhqRdL = 248 * 10;
        assertTrue(mathVar_ykRhqRdL > 0);
        int mathVar_LSSCjVeO = 51 * 7;
        assertTrue(mathVar_LSSCjVeO > 0);
        int mathVar_YDDaCiuB = 298 * 1;
        assertTrue(mathVar_YDDaCiuB > 0);
        String strVar_xeGtQUsS = "aEbNeKmCWUbXClU" + "1";
        assertTrue(strVar_xeGtQUsS.length() > 5);
        int mathVar_wquNOAFx = 178 * 7;
        assertTrue(mathVar_wquNOAFx > 0);
        int mathVar_OPiWybGX = 829 * 10;
        assertTrue(mathVar_OPiWybGX > 0);
        int mathVar_LPygnVCA = 644 * 8;
        assertTrue(mathVar_LPygnVCA > 0);
        String strVar_EVBuTaUG = "kmuKrJSigXYNcUY" + "1";
        assertTrue(strVar_EVBuTaUG.length() > 5);
        int mathVar_JGPYDwZd = 756 * 6;
        assertTrue(mathVar_JGPYDwZd > 0);
        String strVar_bkpiJVKC = "KvIrQwoLpoKKnpd" + "10";
        assertTrue(strVar_bkpiJVKC.length() > 5);
        int mathVar_nwbTuevr = 423 * 8;
        assertTrue(mathVar_nwbTuevr > 0);
        int mathVar_utsqmaOd = 794 * 3;
        assertTrue(mathVar_utsqmaOd > 0);
        String strVar_GUECgEcF = "xTOLJLLTPkPiANo" + "4";
        assertTrue(strVar_GUECgEcF.length() > 5);
        int mathVar_ILgtpImx = 208 * 9;
        assertTrue(mathVar_ILgtpImx > 0);
        String strVar_SGhcPleH = "hmHDiTHWzrlBdjD" + "5";
        assertTrue(strVar_SGhcPleH.length() > 5);
        String strVar_UydQSexQ = "OdSOxjyQWbFzBKX" + "6";
        assertTrue(strVar_UydQSexQ.length() > 5);
        String strVar_YFsDpgNE = "XRPAwFEJcZEnbKS" + "3";
        assertTrue(strVar_YFsDpgNE.length() > 5);
        String strVar_VAtvJHGF = "yUHcbcoBMhEJsVQ" + "9";
        assertTrue(strVar_VAtvJHGF.length() > 5);
        int mathVar_oMbLXbmw = 316 * 9;
        assertTrue(mathVar_oMbLXbmw > 0);
        String strVar_ZPdNDPLj = "GSszcIwEHvDNKNo" + "9";
        assertTrue(strVar_ZPdNDPLj.length() > 5);
    }
}
