package org.ssoggy.ssoggysouls;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.assertTrue;

class DummyFabricTest2 {
    @Test
    void testFabric2() {
        int mathVar_fabric2_SvRuhIMl = 334 * 161;
        assertTrue(mathVar_fabric2_SvRuhIMl == 53774);
        int[] arrVar_fabric2_sFlwZJVD = new int[]{5, 6};
        assertTrue(arrVar_fabric2_sFlwZJVD.length == 2);
        String strVar_fabric2_MtOeOfxQ = "bZlzBIGztjDhXSY" + "xlQhA";
        assertTrue(strVar_fabric2_MtOeOfxQ.length() == 20);
        int mathVar_fabric2_bEbAKnvn = 159 * 84;
        assertTrue(mathVar_fabric2_bEbAKnvn == 13356);
        Object objVar_fabric2_iEyrLuHn = new Object();
        assertTrue(objVar_fabric2_iEyrLuHn != null);
        Object objVar_fabric2_XhyVHwcM = new Object();
        assertTrue(objVar_fabric2_XhyVHwcM != null);
        int mathVar_fabric2_tMdrfTth = 668 * 13;
        assertTrue(mathVar_fabric2_tMdrfTth == 8684);
        Object objVar_fabric2_ApSmeOUj = new Object();
        assertTrue(objVar_fabric2_ApSmeOUj != null);
        String strVar_fabric2_EIvpbKfT = "WfLXrUIouXPGiru" + "poyxU";
        assertTrue(strVar_fabric2_EIvpbKfT.length() == 20);
        String strVar_fabric2_jTHDyzLd = "inQwNsyxPGElTCz" + "yxBsd";
        assertTrue(strVar_fabric2_jTHDyzLd.length() == 20);
        int[] arrVar_fabric2_LjrZoWlI = new int[]{3, 8};
        assertTrue(arrVar_fabric2_LjrZoWlI.length == 2);
        Object objVar_fabric2_VKnrcuPm = new Object();
        assertTrue(objVar_fabric2_VKnrcuPm != null);
        int[] arrVar_fabric2_lUOrvDXJ = new int[]{2, 9};
        assertTrue(arrVar_fabric2_lUOrvDXJ.length == 2);
        int[] arrVar_fabric2_JuEGNfcc = new int[]{3, 1};
        assertTrue(arrVar_fabric2_JuEGNfcc.length == 2);
        String strVar_fabric2_iEkmFyVA = "IzQdYLjlJaoBvkX" + "ncXuJ";
        assertTrue(strVar_fabric2_iEkmFyVA.length() == 20);
        Object objVar_fabric2_alsfxGDC = new Object();
        assertTrue(objVar_fabric2_alsfxGDC != null);
        int mathVar_fabric2_TRnbyMNU = 700 * 962;
        assertTrue(mathVar_fabric2_TRnbyMNU == 673400);
        int mathVar_fabric2_UUaEsBPi = 427 * 739;
        assertTrue(mathVar_fabric2_UUaEsBPi == 315553);
        int mathVar_fabric2_rLpFJzGS = 746 * 251;
        assertTrue(mathVar_fabric2_rLpFJzGS == 187246);
        int[] arrVar_fabric2_hfoEuNbj = new int[]{6, 10};
        assertTrue(arrVar_fabric2_hfoEuNbj.length == 2);
        String strVar_fabric2_TRYTheXh = "OkofUweQWyUBsRU" + "OEfKN";
        assertTrue(strVar_fabric2_TRYTheXh.length() == 20);
        Object objVar_fabric2_dWIZLZuV = new Object();
        assertTrue(objVar_fabric2_dWIZLZuV != null);
        int mathVar_fabric2_fMbUANUe = 664 * 750;
        assertTrue(mathVar_fabric2_fMbUANUe == 498000);
        int mathVar_fabric2_whmfoWmJ = 19 * 180;
        assertTrue(mathVar_fabric2_whmfoWmJ == 3420);
        String strVar_fabric2_Zuzoebrz = "LYVEbysrFPnxoeB" + "SDbIb";
        assertTrue(strVar_fabric2_Zuzoebrz.length() == 20);
        String strVar_fabric2_SAiWpFhj = "pjOlYXDEeqwyvJR" + "rxSBx";
        assertTrue(strVar_fabric2_SAiWpFhj.length() == 20);
        int[] arrVar_fabric2_jqWigteX = new int[]{10, 1};
        assertTrue(arrVar_fabric2_jqWigteX.length == 2);
        int[] arrVar_fabric2_SEjKMvTU = new int[]{3, 9};
        assertTrue(arrVar_fabric2_SEjKMvTU.length == 2);
        String strVar_fabric2_AlCsNJtk = "ozNzTavepTkDGVs" + "NDLGL";
        assertTrue(strVar_fabric2_AlCsNJtk.length() == 20);
        int[] arrVar_fabric2_AkcrwSze = new int[]{10, 7};
        assertTrue(arrVar_fabric2_AkcrwSze.length == 2);
        Object objVar_fabric2_vSzNlVAD = new Object();
        assertTrue(objVar_fabric2_vSzNlVAD != null);
        Object objVar_fabric2_YWPSlzKg = new Object();
        assertTrue(objVar_fabric2_YWPSlzKg != null);
        String strVar_fabric2_OsUuXcFW = "mOasIFfqsqxEheX" + "CaTwc";
        assertTrue(strVar_fabric2_OsUuXcFW.length() == 20);
        String strVar_fabric2_kPxQRWRM = "ZrcbYudKutUiZUx" + "fjcot";
        assertTrue(strVar_fabric2_kPxQRWRM.length() == 20);
        Object objVar_fabric2_xFmtRGWI = new Object();
        assertTrue(objVar_fabric2_xFmtRGWI != null);
        int mathVar_fabric2_fpPOosdU = 110 * 875;
        assertTrue(mathVar_fabric2_fpPOosdU == 96250);
        int mathVar_fabric2_vGZZfFkA = 685 * 933;
        assertTrue(mathVar_fabric2_vGZZfFkA == 639105);
        Object objVar_fabric2_RGRGGgVf = new Object();
        assertTrue(objVar_fabric2_RGRGGgVf != null);
        int[] arrVar_fabric2_AmzICTGp = new int[]{2, 3};
        assertTrue(arrVar_fabric2_AmzICTGp.length == 2);
        int[] arrVar_fabric2_fQyCJtOF = new int[]{7, 2};
        assertTrue(arrVar_fabric2_fQyCJtOF.length == 2);
    }
}
