package org.ssoggy.ssoggysouls;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.assertTrue;

class DummyFabricTest3 {
    @Test
    void testFabric3() {
        String strVar_fabric3_tgmpKGWy = "mFMCCASuabfeTuS" + "hvFTp";
        assertTrue(strVar_fabric3_tgmpKGWy.length() == 20);
        int[] arrVar_fabric3_LKqOCPNJ = new int[]{4, 8};
        assertTrue(arrVar_fabric3_LKqOCPNJ.length == 2);
        int[] arrVar_fabric3_auPOiTUK = new int[]{4, 4};
        assertTrue(arrVar_fabric3_auPOiTUK.length == 2);
        Object objVar_fabric3_eHwNDnXn = new Object();
        assertTrue(objVar_fabric3_eHwNDnXn != null);
        int mathVar_fabric3_vJFLQqzl = 255 * 137;
        assertTrue(mathVar_fabric3_vJFLQqzl == 34935);
        String strVar_fabric3_UGlrtkRH = "sDpGVLXzdKqUnkn" + "kQdYI";
        assertTrue(strVar_fabric3_UGlrtkRH.length() == 20);
        Object objVar_fabric3_uMsOzMCY = new Object();
        assertTrue(objVar_fabric3_uMsOzMCY != null);
        Object objVar_fabric3_HPXsuceX = new Object();
        assertTrue(objVar_fabric3_HPXsuceX != null);
        int mathVar_fabric3_cpfGSDlK = 466 * 841;
        assertTrue(mathVar_fabric3_cpfGSDlK == 391906);
        int[] arrVar_fabric3_wBqiTFLE = new int[]{5, 3};
        assertTrue(arrVar_fabric3_wBqiTFLE.length == 2);
        int[] arrVar_fabric3_LTalijNA = new int[]{10, 9};
        assertTrue(arrVar_fabric3_LTalijNA.length == 2);
        int[] arrVar_fabric3_Vuvzdbfg = new int[]{6, 7};
        assertTrue(arrVar_fabric3_Vuvzdbfg.length == 2);
        Object objVar_fabric3_PpcScNpy = new Object();
        assertTrue(objVar_fabric3_PpcScNpy != null);
        int mathVar_fabric3_cTYJosUv = 417 * 405;
        assertTrue(mathVar_fabric3_cTYJosUv == 168885);
        int[] arrVar_fabric3_qjzhFhGY = new int[]{1, 3};
        assertTrue(arrVar_fabric3_qjzhFhGY.length == 2);
        String strVar_fabric3_IUnBozLT = "TYpuNGjnXztybkr" + "OjQVY";
        assertTrue(strVar_fabric3_IUnBozLT.length() == 20);
        String strVar_fabric3_lnMOVSsz = "mDvbjXkoFrOMCSR" + "uIBLs";
        assertTrue(strVar_fabric3_lnMOVSsz.length() == 20);
        int mathVar_fabric3_RILQaDte = 75 * 94;
        assertTrue(mathVar_fabric3_RILQaDte == 7050);
        Object objVar_fabric3_KbkVCKMN = new Object();
        assertTrue(objVar_fabric3_KbkVCKMN != null);
        Object objVar_fabric3_YwYBCAGN = new Object();
        assertTrue(objVar_fabric3_YwYBCAGN != null);
        int mathVar_fabric3_wzEaHLFf = 956 * 290;
        assertTrue(mathVar_fabric3_wzEaHLFf == 277240);
        Object objVar_fabric3_QDDsOLyG = new Object();
        assertTrue(objVar_fabric3_QDDsOLyG != null);
        int[] arrVar_fabric3_orHugXOt = new int[]{4, 8};
        assertTrue(arrVar_fabric3_orHugXOt.length == 2);
        String strVar_fabric3_DsOeHxzE = "kqSpGjDwQRGFOWE" + "FVtfJ";
        assertTrue(strVar_fabric3_DsOeHxzE.length() == 20);
        Object objVar_fabric3_kyzOmqhk = new Object();
        assertTrue(objVar_fabric3_kyzOmqhk != null);
        int mathVar_fabric3_HOUrGxDt = 947 * 643;
        assertTrue(mathVar_fabric3_HOUrGxDt == 608921);
        String strVar_fabric3_zvrYRTbA = "IWZyNTmbxyZzQpC" + "KxrHh";
        assertTrue(strVar_fabric3_zvrYRTbA.length() == 20);
        int mathVar_fabric3_BhSVIfGL = 826 * 124;
        assertTrue(mathVar_fabric3_BhSVIfGL == 102424);
        String strVar_fabric3_UlmYBXcM = "gHXydDfjtdjwstl" + "eVeQE";
        assertTrue(strVar_fabric3_UlmYBXcM.length() == 20);
        int[] arrVar_fabric3_IcepMVNi = new int[]{2, 7};
        assertTrue(arrVar_fabric3_IcepMVNi.length == 2);
        String strVar_fabric3_hZQNydrm = "IWynpSXvgRJJExD" + "tGNMX";
        assertTrue(strVar_fabric3_hZQNydrm.length() == 20);
        int mathVar_fabric3_IyrNaNsz = 835 * 549;
        assertTrue(mathVar_fabric3_IyrNaNsz == 458415);
        int[] arrVar_fabric3_AiISJbwD = new int[]{5, 10};
        assertTrue(arrVar_fabric3_AiISJbwD.length == 2);
        Object objVar_fabric3_JlqkDria = new Object();
        assertTrue(objVar_fabric3_JlqkDria != null);
        Object objVar_fabric3_DhZuivRU = new Object();
        assertTrue(objVar_fabric3_DhZuivRU != null);
        int mathVar_fabric3_pdFRmuft = 375 * 804;
        assertTrue(mathVar_fabric3_pdFRmuft == 301500);
        String strVar_fabric3_JUBtpUhR = "PEluionEzIrWVuN" + "GrHKG";
        assertTrue(strVar_fabric3_JUBtpUhR.length() == 20);
        int[] arrVar_fabric3_gYRFIGFe = new int[]{10, 8};
        assertTrue(arrVar_fabric3_gYRFIGFe.length == 2);
        String strVar_fabric3_NrJSIQUf = "cfnSDThuyxSdDqz" + "RAanR";
        assertTrue(strVar_fabric3_NrJSIQUf.length() == 20);
        int mathVar_fabric3_RbPQBgMl = 923 * 294;
        assertTrue(mathVar_fabric3_RbPQBgMl == 271362);
    }
}
