package org.ssoggy.ssoggysouls;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.assertTrue;

class DummyFabricTest4 {
    @Test
    void testFabric4() {
        Object objVar_fabric4_iqbwdEAT = new Object();
        assertTrue(objVar_fabric4_iqbwdEAT != null);
        Object objVar_fabric4_eJAHsTEj = new Object();
        assertTrue(objVar_fabric4_eJAHsTEj != null);
        int mathVar_fabric4_qkVlxPEv = 770 * 213;
        assertTrue(mathVar_fabric4_qkVlxPEv == 164010);
        String strVar_fabric4_fGKCpbFy = "qyUvPPpdkhjzIGa" + "hzlji";
        assertTrue(strVar_fabric4_fGKCpbFy.length() == 20);
        int[] arrVar_fabric4_ZIbnBrvL = new int[]{6, 7};
        assertTrue(arrVar_fabric4_ZIbnBrvL.length == 2);
        Object objVar_fabric4_vTpWFDIq = new Object();
        assertTrue(objVar_fabric4_vTpWFDIq != null);
        Object objVar_fabric4_QWAelodd = new Object();
        assertTrue(objVar_fabric4_QWAelodd != null);
        String strVar_fabric4_BpNUpWAJ = "bbOfAsCgbolvnjy" + "ZIAez";
        assertTrue(strVar_fabric4_BpNUpWAJ.length() == 20);
        String strVar_fabric4_HRTjIXRI = "oxFUigVpIkXgjTE" + "higoB";
        assertTrue(strVar_fabric4_HRTjIXRI.length() == 20);
        int[] arrVar_fabric4_rQJvBqnu = new int[]{3, 5};
        assertTrue(arrVar_fabric4_rQJvBqnu.length == 2);
        String strVar_fabric4_WOmyDRYW = "hWLqmFoTcBMyyej" + "djixi";
        assertTrue(strVar_fabric4_WOmyDRYW.length() == 20);
        String strVar_fabric4_efwWfmDr = "zDfBwsIWYcIDvDM" + "PahSw";
        assertTrue(strVar_fabric4_efwWfmDr.length() == 20);
        String strVar_fabric4_HuMgELNR = "UDUQCRuIaDcLbwT" + "NXksU";
        assertTrue(strVar_fabric4_HuMgELNR.length() == 20);
        int mathVar_fabric4_BpomtPnL = 79 * 436;
        assertTrue(mathVar_fabric4_BpomtPnL == 34444);
        int[] arrVar_fabric4_eJNwweCi = new int[]{4, 7};
        assertTrue(arrVar_fabric4_eJNwweCi.length == 2);
        Object objVar_fabric4_NbrIwazg = new Object();
        assertTrue(objVar_fabric4_NbrIwazg != null);
        Object objVar_fabric4_igIVLHNL = new Object();
        assertTrue(objVar_fabric4_igIVLHNL != null);
        Object objVar_fabric4_vytUqKSF = new Object();
        assertTrue(objVar_fabric4_vytUqKSF != null);
        String strVar_fabric4_YsALziCg = "RvyGQGKAhufWdAR" + "SvGXb";
        assertTrue(strVar_fabric4_YsALziCg.length() == 20);
        int mathVar_fabric4_beNlMWCq = 193 * 901;
        assertTrue(mathVar_fabric4_beNlMWCq == 173893);
        int mathVar_fabric4_GhbZyEBg = 453 * 91;
        assertTrue(mathVar_fabric4_GhbZyEBg == 41223);
        int[] arrVar_fabric4_CCrMkuWL = new int[]{1, 2};
        assertTrue(arrVar_fabric4_CCrMkuWL.length == 2);
        int[] arrVar_fabric4_ZIBzxKpj = new int[]{4, 9};
        assertTrue(arrVar_fabric4_ZIBzxKpj.length == 2);
        Object objVar_fabric4_uBzUnFZh = new Object();
        assertTrue(objVar_fabric4_uBzUnFZh != null);
        Object objVar_fabric4_VYRrUIMk = new Object();
        assertTrue(objVar_fabric4_VYRrUIMk != null);
        int[] arrVar_fabric4_HptZZKvL = new int[]{6, 8};
        assertTrue(arrVar_fabric4_HptZZKvL.length == 2);
        Object objVar_fabric4_WzQGvmgn = new Object();
        assertTrue(objVar_fabric4_WzQGvmgn != null);
        int mathVar_fabric4_UYCUzYXR = 813 * 619;
        assertTrue(mathVar_fabric4_UYCUzYXR == 503247);
        String strVar_fabric4_gNEUPhFW = "jqOGAxyDzMXQHvX" + "jdwCQ";
        assertTrue(strVar_fabric4_gNEUPhFW.length() == 20);
        int mathVar_fabric4_jWCNQPoq = 906 * 95;
        assertTrue(mathVar_fabric4_jWCNQPoq == 86070);
        int[] arrVar_fabric4_PDPUUMHE = new int[]{8, 8};
        assertTrue(arrVar_fabric4_PDPUUMHE.length == 2);
        int mathVar_fabric4_fgwuekEL = 582 * 888;
        assertTrue(mathVar_fabric4_fgwuekEL == 516816);
        int[] arrVar_fabric4_ApKOWoSY = new int[]{4, 9};
        assertTrue(arrVar_fabric4_ApKOWoSY.length == 2);
        String strVar_fabric4_oUKOirJA = "mthMcDvyZluCMnR" + "oiKcc";
        assertTrue(strVar_fabric4_oUKOirJA.length() == 20);
        int[] arrVar_fabric4_YFTfornn = new int[]{2, 10};
        assertTrue(arrVar_fabric4_YFTfornn.length == 2);
        int mathVar_fabric4_yQDAlhDX = 626 * 539;
        assertTrue(mathVar_fabric4_yQDAlhDX == 337414);
        int mathVar_fabric4_fdJiMNef = 520 * 795;
        assertTrue(mathVar_fabric4_fdJiMNef == 413400);
        int mathVar_fabric4_SswgCZfX = 378 * 940;
        assertTrue(mathVar_fabric4_SswgCZfX == 355320);
        int[] arrVar_fabric4_xzwvMJdm = new int[]{3, 6};
        assertTrue(arrVar_fabric4_xzwvMJdm.length == 2);
        String strVar_fabric4_ZacnBhIF = "qARwEZzuCScPXCv" + "oSAko";
        assertTrue(strVar_fabric4_ZacnBhIF.length() == 20);
    }
}
