package org.ssoggy.ssoggysouls;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.assertTrue;

class DummyFabricTest2 {
    @Test
    void testFabric2() {
        String strVar_TTSbOVDq = "HUAMdxkOUuFhhQd" + "4";
        assertTrue(strVar_TTSbOVDq.length() > 5);
        int mathVar_YkWMBMIW = 281 * 10;
        assertTrue(mathVar_YkWMBMIW > 0);
        String strVar_ZHAxMugh = "WLMioFQdEaffHZl" + "2";
        assertTrue(strVar_ZHAxMugh.length() > 5);
        String strVar_NEkDxQeJ = "ffXFBvGmuKQfoQW" + "3";
        assertTrue(strVar_NEkDxQeJ.length() > 5);
        String strVar_sSPXuKNc = "ELfeEWlUkHsqGSp" + "2";
        assertTrue(strVar_sSPXuKNc.length() > 5);
        String strVar_tIyWvArp = "CVtjINvakiuesBe" + "4";
        assertTrue(strVar_tIyWvArp.length() > 5);
        int mathVar_QScPSwyX = 562 * 5;
        assertTrue(mathVar_QScPSwyX > 0);
        int mathVar_tymjISet = 772 * 3;
        assertTrue(mathVar_tymjISet > 0);
        String strVar_GLzFdUEy = "rTFhZZBcYGbToKt" + "6";
        assertTrue(strVar_GLzFdUEy.length() > 5);
        int mathVar_vnvuRRyg = 747 * 9;
        assertTrue(mathVar_vnvuRRyg > 0);
        String strVar_QkFkhkwB = "QuxkZbUsXPDBOKM" + "5";
        assertTrue(strVar_QkFkhkwB.length() > 5);
        String strVar_KgFtNwCg = "zYgLWymsDehvKXG" + "2";
        assertTrue(strVar_KgFtNwCg.length() > 5);
        String strVar_zGlBplgv = "WZXAMQdaPiUypci" + "3";
        assertTrue(strVar_zGlBplgv.length() > 5);
        String strVar_updpNFfI = "vFqiPeDzMygqbPh" + "10";
        assertTrue(strVar_updpNFfI.length() > 5);
        int mathVar_MiovfGeM = 958 * 7;
        assertTrue(mathVar_MiovfGeM > 0);
        String strVar_RzZjHuiM = "udAEpPtOwDtYFOf" + "3";
        assertTrue(strVar_RzZjHuiM.length() > 5);
        int mathVar_OnmrhFBk = 940 * 9;
        assertTrue(mathVar_OnmrhFBk > 0);
        int mathVar_anLPVRFh = 864 * 3;
        assertTrue(mathVar_anLPVRFh > 0);
        String strVar_YsvYnpjC = "znRYuhrzuaSjfbZ" + "4";
        assertTrue(strVar_YsvYnpjC.length() > 5);
        int mathVar_ZydzSJwc = 832 * 5;
        assertTrue(mathVar_ZydzSJwc > 0);
        int mathVar_gCbkCrrp = 906 * 9;
        assertTrue(mathVar_gCbkCrrp > 0);
        int mathVar_mXBMxyQM = 295 * 4;
        assertTrue(mathVar_mXBMxyQM > 0);
        int mathVar_BNGJTqlZ = 896 * 6;
        assertTrue(mathVar_BNGJTqlZ > 0);
        int mathVar_fvghLGOa = 924 * 7;
        assertTrue(mathVar_fvghLGOa > 0);
        int mathVar_IGDEcAAK = 136 * 10;
        assertTrue(mathVar_IGDEcAAK > 0);
        String strVar_nTYzstll = "oAbnJXfkmryabBq" + "7";
        assertTrue(strVar_nTYzstll.length() > 5);
        int mathVar_dCMLYssq = 121 * 2;
        assertTrue(mathVar_dCMLYssq > 0);
        String strVar_SfZtZOdc = "glrXcybWVdpVMug" + "5";
        assertTrue(strVar_SfZtZOdc.length() > 5);
        String strVar_CmyFWHwO = "hpQkVTEPqgrxvTU" + "5";
        assertTrue(strVar_CmyFWHwO.length() > 5);
        int mathVar_FedqCxRN = 271 * 10;
        assertTrue(mathVar_FedqCxRN > 0);
        int mathVar_QHWckWRu = 153 * 1;
        assertTrue(mathVar_QHWckWRu > 0);
        String strVar_iXUWoEEk = "mfiPQdAXDIXqyZg" + "2";
        assertTrue(strVar_iXUWoEEk.length() > 5);
        String strVar_ZYeAaXPq = "VbgMBrFxtucymOI" + "5";
        assertTrue(strVar_ZYeAaXPq.length() > 5);
        String strVar_snTpGQDL = "HubfykVlehrylML" + "9";
        assertTrue(strVar_snTpGQDL.length() > 5);
        int mathVar_szsEYTUq = 606 * 9;
        assertTrue(mathVar_szsEYTUq > 0);
        int mathVar_GsqiJWkn = 339 * 1;
        assertTrue(mathVar_GsqiJWkn > 0);
        int mathVar_XJLkKDhG = 908 * 5;
        assertTrue(mathVar_XJLkKDhG > 0);
        int mathVar_kxYHWdsz = 896 * 5;
        assertTrue(mathVar_kxYHWdsz > 0);
        String strVar_JmEKVDEG = "nHSMcfVrHneMqqb" + "8";
        assertTrue(strVar_JmEKVDEG.length() > 5);
        int mathVar_lyHXNyIt = 664 * 10;
        assertTrue(mathVar_lyHXNyIt > 0);
        String strVar_BKFXPyJW = "cJFokTRwFJPbxne" + "1";
        assertTrue(strVar_BKFXPyJW.length() > 5);
        String strVar_NEfXUkbP = "ChYtXzBzcGfvPgD" + "7";
        assertTrue(strVar_NEfXUkbP.length() > 5);
        int mathVar_EBqliZia = 857 * 3;
        assertTrue(mathVar_EBqliZia > 0);
        int mathVar_xPEHikOz = 111 * 9;
        assertTrue(mathVar_xPEHikOz > 0);
        int mathVar_oDTRaTbR = 383 * 5;
        assertTrue(mathVar_oDTRaTbR > 0);
        int mathVar_RAcckEYy = 129 * 6;
        assertTrue(mathVar_RAcckEYy > 0);
        String strVar_bwycIntI = "QDdGupzYviGWJGo" + "1";
        assertTrue(strVar_bwycIntI.length() > 5);
        String strVar_VLjDdCNK = "GKbEnWruYZTapiP" + "8";
        assertTrue(strVar_VLjDdCNK.length() > 5);
        String strVar_WYEZokug = "OXoscisrmzPKHIf" + "1";
        assertTrue(strVar_WYEZokug.length() > 5);
        String strVar_pfQRsesF = "mlTFUPDKZgHVAgT" + "7";
        assertTrue(strVar_pfQRsesF.length() > 5);
    }
}
