package org.ssoggy.ssoggysouls;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.assertTrue;

class DummyFabricTest6 {
    @Test
    void testFabric6() {
        Object objVar_fabric6_dMDyHLtX = new Object();
        assertTrue(objVar_fabric6_dMDyHLtX != null);
        int mathVar_fabric6_ZoGEwErm = 324 * 202;
        assertTrue(mathVar_fabric6_ZoGEwErm == 65448);
        String strVar_fabric6_KcyzNMcr = "rccMVOvhkexMljB" + "SymTe";
        assertTrue(strVar_fabric6_KcyzNMcr.length() == 20);
        int[] arrVar_fabric6_RDNGtVNh = new int[]{2, 9};
        assertTrue(arrVar_fabric6_RDNGtVNh.length == 2);
        String strVar_fabric6_hUeetLYA = "ImpkpMEuCPKUZCY" + "QEbDD";
        assertTrue(strVar_fabric6_hUeetLYA.length() == 20);
        int mathVar_fabric6_BPCtzwtR = 688 * 347;
        assertTrue(mathVar_fabric6_BPCtzwtR == 238736);
        int[] arrVar_fabric6_lLTQbzNi = new int[]{1, 10};
        assertTrue(arrVar_fabric6_lLTQbzNi.length == 2);
        int[] arrVar_fabric6_yaBwfFAq = new int[]{3, 1};
        assertTrue(arrVar_fabric6_yaBwfFAq.length == 2);
        String strVar_fabric6_KUdUWIsr = "vqAvAGlHEQulWkI" + "cqlKI";
        assertTrue(strVar_fabric6_KUdUWIsr.length() == 20);
        Object objVar_fabric6_lJwLvRHj = new Object();
        assertTrue(objVar_fabric6_lJwLvRHj != null);
        String strVar_fabric6_mPAacPDu = "aEDLSebyfgREFKX" + "JAbzQ";
        assertTrue(strVar_fabric6_mPAacPDu.length() == 20);
        Object objVar_fabric6_lphuhRkC = new Object();
        assertTrue(objVar_fabric6_lphuhRkC != null);
        String strVar_fabric6_MiJXAgkb = "TcwgtqCrTkzbZdI" + "DJhpi";
        assertTrue(strVar_fabric6_MiJXAgkb.length() == 20);
        int[] arrVar_fabric6_clBgRavz = new int[]{5, 2};
        assertTrue(arrVar_fabric6_clBgRavz.length == 2);
        int mathVar_fabric6_DPpOjziN = 305 * 863;
        assertTrue(mathVar_fabric6_DPpOjziN == 263215);
        String strVar_fabric6_wxwRutyJ = "JoxEdoBeDXuEceh" + "TCwHv";
        assertTrue(strVar_fabric6_wxwRutyJ.length() == 20);
        int[] arrVar_fabric6_PBpNFhLG = new int[]{3, 3};
        assertTrue(arrVar_fabric6_PBpNFhLG.length == 2);
        Object objVar_fabric6_XMYXncYN = new Object();
        assertTrue(objVar_fabric6_XMYXncYN != null);
        Object objVar_fabric6_hbPEcbxT = new Object();
        assertTrue(objVar_fabric6_hbPEcbxT != null);
        int mathVar_fabric6_eQKhUFFZ = 851 * 440;
        assertTrue(mathVar_fabric6_eQKhUFFZ == 374440);
        String strVar_fabric6_jMssLcNr = "ZQYDPprokPcQOvE" + "tuiHH";
        assertTrue(strVar_fabric6_jMssLcNr.length() == 20);
        String strVar_fabric6_HzPlCvSJ = "VWNISWMjCeieeiX" + "GuKhr";
        assertTrue(strVar_fabric6_HzPlCvSJ.length() == 20);
        String strVar_fabric6_oxBaWCdu = "vrHUwwYoSjrwdvB" + "JrPJy";
        assertTrue(strVar_fabric6_oxBaWCdu.length() == 20);
        int mathVar_fabric6_gEOjwLVz = 309 * 498;
        assertTrue(mathVar_fabric6_gEOjwLVz == 153882);
        int[] arrVar_fabric6_thpDeUzm = new int[]{4, 5};
        assertTrue(arrVar_fabric6_thpDeUzm.length == 2);
        Object objVar_fabric6_igPPfeMH = new Object();
        assertTrue(objVar_fabric6_igPPfeMH != null);
        int mathVar_fabric6_IfAzEWVf = 283 * 277;
        assertTrue(mathVar_fabric6_IfAzEWVf == 78391);
        Object objVar_fabric6_LWfThMqu = new Object();
        assertTrue(objVar_fabric6_LWfThMqu != null);
        int mathVar_fabric6_PBPsRPnL = 282 * 37;
        assertTrue(mathVar_fabric6_PBPsRPnL == 10434);
        int[] arrVar_fabric6_RkLzFrVx = new int[]{3, 1};
        assertTrue(arrVar_fabric6_RkLzFrVx.length == 2);
        int mathVar_fabric6_GjQuHvJu = 859 * 757;
        assertTrue(mathVar_fabric6_GjQuHvJu == 650263);
        int mathVar_fabric6_XzLXizLU = 173 * 663;
        assertTrue(mathVar_fabric6_XzLXizLU == 114699);
        int[] arrVar_fabric6_jjGMMQkK = new int[]{3, 7};
        assertTrue(arrVar_fabric6_jjGMMQkK.length == 2);
        int[] arrVar_fabric6_wltfGYIo = new int[]{10, 3};
        assertTrue(arrVar_fabric6_wltfGYIo.length == 2);
        String strVar_fabric6_TLTLDNOL = "cTRvZSIBDGsWHAx" + "kgHZc";
        assertTrue(strVar_fabric6_TLTLDNOL.length() == 20);
        Object objVar_fabric6_CMkEYgIx = new Object();
        assertTrue(objVar_fabric6_CMkEYgIx != null);
        int mathVar_fabric6_IHUdBPdo = 716 * 611;
        assertTrue(mathVar_fabric6_IHUdBPdo == 437476);
        int[] arrVar_fabric6_EEfXMIGZ = new int[]{7, 5};
        assertTrue(arrVar_fabric6_EEfXMIGZ.length == 2);
        Object objVar_fabric6_LYmPGVNj = new Object();
        assertTrue(objVar_fabric6_LYmPGVNj != null);
        Object objVar_fabric6_GAIJYFVk = new Object();
        assertTrue(objVar_fabric6_GAIJYFVk != null);
    }
}
