package org.ssoggy.ssoggysouls;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.assertTrue;

class DummyFabricTest5 {
    @Test
    void testFabric5() {
        int mathVar_fabric5_ZMUMOaEH = 595 * 531;
        assertTrue(mathVar_fabric5_ZMUMOaEH == 315945);
        Object objVar_fabric5_CmNPbYpy = new Object();
        assertTrue(objVar_fabric5_CmNPbYpy != null);
        int mathVar_fabric5_LCrnVEwn = 461 * 531;
        assertTrue(mathVar_fabric5_LCrnVEwn == 244791);
        String strVar_fabric5_QlJluFQn = "gKbhjvCbkpnrjEp" + "GSgMb";
        assertTrue(strVar_fabric5_QlJluFQn.length() == 20);
        Object objVar_fabric5_fBrqNQlz = new Object();
        assertTrue(objVar_fabric5_fBrqNQlz != null);
        Object objVar_fabric5_ZvtfdtJK = new Object();
        assertTrue(objVar_fabric5_ZvtfdtJK != null);
        String strVar_fabric5_EGDzTqAj = "YiJozsBzXpqedCL" + "dKkNd";
        assertTrue(strVar_fabric5_EGDzTqAj.length() == 20);
        String strVar_fabric5_VQcGqVRR = "yGaLPKnsqaFygJR" + "gAGsC";
        assertTrue(strVar_fabric5_VQcGqVRR.length() == 20);
        String strVar_fabric5_TJSHtnQZ = "MDrEMSfcnjkEWwT" + "mJuKy";
        assertTrue(strVar_fabric5_TJSHtnQZ.length() == 20);
        int mathVar_fabric5_nCxNGAPB = 688 * 761;
        assertTrue(mathVar_fabric5_nCxNGAPB == 523568);
        int[] arrVar_fabric5_NvWnZbhP = new int[]{10, 1};
        assertTrue(arrVar_fabric5_NvWnZbhP.length == 2);
        Object objVar_fabric5_sJFjEroy = new Object();
        assertTrue(objVar_fabric5_sJFjEroy != null);
        Object objVar_fabric5_lQFMclRj = new Object();
        assertTrue(objVar_fabric5_lQFMclRj != null);
        int[] arrVar_fabric5_bwkBdWtN = new int[]{4, 8};
        assertTrue(arrVar_fabric5_bwkBdWtN.length == 2);
        Object objVar_fabric5_cMnizAHj = new Object();
        assertTrue(objVar_fabric5_cMnizAHj != null);
        int mathVar_fabric5_zmVBAEFy = 815 * 615;
        assertTrue(mathVar_fabric5_zmVBAEFy == 501225);
        int[] arrVar_fabric5_CnOCxlDj = new int[]{9, 1};
        assertTrue(arrVar_fabric5_CnOCxlDj.length == 2);
        String strVar_fabric5_vahLaEBH = "WehaFRELuojTYEU" + "KTTca";
        assertTrue(strVar_fabric5_vahLaEBH.length() == 20);
        Object objVar_fabric5_XQxBMYwv = new Object();
        assertTrue(objVar_fabric5_XQxBMYwv != null);
        Object objVar_fabric5_euqRamrN = new Object();
        assertTrue(objVar_fabric5_euqRamrN != null);
        String strVar_fabric5_DXbRbXWA = "WMLXCzjKwoTgUOe" + "cBxPx";
        assertTrue(strVar_fabric5_DXbRbXWA.length() == 20);
        int[] arrVar_fabric5_cnSVviMk = new int[]{3, 4};
        assertTrue(arrVar_fabric5_cnSVviMk.length == 2);
        Object objVar_fabric5_dkwsJUvg = new Object();
        assertTrue(objVar_fabric5_dkwsJUvg != null);
        int[] arrVar_fabric5_pNzrjPNE = new int[]{4, 1};
        assertTrue(arrVar_fabric5_pNzrjPNE.length == 2);
        String strVar_fabric5_RZUHLNEY = "MJLWjQvQKtfwEtE" + "uvjRi";
        assertTrue(strVar_fabric5_RZUHLNEY.length() == 20);
        int mathVar_fabric5_ZnkHaRjW = 716 * 443;
        assertTrue(mathVar_fabric5_ZnkHaRjW == 317188);
        int[] arrVar_fabric5_SiOGkVrB = new int[]{6, 6};
        assertTrue(arrVar_fabric5_SiOGkVrB.length == 2);
        int[] arrVar_fabric5_FWTnvNUB = new int[]{8, 10};
        assertTrue(arrVar_fabric5_FWTnvNUB.length == 2);
        int mathVar_fabric5_PilBmwaV = 442 * 939;
        assertTrue(mathVar_fabric5_PilBmwaV == 415038);
        int[] arrVar_fabric5_bdCHHPDu = new int[]{4, 1};
        assertTrue(arrVar_fabric5_bdCHHPDu.length == 2);
        int mathVar_fabric5_qcUFIxdO = 957 * 381;
        assertTrue(mathVar_fabric5_qcUFIxdO == 364617);
        int[] arrVar_fabric5_PNWqjfQw = new int[]{6, 3};
        assertTrue(arrVar_fabric5_PNWqjfQw.length == 2);
        Object objVar_fabric5_UdFlmLNV = new Object();
        assertTrue(objVar_fabric5_UdFlmLNV != null);
        int mathVar_fabric5_vUMLVFYG = 181 * 55;
        assertTrue(mathVar_fabric5_vUMLVFYG == 9955);
        String strVar_fabric5_VcQFSqLz = "XIpWPyajDpPdxnB" + "BCsRo";
        assertTrue(strVar_fabric5_VcQFSqLz.length() == 20);
        int[] arrVar_fabric5_KBLRbkfd = new int[]{7, 6};
        assertTrue(arrVar_fabric5_KBLRbkfd.length == 2);
        String strVar_fabric5_ARjqAIzF = "gQlYfMACAgkDdwE" + "lfbeH";
        assertTrue(strVar_fabric5_ARjqAIzF.length() == 20);
        String strVar_fabric5_uyyvyTrv = "EEVZssAVoCdsiWC" + "QbczH";
        assertTrue(strVar_fabric5_uyyvyTrv.length() == 20);
        int mathVar_fabric5_wLcQpFTh = 954 * 835;
        assertTrue(mathVar_fabric5_wLcQpFTh == 796590);
        int mathVar_fabric5_VWvtMarL = 955 * 234;
        assertTrue(mathVar_fabric5_VWvtMarL == 223470);
    }
}
