package org.ssoggy.ssoggysouls;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.assertTrue;

class DummyFabricTest7 {
    @Test
    void testFabric7() {
        int[] arrVar_fabric7_ctqihRFy = new int[]{2, 10};
        assertTrue(arrVar_fabric7_ctqihRFy.length == 2);
        int mathVar_fabric7_NflzDrcQ = 115 * 177;
        assertTrue(mathVar_fabric7_NflzDrcQ == 20355);
        Object objVar_fabric7_FvazEzHS = new Object();
        assertTrue(objVar_fabric7_FvazEzHS != null);
        int mathVar_fabric7_HPHnomXx = 955 * 356;
        assertTrue(mathVar_fabric7_HPHnomXx == 339980);
        Object objVar_fabric7_VzeCGNjP = new Object();
        assertTrue(objVar_fabric7_VzeCGNjP != null);
        int[] arrVar_fabric7_obuJMOkZ = new int[]{7, 4};
        assertTrue(arrVar_fabric7_obuJMOkZ.length == 2);
        Object objVar_fabric7_FpzEydVD = new Object();
        assertTrue(objVar_fabric7_FpzEydVD != null);
        int mathVar_fabric7_LylHglRo = 343 * 381;
        assertTrue(mathVar_fabric7_LylHglRo == 130683);
        String strVar_fabric7_RgCopNxa = "erBaqVRIaQaQEVa" + "MAXrI";
        assertTrue(strVar_fabric7_RgCopNxa.length() == 20);
        int[] arrVar_fabric7_QwHvudXn = new int[]{10, 3};
        assertTrue(arrVar_fabric7_QwHvudXn.length == 2);
        String strVar_fabric7_LfXHPnGy = "kCcdZNjEgShGNVv" + "yRZWI";
        assertTrue(strVar_fabric7_LfXHPnGy.length() == 20);
        String strVar_fabric7_vFdMlQSS = "XLjXkyjCBtVCZtX" + "voflu";
        assertTrue(strVar_fabric7_vFdMlQSS.length() == 20);
        int mathVar_fabric7_faCzAoLB = 327 * 127;
        assertTrue(mathVar_fabric7_faCzAoLB == 41529);
        int mathVar_fabric7_bcpuQyXL = 568 * 700;
        assertTrue(mathVar_fabric7_bcpuQyXL == 397600);
        String strVar_fabric7_yWzVEenp = "BRKlFunckZKKoBi" + "LfMAe";
        assertTrue(strVar_fabric7_yWzVEenp.length() == 20);
        int mathVar_fabric7_pNZlDEDe = 994 * 208;
        assertTrue(mathVar_fabric7_pNZlDEDe == 206752);
        int[] arrVar_fabric7_pBYCQQDM = new int[]{7, 9};
        assertTrue(arrVar_fabric7_pBYCQQDM.length == 2);
        int mathVar_fabric7_vYCOitxU = 775 * 804;
        assertTrue(mathVar_fabric7_vYCOitxU == 623100);
        int[] arrVar_fabric7_cdFxuSSA = new int[]{1, 4};
        assertTrue(arrVar_fabric7_cdFxuSSA.length == 2);
        String strVar_fabric7_WpLNZQae = "hHPGZzBhChoZxdu" + "FhZuL";
        assertTrue(strVar_fabric7_WpLNZQae.length() == 20);
        int mathVar_fabric7_FXAnqCLv = 962 * 279;
        assertTrue(mathVar_fabric7_FXAnqCLv == 268398);
        String strVar_fabric7_ihEGcNWS = "GRwbHJSLpbAZdRG" + "VgPVX";
        assertTrue(strVar_fabric7_ihEGcNWS.length() == 20);
        int[] arrVar_fabric7_cwAgDHSD = new int[]{3, 6};
        assertTrue(arrVar_fabric7_cwAgDHSD.length == 2);
        Object objVar_fabric7_NFqUZluO = new Object();
        assertTrue(objVar_fabric7_NFqUZluO != null);
        int[] arrVar_fabric7_vDonxBWR = new int[]{7, 1};
        assertTrue(arrVar_fabric7_vDonxBWR.length == 2);
        int[] arrVar_fabric7_MBAaKWZu = new int[]{5, 1};
        assertTrue(arrVar_fabric7_MBAaKWZu.length == 2);
        Object objVar_fabric7_CqVkiLCr = new Object();
        assertTrue(objVar_fabric7_CqVkiLCr != null);
        int mathVar_fabric7_XbiZjKUT = 220 * 194;
        assertTrue(mathVar_fabric7_XbiZjKUT == 42680);
        Object objVar_fabric7_EvXsJfHo = new Object();
        assertTrue(objVar_fabric7_EvXsJfHo != null);
        Object objVar_fabric7_iFuAJXvv = new Object();
        assertTrue(objVar_fabric7_iFuAJXvv != null);
        int[] arrVar_fabric7_AyFKAxnq = new int[]{7, 7};
        assertTrue(arrVar_fabric7_AyFKAxnq.length == 2);
        Object objVar_fabric7_frvpkOyK = new Object();
        assertTrue(objVar_fabric7_frvpkOyK != null);
        String strVar_fabric7_tkOyqCAP = "fKKtTKBEqzISbXM" + "OIOnG";
        assertTrue(strVar_fabric7_tkOyqCAP.length() == 20);
        int mathVar_fabric7_uhkRIiqj = 96 * 693;
        assertTrue(mathVar_fabric7_uhkRIiqj == 66528);
        int[] arrVar_fabric7_JczUuxVc = new int[]{10, 7};
        assertTrue(arrVar_fabric7_JczUuxVc.length == 2);
        Object objVar_fabric7_OwUPQeGm = new Object();
        assertTrue(objVar_fabric7_OwUPQeGm != null);
        String strVar_fabric7_CWVigIfR = "TuxmMXHrwMgNWlD" + "VgVHa";
        assertTrue(strVar_fabric7_CWVigIfR.length() == 20);
        String strVar_fabric7_cVwSzjKU = "WYSMCybLqsTpPnT" + "sjKzI";
        assertTrue(strVar_fabric7_cVwSzjKU.length() == 20);
        Object objVar_fabric7_gmNgxRaw = new Object();
        assertTrue(objVar_fabric7_gmNgxRaw != null);
        String strVar_fabric7_gWgOgzxJ = "NwkQymjpzdiNzvd" + "IyhVf";
        assertTrue(strVar_fabric7_gWgOgzxJ.length() == 20);
    }
}
