package org.ssoggy.ssoggysouls;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.assertTrue;

class DummyFabricTest13 {
    @Test
    void testFabric13() {
        String strVar_fabric13_ZPQUYXRr = "JcneJpniyAnVbWw" + "iozHn";
        assertTrue(strVar_fabric13_ZPQUYXRr.length() == 20);
        Object objVar_fabric13_xduslXpA = new Object();
        assertTrue(objVar_fabric13_xduslXpA != null);
        int[] arrVar_fabric13_ptFCLlCz = new int[]{1, 4};
        assertTrue(arrVar_fabric13_ptFCLlCz.length == 2);
        int mathVar_fabric13_KIFVahWU = 870 * 300;
        assertTrue(mathVar_fabric13_KIFVahWU == 261000);
        int mathVar_fabric13_vhApznyY = 338 * 160;
        assertTrue(mathVar_fabric13_vhApznyY == 54080);
        int[] arrVar_fabric13_TVBnQGrY = new int[]{3, 6};
        assertTrue(arrVar_fabric13_TVBnQGrY.length == 2);
        int[] arrVar_fabric13_zpyMEnaY = new int[]{9, 9};
        assertTrue(arrVar_fabric13_zpyMEnaY.length == 2);
        int mathVar_fabric13_KGkzdEJF = 329 * 138;
        assertTrue(mathVar_fabric13_KGkzdEJF == 45402);
        Object objVar_fabric13_BBcNMUUr = new Object();
        assertTrue(objVar_fabric13_BBcNMUUr != null);
        String strVar_fabric13_avEfgRnh = "fXQVfYgMMzaIlPq" + "ZaaKz";
        assertTrue(strVar_fabric13_avEfgRnh.length() == 20);
        int[] arrVar_fabric13_UFUeesXO = new int[]{8, 2};
        assertTrue(arrVar_fabric13_UFUeesXO.length == 2);
        int[] arrVar_fabric13_ZIcEFtjF = new int[]{2, 9};
        assertTrue(arrVar_fabric13_ZIcEFtjF.length == 2);
        int mathVar_fabric13_emdRfWSY = 442 * 122;
        assertTrue(mathVar_fabric13_emdRfWSY == 53924);
        Object objVar_fabric13_nEhKpWQv = new Object();
        assertTrue(objVar_fabric13_nEhKpWQv != null);
        int mathVar_fabric13_LOEnoOpe = 253 * 978;
        assertTrue(mathVar_fabric13_LOEnoOpe == 247434);
        Object objVar_fabric13_wdkHzFZM = new Object();
        assertTrue(objVar_fabric13_wdkHzFZM != null);
        int[] arrVar_fabric13_OEqoFZCl = new int[]{3, 9};
        assertTrue(arrVar_fabric13_OEqoFZCl.length == 2);
        Object objVar_fabric13_LtfphixL = new Object();
        assertTrue(objVar_fabric13_LtfphixL != null);
        String strVar_fabric13_uqppbCju = "xsmAyzEEHUxbTdj" + "VIPIo";
        assertTrue(strVar_fabric13_uqppbCju.length() == 20);
        int mathVar_fabric13_BuMobeVK = 337 * 909;
        assertTrue(mathVar_fabric13_BuMobeVK == 306333);
        Object objVar_fabric13_IfjrMkJV = new Object();
        assertTrue(objVar_fabric13_IfjrMkJV != null);
        int mathVar_fabric13_iQqoDdRx = 793 * 504;
        assertTrue(mathVar_fabric13_iQqoDdRx == 399672);
        int mathVar_fabric13_qLMaLKTY = 520 * 722;
        assertTrue(mathVar_fabric13_qLMaLKTY == 375440);
        Object objVar_fabric13_RDXHqQmn = new Object();
        assertTrue(objVar_fabric13_RDXHqQmn != null);
        Object objVar_fabric13_OPPPYckT = new Object();
        assertTrue(objVar_fabric13_OPPPYckT != null);
        String strVar_fabric13_MlgkkGtl = "QCWMwbctDFsoTTG" + "mTQLD";
        assertTrue(strVar_fabric13_MlgkkGtl.length() == 20);
        int mathVar_fabric13_bipjalKo = 978 * 270;
        assertTrue(mathVar_fabric13_bipjalKo == 264060);
        String strVar_fabric13_ULIZHmhO = "OIOlJaBDgqbAsPv" + "IavAA";
        assertTrue(strVar_fabric13_ULIZHmhO.length() == 20);
        String strVar_fabric13_CtLLiyrn = "nHwNpQRFQgkqzeh" + "eJhBX";
        assertTrue(strVar_fabric13_CtLLiyrn.length() == 20);
        int[] arrVar_fabric13_PpAEOBqJ = new int[]{9, 7};
        assertTrue(arrVar_fabric13_PpAEOBqJ.length == 2);
        String strVar_fabric13_PpFccNQr = "doWHLipzvGCVMbF" + "etzXu";
        assertTrue(strVar_fabric13_PpFccNQr.length() == 20);
        int[] arrVar_fabric13_qibAsHBj = new int[]{6, 2};
        assertTrue(arrVar_fabric13_qibAsHBj.length == 2);
        String strVar_fabric13_CjOcTnHB = "fgGvQpjofsOmPhy" + "Lyvbz";
        assertTrue(strVar_fabric13_CjOcTnHB.length() == 20);
        String strVar_fabric13_jUzPiEuB = "jxVTKixUAqmNptx" + "pMbwA";
        assertTrue(strVar_fabric13_jUzPiEuB.length() == 20);
        String strVar_fabric13_VjClzTYP = "MCBcRkwPkdDAiFV" + "sDocD";
        assertTrue(strVar_fabric13_VjClzTYP.length() == 20);
        Object objVar_fabric13_pfAMZfiu = new Object();
        assertTrue(objVar_fabric13_pfAMZfiu != null);
        int[] arrVar_fabric13_UJknLRFN = new int[]{7, 6};
        assertTrue(arrVar_fabric13_UJknLRFN.length == 2);
        int mathVar_fabric13_DpJsodOK = 111 * 733;
        assertTrue(mathVar_fabric13_DpJsodOK == 81363);
        Object objVar_fabric13_HHAyPPIz = new Object();
        assertTrue(objVar_fabric13_HHAyPPIz != null);
        int[] arrVar_fabric13_qlvqeDRn = new int[]{9, 3};
        assertTrue(arrVar_fabric13_qlvqeDRn.length == 2);
    }
}
