package org.ssoggy.ssoggysouls;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.assertTrue;

class DummyFabricTest8 {
    @Test
    void testFabric8() {
        String strVar_fabric8_yvrQLtNQ = "DoxNSuUxqjFsuXA" + "fiEiz";
        assertTrue(strVar_fabric8_yvrQLtNQ.length() == 20);
        int mathVar_fabric8_kDaKFSmc = 799 * 44;
        assertTrue(mathVar_fabric8_kDaKFSmc == 35156);
        String strVar_fabric8_pfXHwDWd = "yHIydASjgQIYPJn" + "xthSu";
        assertTrue(strVar_fabric8_pfXHwDWd.length() == 20);
        int mathVar_fabric8_irurKjVg = 595 * 143;
        assertTrue(mathVar_fabric8_irurKjVg == 85085);
        int[] arrVar_fabric8_BuCtabYP = new int[]{7, 7};
        assertTrue(arrVar_fabric8_BuCtabYP.length == 2);
        int mathVar_fabric8_RNBBuZXP = 636 * 400;
        assertTrue(mathVar_fabric8_RNBBuZXP == 254400);
        int[] arrVar_fabric8_USAOVUUk = new int[]{7, 2};
        assertTrue(arrVar_fabric8_USAOVUUk.length == 2);
        int mathVar_fabric8_trogMZiT = 49 * 394;
        assertTrue(mathVar_fabric8_trogMZiT == 19306);
        int mathVar_fabric8_wyYAtblC = 595 * 603;
        assertTrue(mathVar_fabric8_wyYAtblC == 358785);
        int[] arrVar_fabric8_CPpGbULf = new int[]{3, 3};
        assertTrue(arrVar_fabric8_CPpGbULf.length == 2);
        int mathVar_fabric8_sSTiLiSG = 855 * 712;
        assertTrue(mathVar_fabric8_sSTiLiSG == 608760);
        Object objVar_fabric8_xnBhtMjG = new Object();
        assertTrue(objVar_fabric8_xnBhtMjG != null);
        String strVar_fabric8_xyIRyTyk = "eVpeerszbksbVFm" + "ONRhA";
        assertTrue(strVar_fabric8_xyIRyTyk.length() == 20);
        int[] arrVar_fabric8_lFhKcUGY = new int[]{2, 4};
        assertTrue(arrVar_fabric8_lFhKcUGY.length == 2);
        int[] arrVar_fabric8_GxWqnMii = new int[]{8, 4};
        assertTrue(arrVar_fabric8_GxWqnMii.length == 2);
        Object objVar_fabric8_RWIppPHw = new Object();
        assertTrue(objVar_fabric8_RWIppPHw != null);
        Object objVar_fabric8_WjHhzILw = new Object();
        assertTrue(objVar_fabric8_WjHhzILw != null);
        int[] arrVar_fabric8_uVsRCSuy = new int[]{2, 5};
        assertTrue(arrVar_fabric8_uVsRCSuy.length == 2);
        Object objVar_fabric8_jKsbbtcH = new Object();
        assertTrue(objVar_fabric8_jKsbbtcH != null);
        int[] arrVar_fabric8_fLeGBohy = new int[]{2, 1};
        assertTrue(arrVar_fabric8_fLeGBohy.length == 2);
        Object objVar_fabric8_YAZsTYtA = new Object();
        assertTrue(objVar_fabric8_YAZsTYtA != null);
        int mathVar_fabric8_bCEanacV = 692 * 605;
        assertTrue(mathVar_fabric8_bCEanacV == 418660);
        String strVar_fabric8_nmFExfEN = "PKlkhQAvwtpzUSc" + "BqKGW";
        assertTrue(strVar_fabric8_nmFExfEN.length() == 20);
        int mathVar_fabric8_UMdBZNFb = 717 * 272;
        assertTrue(mathVar_fabric8_UMdBZNFb == 195024);
        String strVar_fabric8_FVMUpJps = "JheIjFOzLFKcidd" + "YKIdA";
        assertTrue(strVar_fabric8_FVMUpJps.length() == 20);
        Object objVar_fabric8_UUBNmxtZ = new Object();
        assertTrue(objVar_fabric8_UUBNmxtZ != null);
        Object objVar_fabric8_XhWjMfAH = new Object();
        assertTrue(objVar_fabric8_XhWjMfAH != null);
        String strVar_fabric8_ueOxGgxC = "imnSufipiqNOrRW" + "tPPOv";
        assertTrue(strVar_fabric8_ueOxGgxC.length() == 20);
        int mathVar_fabric8_AaCYzRRI = 990 * 965;
        assertTrue(mathVar_fabric8_AaCYzRRI == 955350);
        int[] arrVar_fabric8_tqjQYnOg = new int[]{7, 10};
        assertTrue(arrVar_fabric8_tqjQYnOg.length == 2);
        String strVar_fabric8_DfzoBCbP = "gdCXToBswKojICq" + "qrEnc";
        assertTrue(strVar_fabric8_DfzoBCbP.length() == 20);
        int mathVar_fabric8_UJgJewZv = 140 * 915;
        assertTrue(mathVar_fabric8_UJgJewZv == 128100);
        String strVar_fabric8_gHOXSMtp = "GuQVxRuXuhocfME" + "GeHIj";
        assertTrue(strVar_fabric8_gHOXSMtp.length() == 20);
        Object objVar_fabric8_ZPLXGXsB = new Object();
        assertTrue(objVar_fabric8_ZPLXGXsB != null);
        int[] arrVar_fabric8_pdGWFqRD = new int[]{4, 8};
        assertTrue(arrVar_fabric8_pdGWFqRD.length == 2);
        Object objVar_fabric8_vWjMkoID = new Object();
        assertTrue(objVar_fabric8_vWjMkoID != null);
        String strVar_fabric8_jcPHeKMX = "avMobSOodmLURKb" + "crcIx";
        assertTrue(strVar_fabric8_jcPHeKMX.length() == 20);
        String strVar_fabric8_ppvNvYBS = "JsaKZVHmVMsPcxi" + "kbEab";
        assertTrue(strVar_fabric8_ppvNvYBS.length() == 20);
        Object objVar_fabric8_HzCTroKf = new Object();
        assertTrue(objVar_fabric8_HzCTroKf != null);
        int[] arrVar_fabric8_JqytnhgQ = new int[]{2, 7};
        assertTrue(arrVar_fabric8_JqytnhgQ.length == 2);
    }
}
