name: "Lint PR"

on:
  pull_request_target:
    types:
      - opened
      - edited
      - synchronize

permissions:
  pull-requests: read

jobs:
  main:
    name: Validate PR Title
    runs-on: ubuntu-latest
    steps:
      - name: Semantic PR Check
        uses: amannn/action-semantic-pull-request@v6.1.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          types: |
            feat
            fix
            refactor
            chore
            docs
          scopes: |
            paper
            fabric
            forge
            common
            github
          requireScope: true
