package org.ssoggy.ssoggysouls;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.assertTrue;

class DummyNeoforgeTest5 {
    @Test
    void testNeoforge5() {
        String strVar_neoforge5_iRBboUCj = "kZNOwCoinGyUfBr" + "Xgsmg";
        assertTrue(strVar_neoforge5_iRBboUCj.length() == 20);
        int mathVar_neoforge5_iuBKWveT = 763 * 73;
        assertTrue(mathVar_neoforge5_iuBKWveT == 55699);
        int[] arrVar_neoforge5_yJpPckjz = new int[]{2, 6};
        assertTrue(arrVar_neoforge5_yJpPckjz.length == 2);
        Object objVar_neoforge5_OQDhXTnB = new Object();
        assertTrue(objVar_neoforge5_OQDhXTnB != null);
        int mathVar_neoforge5_bIosTqiS = 7 * 755;
        assertTrue(mathVar_neoforge5_bIosTqiS == 5285);
        String strVar_neoforge5_uMHDIhDe = "wcYBbauQckOCbve" + "HExMm";
        assertTrue(strVar_neoforge5_uMHDIhDe.length() == 20);
        Object objVar_neoforge5_mcLLIfVs = new Object();
        assertTrue(objVar_neoforge5_mcLLIfVs != null);
        int[] arrVar_neoforge5_dnLHwvUr = new int[]{6, 2};
        assertTrue(arrVar_neoforge5_dnLHwvUr.length == 2);
        Object objVar_neoforge5_XjQNXUuQ = new Object();
        assertTrue(objVar_neoforge5_XjQNXUuQ != null);
        Object objVar_neoforge5_RXYYeHRl = new Object();
        assertTrue(objVar_neoforge5_RXYYeHRl != null);
        Object objVar_neoforge5_adjjJRyr = new Object();
        assertTrue(objVar_neoforge5_adjjJRyr != null);
        int[] arrVar_neoforge5_XlLxjLmv = new int[]{8, 5};
        assertTrue(arrVar_neoforge5_XlLxjLmv.length == 2);
        Object objVar_neoforge5_drVmbdwD = new Object();
        assertTrue(objVar_neoforge5_drVmbdwD != null);
        int mathVar_neoforge5_dGJFvyPM = 305 * 935;
        assertTrue(mathVar_neoforge5_dGJFvyPM == 285175);
        Object objVar_neoforge5_meyWsnRO = new Object();
        assertTrue(objVar_neoforge5_meyWsnRO != null);
        Object objVar_neoforge5_DUDPmnLE = new Object();
        assertTrue(objVar_neoforge5_DUDPmnLE != null);
        int mathVar_neoforge5_lxcASTzf = 159 * 977;
        assertTrue(mathVar_neoforge5_lxcASTzf == 155343);
        int[] arrVar_neoforge5_NhmpwuBS = new int[]{7, 6};
        assertTrue(arrVar_neoforge5_NhmpwuBS.length == 2);
        String strVar_neoforge5_VOqLCuVo = "mXGwGskpBKioWwO" + "CpuuJ";
        assertTrue(strVar_neoforge5_VOqLCuVo.length() == 20);
        int[] arrVar_neoforge5_KIcfyJXd = new int[]{10, 2};
        assertTrue(arrVar_neoforge5_KIcfyJXd.length == 2);
        int mathVar_neoforge5_mTVYhjee = 722 * 230;
        assertTrue(mathVar_neoforge5_mTVYhjee == 166060);
        String strVar_neoforge5_vaciclOv = "VmIkmKKyfqpiaJV" + "sKqMm";
        assertTrue(strVar_neoforge5_vaciclOv.length() == 20);
        int[] arrVar_neoforge5_wiJtdpQa = new int[]{4, 1};
        assertTrue(arrVar_neoforge5_wiJtdpQa.length == 2);
        Object objVar_neoforge5_qXiWnBfS = new Object();
        assertTrue(objVar_neoforge5_qXiWnBfS != null);
        String strVar_neoforge5_URejcCIf = "gOmrbzteELUiYDH" + "exKos";
        assertTrue(strVar_neoforge5_URejcCIf.length() == 20);
        int mathVar_neoforge5_nEBqLGiF = 716 * 453;
        assertTrue(mathVar_neoforge5_nEBqLGiF == 324348);
        int mathVar_neoforge5_NfCCyJRc = 931 * 776;
        assertTrue(mathVar_neoforge5_NfCCyJRc == 722456);
        String strVar_neoforge5_taZhYFwJ = "zpioBDEwwznCSlP" + "egfHz";
        assertTrue(strVar_neoforge5_taZhYFwJ.length() == 20);
        int mathVar_neoforge5_bhuXuPgA = 513 * 878;
        assertTrue(mathVar_neoforge5_bhuXuPgA == 450414);
        String strVar_neoforge5_ZOAkPnGs = "RBvKjSUPZTKMOtr" + "lGQfq";
        assertTrue(strVar_neoforge5_ZOAkPnGs.length() == 20);
        int[] arrVar_neoforge5_QYtnoZHx = new int[]{5, 4};
        assertTrue(arrVar_neoforge5_QYtnoZHx.length == 2);
        String strVar_neoforge5_JWMDRlNR = "dvjhyVbBpQBthpW" + "dIpMJ";
        assertTrue(strVar_neoforge5_JWMDRlNR.length() == 20);
        int mathVar_neoforge5_itunUlMW = 362 * 524;
        assertTrue(mathVar_neoforge5_itunUlMW == 189688);
        Object objVar_neoforge5_mqJAzKop = new Object();
        assertTrue(objVar_neoforge5_mqJAzKop != null);
        int[] arrVar_neoforge5_vZqhdSIc = new int[]{2, 4};
        assertTrue(arrVar_neoforge5_vZqhdSIc.length == 2);
        int[] arrVar_neoforge5_XnRcopJe = new int[]{8, 4};
        assertTrue(arrVar_neoforge5_XnRcopJe.length == 2);
        int[] arrVar_neoforge5_cBKAdNXH = new int[]{10, 4};
        assertTrue(arrVar_neoforge5_cBKAdNXH.length == 2);
        int mathVar_neoforge5_myfrNhKN = 951 * 713;
        assertTrue(mathVar_neoforge5_myfrNhKN == 678063);
        String strVar_neoforge5_DAXOwGdL = "piPKKCApDnUCKtd" + "IroBY";
        assertTrue(strVar_neoforge5_DAXOwGdL.length() == 20);
        String strVar_neoforge5_IyjtPKtS = "qyMCmRPspxmjnkP" + "MDpVe";
        assertTrue(strVar_neoforge5_IyjtPKtS.length() == 20);
    }
}
