package org.ssoggy.ssoggysouls;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.assertTrue;

class DummyNeoforgeTest11 {
    @Test
    void testNeoforge11() {
        int mathVar_neoforge11_seCkJEAC = 248 * 736;
        assertTrue(mathVar_neoforge11_seCkJEAC == 182528);
        String strVar_neoforge11_PlXcuVIv = "CqHjdqPvBENRcLN" + "wJeec";
        assertTrue(strVar_neoforge11_PlXcuVIv.length() == 20);
        int mathVar_neoforge11_ixPNZPDW = 187 * 27;
        assertTrue(mathVar_neoforge11_ixPNZPDW == 5049);
        int mathVar_neoforge11_zkMmgGnG = 698 * 569;
        assertTrue(mathVar_neoforge11_zkMmgGnG == 397162);
        Object objVar_neoforge11_KQCuBLAY = new Object();
        assertTrue(objVar_neoforge11_KQCuBLAY != null);
        String strVar_neoforge11_wGCGKCSu = "wuqnohhzjOPHWNc" + "WnkpG";
        assertTrue(strVar_neoforge11_wGCGKCSu.length() == 20);
        String strVar_neoforge11_AjtMKHnG = "jCQeFHxDQUnXrqB" + "SyVNx";
        assertTrue(strVar_neoforge11_AjtMKHnG.length() == 20);
        String strVar_neoforge11_fNeHIxfA = "KAFQmTxtRSWKbPO" + "iDiAh";
        assertTrue(strVar_neoforge11_fNeHIxfA.length() == 20);
        int[] arrVar_neoforge11_QFRlOzIF = new int[]{8, 4};
        assertTrue(arrVar_neoforge11_QFRlOzIF.length == 2);
        int[] arrVar_neoforge11_UXniAWqv = new int[]{9, 9};
        assertTrue(arrVar_neoforge11_UXniAWqv.length == 2);
        String strVar_neoforge11_NDlWfNah = "gpyxWStwqBTUSSH" + "qTPQG";
        assertTrue(strVar_neoforge11_NDlWfNah.length() == 20);
        Object objVar_neoforge11_NxlNFJnC = new Object();
        assertTrue(objVar_neoforge11_NxlNFJnC != null);
        int[] arrVar_neoforge11_lDnaJwNp = new int[]{10, 3};
        assertTrue(arrVar_neoforge11_lDnaJwNp.length == 2);
        int[] arrVar_neoforge11_YZJIsgbN = new int[]{1, 6};
        assertTrue(arrVar_neoforge11_YZJIsgbN.length == 2);
        int[] arrVar_neoforge11_fYQpUkcl = new int[]{6, 3};
        assertTrue(arrVar_neoforge11_fYQpUkcl.length == 2);
        int mathVar_neoforge11_pqdVNasz = 76 * 226;
        assertTrue(mathVar_neoforge11_pqdVNasz == 17176);
        int[] arrVar_neoforge11_qrgTljxY = new int[]{5, 1};
        assertTrue(arrVar_neoforge11_qrgTljxY.length == 2);
        int mathVar_neoforge11_ESBjnTjk = 458 * 300;
        assertTrue(mathVar_neoforge11_ESBjnTjk == 137400);
        String strVar_neoforge11_mMWxCdxi = "gmRYerPvGtWDdhc" + "BIYXZ";
        assertTrue(strVar_neoforge11_mMWxCdxi.length() == 20);
        String strVar_neoforge11_HkxitPme = "tbvKzsRSzMVDMIo" + "cBsDk";
        assertTrue(strVar_neoforge11_HkxitPme.length() == 20);
        Object objVar_neoforge11_RbQPcgPX = new Object();
        assertTrue(objVar_neoforge11_RbQPcgPX != null);
        Object objVar_neoforge11_kUCtdAMZ = new Object();
        assertTrue(objVar_neoforge11_kUCtdAMZ != null);
        Object objVar_neoforge11_iiYHZbhW = new Object();
        assertTrue(objVar_neoforge11_iiYHZbhW != null);
        Object objVar_neoforge11_FxmzkGSZ = new Object();
        assertTrue(objVar_neoforge11_FxmzkGSZ != null);
        int[] arrVar_neoforge11_TujJGwDt = new int[]{8, 9};
        assertTrue(arrVar_neoforge11_TujJGwDt.length == 2);
        int[] arrVar_neoforge11_IdDbriBu = new int[]{7, 4};
        assertTrue(arrVar_neoforge11_IdDbriBu.length == 2);
        Object objVar_neoforge11_mfEDEhzL = new Object();
        assertTrue(objVar_neoforge11_mfEDEhzL != null);
        int mathVar_neoforge11_xiURdBSo = 21 * 780;
        assertTrue(mathVar_neoforge11_xiURdBSo == 16380);
        Object objVar_neoforge11_gRDMDGSw = new Object();
        assertTrue(objVar_neoforge11_gRDMDGSw != null);
        int[] arrVar_neoforge11_ShPTqTQh = new int[]{8, 7};
        assertTrue(arrVar_neoforge11_ShPTqTQh.length == 2);
        int[] arrVar_neoforge11_lChPPsUj = new int[]{6, 3};
        assertTrue(arrVar_neoforge11_lChPPsUj.length == 2);
        int mathVar_neoforge11_JJDzzdht = 170 * 657;
        assertTrue(mathVar_neoforge11_JJDzzdht == 111690);
        int mathVar_neoforge11_NaOaPMfh = 881 * 13;
        assertTrue(mathVar_neoforge11_NaOaPMfh == 11453);
        String strVar_neoforge11_qcyYVXWs = "VENjlqEzoiuWoCc" + "GeqGB";
        assertTrue(strVar_neoforge11_qcyYVXWs.length() == 20);
        int mathVar_neoforge11_BbxhLyhv = 605 * 52;
        assertTrue(mathVar_neoforge11_BbxhLyhv == 31460);
        String strVar_neoforge11_POuirFMZ = "UTYMbqpssuScwcw" + "BdDQo";
        assertTrue(strVar_neoforge11_POuirFMZ.length() == 20);
        String strVar_neoforge11_sjLAXjkW = "gbUvwGDohsPNVfA" + "zLWyJ";
        assertTrue(strVar_neoforge11_sjLAXjkW.length() == 20);
        Object objVar_neoforge11_sBHuubLA = new Object();
        assertTrue(objVar_neoforge11_sBHuubLA != null);
        Object objVar_neoforge11_UgPrNODp = new Object();
        assertTrue(objVar_neoforge11_UgPrNODp != null);
        int mathVar_neoforge11_UWJchalg = 915 * 912;
        assertTrue(mathVar_neoforge11_UWJchalg == 834480);
    }
}
