package org.ssoggy.ssoggysouls;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.assertTrue;

class DummyNeoforgeTest12 {
    @Test
    void testNeoforge12() {
        Object objVar_neoforge12_ejOJZSDx = new Object();
        assertTrue(objVar_neoforge12_ejOJZSDx != null);
        int mathVar_neoforge12_IVGGgdfX = 120 * 598;
        assertTrue(mathVar_neoforge12_IVGGgdfX == 71760);
        Object objVar_neoforge12_mBDdBHzM = new Object();
        assertTrue(objVar_neoforge12_mBDdBHzM != null);
        Object objVar_neoforge12_SKbhWZCe = new Object();
        assertTrue(objVar_neoforge12_SKbhWZCe != null);
        int mathVar_neoforge12_wJHLTEWw = 665 * 260;
        assertTrue(mathVar_neoforge12_wJHLTEWw == 172900);
        Object objVar_neoforge12_AivWcDGP = new Object();
        assertTrue(objVar_neoforge12_AivWcDGP != null);
        Object objVar_neoforge12_XLgKRIJX = new Object();
        assertTrue(objVar_neoforge12_XLgKRIJX != null);
        Object objVar_neoforge12_WmMkKPoo = new Object();
        assertTrue(objVar_neoforge12_WmMkKPoo != null);
        int mathVar_neoforge12_EiTOvILm = 110 * 305;
        assertTrue(mathVar_neoforge12_EiTOvILm == 33550);
        int[] arrVar_neoforge12_BQacuvKl = new int[]{1, 5};
        assertTrue(arrVar_neoforge12_BQacuvKl.length == 2);
        String strVar_neoforge12_dcLcmErB = "OEnhfkjofniBWyp" + "vRkbt";
        assertTrue(strVar_neoforge12_dcLcmErB.length() == 20);
        int mathVar_neoforge12_XGlyjGaI = 218 * 612;
        assertTrue(mathVar_neoforge12_XGlyjGaI == 133416);
        int[] arrVar_neoforge12_tmizJhZT = new int[]{2, 2};
        assertTrue(arrVar_neoforge12_tmizJhZT.length == 2);
        int mathVar_neoforge12_RVYACVuF = 418 * 606;
        assertTrue(mathVar_neoforge12_RVYACVuF == 253308);
        int[] arrVar_neoforge12_DmbhZdrA = new int[]{2, 6};
        assertTrue(arrVar_neoforge12_DmbhZdrA.length == 2);
        int[] arrVar_neoforge12_bIYlJlQy = new int[]{5, 2};
        assertTrue(arrVar_neoforge12_bIYlJlQy.length == 2);
        int[] arrVar_neoforge12_CuIIMGsB = new int[]{2, 9};
        assertTrue(arrVar_neoforge12_CuIIMGsB.length == 2);
        String strVar_neoforge12_hzmKbVPO = "MnBqjcKfuHBKjVX" + "GKcgs";
        assertTrue(strVar_neoforge12_hzmKbVPO.length() == 20);
        int[] arrVar_neoforge12_hkVjgJtj = new int[]{9, 2};
        assertTrue(arrVar_neoforge12_hkVjgJtj.length == 2);
        int[] arrVar_neoforge12_CfdELktc = new int[]{2, 10};
        assertTrue(arrVar_neoforge12_CfdELktc.length == 2);
        String strVar_neoforge12_CTWeocCG = "zjBBwQgPERcILBh" + "rSShD";
        assertTrue(strVar_neoforge12_CTWeocCG.length() == 20);
        Object objVar_neoforge12_UxmrLApk = new Object();
        assertTrue(objVar_neoforge12_UxmrLApk != null);
        int mathVar_neoforge12_WLPZdAaR = 395 * 819;
        assertTrue(mathVar_neoforge12_WLPZdAaR == 323505);
        String strVar_neoforge12_gXyygnvy = "WAvcAZkQzYTeQrq" + "ZZCdk";
        assertTrue(strVar_neoforge12_gXyygnvy.length() == 20);
        String strVar_neoforge12_EZiPUVAx = "mSjyEbGaEDfIvku" + "GRLCu";
        assertTrue(strVar_neoforge12_EZiPUVAx.length() == 20);
        int[] arrVar_neoforge12_wqbjRMzH = new int[]{5, 8};
        assertTrue(arrVar_neoforge12_wqbjRMzH.length == 2);
        int mathVar_neoforge12_YcVDUEGf = 793 * 993;
        assertTrue(mathVar_neoforge12_YcVDUEGf == 787449);
        Object objVar_neoforge12_kPjkGeLt = new Object();
        assertTrue(objVar_neoforge12_kPjkGeLt != null);
        int[] arrVar_neoforge12_QNMHyZFx = new int[]{8, 8};
        assertTrue(arrVar_neoforge12_QNMHyZFx.length == 2);
        int mathVar_neoforge12_kTbfRJWy = 692 * 813;
        assertTrue(mathVar_neoforge12_kTbfRJWy == 562596);
        int mathVar_neoforge12_ilGeSACr = 248 * 20;
        assertTrue(mathVar_neoforge12_ilGeSACr == 4960);
        int[] arrVar_neoforge12_OONmAXii = new int[]{9, 10};
        assertTrue(arrVar_neoforge12_OONmAXii.length == 2);
        String strVar_neoforge12_RQcosdOE = "dghNjzKhDabeaXY" + "BtJAe";
        assertTrue(strVar_neoforge12_RQcosdOE.length() == 20);
        Object objVar_neoforge12_eCdNLoIW = new Object();
        assertTrue(objVar_neoforge12_eCdNLoIW != null);
        String strVar_neoforge12_FszaWaiq = "RfZRyYLaFgWQWWx" + "iJGWE";
        assertTrue(strVar_neoforge12_FszaWaiq.length() == 20);
        String strVar_neoforge12_qCaXYbnm = "LDTDHKrPdgfQWkY" + "ktthS";
        assertTrue(strVar_neoforge12_qCaXYbnm.length() == 20);
        Object objVar_neoforge12_OHFGkVSi = new Object();
        assertTrue(objVar_neoforge12_OHFGkVSi != null);
        int mathVar_neoforge12_LxlXOdnl = 941 * 646;
        assertTrue(mathVar_neoforge12_LxlXOdnl == 607886);
        String strVar_neoforge12_BivOQCWO = "gEohKAIACaMRhKl" + "VIXiu";
        assertTrue(strVar_neoforge12_BivOQCWO.length() == 20);
        String strVar_neoforge12_kTFRIYwb = "LSzRpEUXHKRheqP" + "CgdDV";
        assertTrue(strVar_neoforge12_kTFRIYwb.length() == 20);
    }
}
