package org.ssoggy.ssoggysouls;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.assertTrue;

class DummyNeoforgeTest6 {
    @Test
    void testNeoforge6() {
        int mathVar_neoforge6_efGLVdCz = 648 * 85;
        assertTrue(mathVar_neoforge6_efGLVdCz == 55080);
        Object objVar_neoforge6_KeJcMCRf = new Object();
        assertTrue(objVar_neoforge6_KeJcMCRf != null);
        int[] arrVar_neoforge6_bJfpiuHx = new int[]{3, 6};
        assertTrue(arrVar_neoforge6_bJfpiuHx.length == 2);
        String strVar_neoforge6_pHCwSBME = "SAftyKzemvMynjn" + "NtlRv";
        assertTrue(strVar_neoforge6_pHCwSBME.length() == 20);
        Object objVar_neoforge6_hRgJYPxt = new Object();
        assertTrue(objVar_neoforge6_hRgJYPxt != null);
        int[] arrVar_neoforge6_dzKpqjrv = new int[]{9, 10};
        assertTrue(arrVar_neoforge6_dzKpqjrv.length == 2);
        int mathVar_neoforge6_EQQFYPpV = 177 * 435;
        assertTrue(mathVar_neoforge6_EQQFYPpV == 76995);
        String strVar_neoforge6_zqGowFPm = "ErvMGcgYTYGTIDU" + "EutRB";
        assertTrue(strVar_neoforge6_zqGowFPm.length() == 20);
        Object objVar_neoforge6_jvDORRMZ = new Object();
        assertTrue(objVar_neoforge6_jvDORRMZ != null);
        int mathVar_neoforge6_xjxcbRId = 861 * 789;
        assertTrue(mathVar_neoforge6_xjxcbRId == 679329);
        String strVar_neoforge6_GgCYzIVU = "tEPtCqyjxmFJnIG" + "IXuJL";
        assertTrue(strVar_neoforge6_GgCYzIVU.length() == 20);
        int[] arrVar_neoforge6_kHrHRmjj = new int[]{3, 8};
        assertTrue(arrVar_neoforge6_kHrHRmjj.length == 2);
        Object objVar_neoforge6_lFMQHbXJ = new Object();
        assertTrue(objVar_neoforge6_lFMQHbXJ != null);
        String strVar_neoforge6_xDrOhBjK = "MatmxkEndcWlJfh" + "dDPkt";
        assertTrue(strVar_neoforge6_xDrOhBjK.length() == 20);
        int[] arrVar_neoforge6_HVpFSEQg = new int[]{10, 2};
        assertTrue(arrVar_neoforge6_HVpFSEQg.length == 2);
        String strVar_neoforge6_xjwSXWXP = "NXmJjOPhPqnODXb" + "xlUet";
        assertTrue(strVar_neoforge6_xjwSXWXP.length() == 20);
        Object objVar_neoforge6_fYBaSVcd = new Object();
        assertTrue(objVar_neoforge6_fYBaSVcd != null);
        Object objVar_neoforge6_EFyhIiNd = new Object();
        assertTrue(objVar_neoforge6_EFyhIiNd != null);
        int mathVar_neoforge6_oiadNnOx = 788 * 731;
        assertTrue(mathVar_neoforge6_oiadNnOx == 576028);
        Object objVar_neoforge6_tYOkhOGa = new Object();
        assertTrue(objVar_neoforge6_tYOkhOGa != null);
        int[] arrVar_neoforge6_ZTXfPoiG = new int[]{2, 1};
        assertTrue(arrVar_neoforge6_ZTXfPoiG.length == 2);
        int[] arrVar_neoforge6_HvRfhKUA = new int[]{10, 2};
        assertTrue(arrVar_neoforge6_HvRfhKUA.length == 2);
        String strVar_neoforge6_NuZgrDyR = "HaZaRidxUIUznfv" + "zmlPe";
        assertTrue(strVar_neoforge6_NuZgrDyR.length() == 20);
        int mathVar_neoforge6_yvIDgrvr = 849 * 417;
        assertTrue(mathVar_neoforge6_yvIDgrvr == 354033);
        String strVar_neoforge6_rvVyCxoj = "NNRgazTgksNBORZ" + "ZYhBb";
        assertTrue(strVar_neoforge6_rvVyCxoj.length() == 20);
        int mathVar_neoforge6_CLovcYjL = 767 * 805;
        assertTrue(mathVar_neoforge6_CLovcYjL == 617435);
        int mathVar_neoforge6_oQJdFimu = 466 * 782;
        assertTrue(mathVar_neoforge6_oQJdFimu == 364412);
        Object objVar_neoforge6_rZLzvMBj = new Object();
        assertTrue(objVar_neoforge6_rZLzvMBj != null);
        int[] arrVar_neoforge6_FOeAaant = new int[]{10, 6};
        assertTrue(arrVar_neoforge6_FOeAaant.length == 2);
        Object objVar_neoforge6_PJGrKgzj = new Object();
        assertTrue(objVar_neoforge6_PJGrKgzj != null);
        Object objVar_neoforge6_RspmWoMt = new Object();
        assertTrue(objVar_neoforge6_RspmWoMt != null);
        int mathVar_neoforge6_RhxmzLAl = 981 * 706;
        assertTrue(mathVar_neoforge6_RhxmzLAl == 692586);
        String strVar_neoforge6_bONHSFDD = "zyMLzyxAHEjrJNI" + "ulCIT";
        assertTrue(strVar_neoforge6_bONHSFDD.length() == 20);
        int[] arrVar_neoforge6_YWNMuvmR = new int[]{9, 8};
        assertTrue(arrVar_neoforge6_YWNMuvmR.length == 2);
        String strVar_neoforge6_PzkTXpCH = "euRFpMsqEtOHrHw" + "apazt";
        assertTrue(strVar_neoforge6_PzkTXpCH.length() == 20);
        int[] arrVar_neoforge6_wdeeAEqw = new int[]{3, 5};
        assertTrue(arrVar_neoforge6_wdeeAEqw.length == 2);
        int[] arrVar_neoforge6_AhSYDQpq = new int[]{4, 10};
        assertTrue(arrVar_neoforge6_AhSYDQpq.length == 2);
        String strVar_neoforge6_cIVJMqQS = "ZxwgnlGZJChQYBx" + "lnmPv";
        assertTrue(strVar_neoforge6_cIVJMqQS.length() == 20);
        int mathVar_neoforge6_cPXmafxh = 802 * 111;
        assertTrue(mathVar_neoforge6_cPXmafxh == 89022);
        int mathVar_neoforge6_pgwTHmIb = 344 * 969;
        assertTrue(mathVar_neoforge6_pgwTHmIb == 333336);
    }
}
