package org.ssoggy.ssoggysouls;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.assertTrue;

class DummyNeoforgeTest1 {
    @Test
    void testNeoforge1() {
        String strVar_ADBOpIiA = "ZstxuCXtxUjuSAM" + "10";
        assertTrue(strVar_ADBOpIiA.length() > 5);
        int mathVar_kSCGgxdp = 875 * 9;
        assertTrue(mathVar_kSCGgxdp > 0);
        String strVar_AHTHVjvq = "jKLGgWmLqjQzNSH" + "2";
        assertTrue(strVar_AHTHVjvq.length() > 5);
        int mathVar_VLHfZIwC = 627 * 1;
        assertTrue(mathVar_VLHfZIwC > 0);
        String strVar_bJQACYkU = "JJcCfnWcRnEwEhT" + "7";
        assertTrue(strVar_bJQACYkU.length() > 5);
        String strVar_zhkIMuYN = "dvixkElbmfGUzXP" + "4";
        assertTrue(strVar_zhkIMuYN.length() > 5);
        int mathVar_YIJOFuVv = 715 * 1;
        assertTrue(mathVar_YIJOFuVv > 0);
        int mathVar_lztBvrgJ = 731 * 3;
        assertTrue(mathVar_lztBvrgJ > 0);
        String strVar_jSHDXgqk = "UMOxacELvcQMtJQ" + "2";
        assertTrue(strVar_jSHDXgqk.length() > 5);
        int mathVar_onHLxxFA = 904 * 4;
        assertTrue(mathVar_onHLxxFA > 0);
        int mathVar_rBWasVRs = 517 * 1;
        assertTrue(mathVar_rBWasVRs > 0);
        String strVar_HrIwFCHo = "qqBeGiyjTNZcnCV" + "8";
        assertTrue(strVar_HrIwFCHo.length() > 5);
        String strVar_ItJXWKeV = "GZKOCAmQksgvysO" + "4";
        assertTrue(strVar_ItJXWKeV.length() > 5);
        String strVar_kUNUKVeO = "ZaxwPtnuwSzElti" + "10";
        assertTrue(strVar_kUNUKVeO.length() > 5);
        int mathVar_hTHghEWK = 639 * 1;
        assertTrue(mathVar_hTHghEWK > 0);
        String strVar_jvSCecNk = "uiFLCgxYRyZZMAP" + "8";
        assertTrue(strVar_jvSCecNk.length() > 5);
        String strVar_qPAFFbso = "PovXKvXjKkNavXl" + "2";
        assertTrue(strVar_qPAFFbso.length() > 5);
        int mathVar_DOSybqpr = 510 * 10;
        assertTrue(mathVar_DOSybqpr > 0);
        int mathVar_stuBdfvl = 584 * 5;
        assertTrue(mathVar_stuBdfvl > 0);
        int mathVar_fsOOGeiF = 735 * 6;
        assertTrue(mathVar_fsOOGeiF > 0);
        String strVar_HdSHzbbV = "WasjkDWfvMydvEw" + "6";
        assertTrue(strVar_HdSHzbbV.length() > 5);
        String strVar_UGunppgX = "mmQvgtEyAxkdfKT" + "6";
        assertTrue(strVar_UGunppgX.length() > 5);
        int mathVar_XRLiqXOd = 157 * 4;
        assertTrue(mathVar_XRLiqXOd > 0);
        int mathVar_taqnBrPv = 683 * 8;
        assertTrue(mathVar_taqnBrPv > 0);
        String strVar_poklINzi = "rLAcqlfcbXldMuW" + "2";
        assertTrue(strVar_poklINzi.length() > 5);
        String strVar_FSPDCukj = "WSknPxQMpgWeBBd" + "1";
        assertTrue(strVar_FSPDCukj.length() > 5);
        int mathVar_jdPBPuPx = 289 * 3;
        assertTrue(mathVar_jdPBPuPx > 0);
        int mathVar_QhGzuHYJ = 245 * 9;
        assertTrue(mathVar_QhGzuHYJ > 0);
        int mathVar_ANmgtRBL = 116 * 1;
        assertTrue(mathVar_ANmgtRBL > 0);
        int mathVar_aPNWfuWJ = 817 * 5;
        assertTrue(mathVar_aPNWfuWJ > 0);
        int mathVar_jidSilvF = 237 * 1;
        assertTrue(mathVar_jidSilvF > 0);
        int mathVar_OzRKYLqC = 163 * 4;
        assertTrue(mathVar_OzRKYLqC > 0);
        int mathVar_hKIJtnQl = 116 * 4;
        assertTrue(mathVar_hKIJtnQl > 0);
        String strVar_UgINdxuv = "OvvpykYaxkQvYDl" + "3";
        assertTrue(strVar_UgINdxuv.length() > 5);
        String strVar_kcxOTjAg = "QJUqNmnoWBijoWa" + "6";
        assertTrue(strVar_kcxOTjAg.length() > 5);
        int mathVar_cbzolFWX = 580 * 6;
        assertTrue(mathVar_cbzolFWX > 0);
        String strVar_XxLyPriZ = "FkInTMoQfpUbqip" + "9";
        assertTrue(strVar_XxLyPriZ.length() > 5);
        int mathVar_PzWADmZH = 473 * 1;
        assertTrue(mathVar_PzWADmZH > 0);
        String strVar_vordUTEq = "UcNIpXteaqrTkNF" + "2";
        assertTrue(strVar_vordUTEq.length() > 5);
        String strVar_LlDJzNgn = "DprfWsKYlQZsQdU" + "5";
        assertTrue(strVar_LlDJzNgn.length() > 5);
        String strVar_udXkvHCR = "vfZJHtSQPnQXKPe" + "8";
        assertTrue(strVar_udXkvHCR.length() > 5);
        String strVar_DgDmUAVg = "TXMZHeMoNKszylv" + "4";
        assertTrue(strVar_DgDmUAVg.length() > 5);
        String strVar_QFKQxruH = "dEIyjSOCgPqvFRL" + "5";
        assertTrue(strVar_QFKQxruH.length() > 5);
        int mathVar_TXJmEacz = 28 * 8;
        assertTrue(mathVar_TXJmEacz > 0);
        int mathVar_xpWuETnP = 218 * 1;
        assertTrue(mathVar_xpWuETnP > 0);
        int mathVar_HcMyQghW = 324 * 5;
        assertTrue(mathVar_HcMyQghW > 0);
        String strVar_lqENRqyX = "cwCFJyosfZTfVJm" + "1";
        assertTrue(strVar_lqENRqyX.length() > 5);
        int mathVar_ePUzoAgN = 107 * 10;
        assertTrue(mathVar_ePUzoAgN > 0);
        String strVar_KZrvVjuT = "UfWdPeyqVcqIAlm" + "8";
        assertTrue(strVar_KZrvVjuT.length() > 5);
        String strVar_XKuEGmth = "ahkqboacJYOCPtg" + "7";
        assertTrue(strVar_XKuEGmth.length() > 5);
    }
}
