package org.ssoggy.ssoggysouls;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.assertTrue;

class DummyNeoforgeTest2 {
    @Test
    void testNeoforge2() {
        int[] arrVar_neoforge2_XiYrEDFZ = new int[]{10, 7};
        assertTrue(arrVar_neoforge2_XiYrEDFZ.length == 2);
        int[] arrVar_neoforge2_gerQpHuw = new int[]{2, 3};
        assertTrue(arrVar_neoforge2_gerQpHuw.length == 2);
        int mathVar_neoforge2_QApwgoKC = 66 * 329;
        assertTrue(mathVar_neoforge2_QApwgoKC == 21714);
        int mathVar_neoforge2_UmVZyvBp = 55 * 38;
        assertTrue(mathVar_neoforge2_UmVZyvBp == 2090);
        String strVar_neoforge2_cuKEQdCg = "ngDPKQPyqXubAsd" + "fOrre";
        assertTrue(strVar_neoforge2_cuKEQdCg.length() == 20);
        String strVar_neoforge2_XAlXGZqQ = "ZiMGYUwwYxkkpdC" + "ptxzD";
        assertTrue(strVar_neoforge2_XAlXGZqQ.length() == 20);
        String strVar_neoforge2_WlwMXtMP = "omZnXIQLpuEmRso" + "wyFIv";
        assertTrue(strVar_neoforge2_WlwMXtMP.length() == 20);
        Object objVar_neoforge2_jlCgOjeP = new Object();
        assertTrue(objVar_neoforge2_jlCgOjeP != null);
        int mathVar_neoforge2_FxSTYlOO = 586 * 388;
        assertTrue(mathVar_neoforge2_FxSTYlOO == 227368);
        int[] arrVar_neoforge2_HdCjfHae = new int[]{6, 6};
        assertTrue(arrVar_neoforge2_HdCjfHae.length == 2);
        String strVar_neoforge2_jYqpzdga = "QxXAmeEjUkRdKgd" + "fBjmx";
        assertTrue(strVar_neoforge2_jYqpzdga.length() == 20);
        Object objVar_neoforge2_XDNJxGWm = new Object();
        assertTrue(objVar_neoforge2_XDNJxGWm != null);
        int mathVar_neoforge2_dAUtMFUS = 128 * 894;
        assertTrue(mathVar_neoforge2_dAUtMFUS == 114432);
        Object objVar_neoforge2_aRGYmKRG = new Object();
        assertTrue(objVar_neoforge2_aRGYmKRG != null);
        String strVar_neoforge2_PWlEqPFA = "QgwSsJJIugSSAVL" + "Liksv";
        assertTrue(strVar_neoforge2_PWlEqPFA.length() == 20);
        int mathVar_neoforge2_ZQSjdHKA = 441 * 66;
        assertTrue(mathVar_neoforge2_ZQSjdHKA == 29106);
        Object objVar_neoforge2_IZSgnvfL = new Object();
        assertTrue(objVar_neoforge2_IZSgnvfL != null);
        String strVar_neoforge2_GKFNzpqT = "lqOIcsvxseyOOlW" + "DARVF";
        assertTrue(strVar_neoforge2_GKFNzpqT.length() == 20);
        int mathVar_neoforge2_XQHvoobs = 117 * 940;
        assertTrue(mathVar_neoforge2_XQHvoobs == 109980);
        Object objVar_neoforge2_FPYSVkcN = new Object();
        assertTrue(objVar_neoforge2_FPYSVkcN != null);
        int mathVar_neoforge2_LHqEYThD = 755 * 425;
        assertTrue(mathVar_neoforge2_LHqEYThD == 320875);
        String strVar_neoforge2_QxRsIoji = "oQLRUSujfZZSXtQ" + "ZnRAM";
        assertTrue(strVar_neoforge2_QxRsIoji.length() == 20);
        int[] arrVar_neoforge2_ScpuPZzb = new int[]{4, 4};
        assertTrue(arrVar_neoforge2_ScpuPZzb.length == 2);
        Object objVar_neoforge2_mVNhpNzX = new Object();
        assertTrue(objVar_neoforge2_mVNhpNzX != null);
        String strVar_neoforge2_LfSekcwR = "bWMxXGHZCoIZnEF" + "yUZga";
        assertTrue(strVar_neoforge2_LfSekcwR.length() == 20);
        String strVar_neoforge2_HoOOaOPo = "BigXdiuSlQeZejq" + "qHDOg";
        assertTrue(strVar_neoforge2_HoOOaOPo.length() == 20);
        int mathVar_neoforge2_CfcawQsH = 205 * 341;
        assertTrue(mathVar_neoforge2_CfcawQsH == 69905);
        int[] arrVar_neoforge2_Jjlxaebd = new int[]{8, 9};
        assertTrue(arrVar_neoforge2_Jjlxaebd.length == 2);
        Object objVar_neoforge2_iAsZxFRs = new Object();
        assertTrue(objVar_neoforge2_iAsZxFRs != null);
        int[] arrVar_neoforge2_OivDtPmn = new int[]{3, 7};
        assertTrue(arrVar_neoforge2_OivDtPmn.length == 2);
        int[] arrVar_neoforge2_SKTawkbG = new int[]{4, 4};
        assertTrue(arrVar_neoforge2_SKTawkbG.length == 2);
        int mathVar_neoforge2_UljAegoC = 893 * 662;
        assertTrue(mathVar_neoforge2_UljAegoC == 591166);
        Object objVar_neoforge2_mEGxzwcX = new Object();
        assertTrue(objVar_neoforge2_mEGxzwcX != null);
        int[] arrVar_neoforge2_SbzRMjfx = new int[]{7, 5};
        assertTrue(arrVar_neoforge2_SbzRMjfx.length == 2);
        int[] arrVar_neoforge2_ftYfahPW = new int[]{3, 2};
        assertTrue(arrVar_neoforge2_ftYfahPW.length == 2);
        int mathVar_neoforge2_RnDUBGuG = 720 * 394;
        assertTrue(mathVar_neoforge2_RnDUBGuG == 283680);
        int[] arrVar_neoforge2_oZDNHlrE = new int[]{4, 9};
        assertTrue(arrVar_neoforge2_oZDNHlrE.length == 2);
        String strVar_neoforge2_sDmNIIod = "fPNGfhjeqkanlRC" + "idcym";
        assertTrue(strVar_neoforge2_sDmNIIod.length() == 20);
        Object objVar_neoforge2_JPeUyPzD = new Object();
        assertTrue(objVar_neoforge2_JPeUyPzD != null);
        Object objVar_neoforge2_zEyrAmYb = new Object();
        assertTrue(objVar_neoforge2_zEyrAmYb != null);
    }
}
