package org.ssoggy.ssoggysouls;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.assertTrue;

class DummyNeoforgeTest4 {
    @Test
    void testNeoforge4() {
        Object objVar_neoforge4_wiUiUogS = new Object();
        assertTrue(objVar_neoforge4_wiUiUogS != null);
        int mathVar_neoforge4_YIjTQjlB = 742 * 876;
        assertTrue(mathVar_neoforge4_YIjTQjlB == 649992);
        Object objVar_neoforge4_EANFRofw = new Object();
        assertTrue(objVar_neoforge4_EANFRofw != null);
        String strVar_neoforge4_XQgZGydq = "yGqLxZzvDGnKFbp" + "YXFxb";
        assertTrue(strVar_neoforge4_XQgZGydq.length() == 20);
        int mathVar_neoforge4_afQJGzPc = 210 * 529;
        assertTrue(mathVar_neoforge4_afQJGzPc == 111090);
        String strVar_neoforge4_zwjmaUMm = "NdTAODLSVoQwpeW" + "fRzEy";
        assertTrue(strVar_neoforge4_zwjmaUMm.length() == 20);
        int mathVar_neoforge4_xQeHAqgi = 558 * 723;
        assertTrue(mathVar_neoforge4_xQeHAqgi == 403434);
        Object objVar_neoforge4_uHqNhYKx = new Object();
        assertTrue(objVar_neoforge4_uHqNhYKx != null);
        int[] arrVar_neoforge4_QveZWsKz = new int[]{8, 7};
        assertTrue(arrVar_neoforge4_QveZWsKz.length == 2);
        Object objVar_neoforge4_jZCcVTbv = new Object();
        assertTrue(objVar_neoforge4_jZCcVTbv != null);
        String strVar_neoforge4_LmcSCFOv = "wgcClpjiuZkqTvF" + "imFCB";
        assertTrue(strVar_neoforge4_LmcSCFOv.length() == 20);
        Object objVar_neoforge4_eoyjOBvF = new Object();
        assertTrue(objVar_neoforge4_eoyjOBvF != null);
        String strVar_neoforge4_LMwtklFW = "BRJhLLBTQTpUSpS" + "CXWgF";
        assertTrue(strVar_neoforge4_LMwtklFW.length() == 20);
        int mathVar_neoforge4_PUypPnEi = 766 * 993;
        assertTrue(mathVar_neoforge4_PUypPnEi == 760638);
        int[] arrVar_neoforge4_PhVpuJiK = new int[]{2, 5};
        assertTrue(arrVar_neoforge4_PhVpuJiK.length == 2);
        int[] arrVar_neoforge4_XaFRENZB = new int[]{2, 5};
        assertTrue(arrVar_neoforge4_XaFRENZB.length == 2);
        int[] arrVar_neoforge4_CnwWHree = new int[]{3, 10};
        assertTrue(arrVar_neoforge4_CnwWHree.length == 2);
        int[] arrVar_neoforge4_hXCAiNTd = new int[]{6, 2};
        assertTrue(arrVar_neoforge4_hXCAiNTd.length == 2);
        int mathVar_neoforge4_qvFvvaID = 517 * 115;
        assertTrue(mathVar_neoforge4_qvFvvaID == 59455);
        Object objVar_neoforge4_KteaDZZo = new Object();
        assertTrue(objVar_neoforge4_KteaDZZo != null);
        String strVar_neoforge4_BrshUCEU = "NvMLAEDOLVtdkWQ" + "Dpkzo";
        assertTrue(strVar_neoforge4_BrshUCEU.length() == 20);
        String strVar_neoforge4_PJcXYull = "YHTbJyPCWZzepXk" + "bhznG";
        assertTrue(strVar_neoforge4_PJcXYull.length() == 20);
        int[] arrVar_neoforge4_rpDTxDDE = new int[]{5, 10};
        assertTrue(arrVar_neoforge4_rpDTxDDE.length == 2);
        Object objVar_neoforge4_EAJgGYVH = new Object();
        assertTrue(objVar_neoforge4_EAJgGYVH != null);
        int[] arrVar_neoforge4_yHlkDKKH = new int[]{3, 4};
        assertTrue(arrVar_neoforge4_yHlkDKKH.length == 2);
        int mathVar_neoforge4_TuqQOSEs = 440 * 198;
        assertTrue(mathVar_neoforge4_TuqQOSEs == 87120);
        int mathVar_neoforge4_ltQjeGjL = 196 * 368;
        assertTrue(mathVar_neoforge4_ltQjeGjL == 72128);
        Object objVar_neoforge4_mCGZDtgF = new Object();
        assertTrue(objVar_neoforge4_mCGZDtgF != null);
        int[] arrVar_neoforge4_onapMDnq = new int[]{1, 5};
        assertTrue(arrVar_neoforge4_onapMDnq.length == 2);
        String strVar_neoforge4_uqStCWJs = "MXkYUDeBaHrAYGn" + "sSkzQ";
        assertTrue(strVar_neoforge4_uqStCWJs.length() == 20);
        String strVar_neoforge4_vXWJBhMp = "zDyPdaHBAhprQkN" + "LiZJE";
        assertTrue(strVar_neoforge4_vXWJBhMp.length() == 20);
        int[] arrVar_neoforge4_WTLVvrfv = new int[]{3, 8};
        assertTrue(arrVar_neoforge4_WTLVvrfv.length == 2);
        String strVar_neoforge4_FYZRwyeY = "ArwUduIDPcQGgit" + "zAiMI";
        assertTrue(strVar_neoforge4_FYZRwyeY.length() == 20);
        int mathVar_neoforge4_GNvWYyIP = 365 * 212;
        assertTrue(mathVar_neoforge4_GNvWYyIP == 77380);
        String strVar_neoforge4_QCtpuypk = "VWsjPGKDKvqbytC" + "glTTo";
        assertTrue(strVar_neoforge4_QCtpuypk.length() == 20);
        Object objVar_neoforge4_FFYkcJeN = new Object();
        assertTrue(objVar_neoforge4_FFYkcJeN != null);
        int mathVar_neoforge4_FGMZgdsN = 625 * 675;
        assertTrue(mathVar_neoforge4_FGMZgdsN == 421875);
        Object objVar_neoforge4_OZYiMSew = new Object();
        assertTrue(objVar_neoforge4_OZYiMSew != null);
        int mathVar_neoforge4_vBoXJHml = 204 * 327;
        assertTrue(mathVar_neoforge4_vBoXJHml == 66708);
        int[] arrVar_neoforge4_BxfBUsMK = new int[]{10, 5};
        assertTrue(arrVar_neoforge4_BxfBUsMK.length == 2);
    }
}
