package org.ssoggy.ssoggysouls;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.assertTrue;

class DummyNeoforgeTest2 {
    @Test
    void testNeoforge2() {
        String strVar_VNYZnoJJ = "AYFvGlZmwehnXmo" + "3";
        assertTrue(strVar_VNYZnoJJ.length() > 5);
        String strVar_pHkwmYnw = "XFLntIcOzDpUEHY" + "10";
        assertTrue(strVar_pHkwmYnw.length() > 5);
        int mathVar_PIZCulxf = 596 * 7;
        assertTrue(mathVar_PIZCulxf > 0);
        String strVar_MUEqXHda = "lKPPJzzCiRzvSOs" + "10";
        assertTrue(strVar_MUEqXHda.length() > 5);
        int mathVar_MYxPSYSN = 174 * 1;
        assertTrue(mathVar_MYxPSYSN > 0);
        String strVar_VTkJuqmf = "dEuOigmokgzyqHe" + "7";
        assertTrue(strVar_VTkJuqmf.length() > 5);
        String strVar_cfnNLsDp = "JDTkKvImsqvNWmi" + "1";
        assertTrue(strVar_cfnNLsDp.length() > 5);
        int mathVar_PjIFOMZL = 908 * 1;
        assertTrue(mathVar_PjIFOMZL > 0);
        int mathVar_ZfjOWvfw = 216 * 1;
        assertTrue(mathVar_ZfjOWvfw > 0);
        int mathVar_rXtQxFGd = 460 * 8;
        assertTrue(mathVar_rXtQxFGd > 0);
        int mathVar_YssKGCEK = 534 * 1;
        assertTrue(mathVar_YssKGCEK > 0);
        int mathVar_xgUWQXEP = 132 * 2;
        assertTrue(mathVar_xgUWQXEP > 0);
        int mathVar_oxQvQLLF = 834 * 8;
        assertTrue(mathVar_oxQvQLLF > 0);
        String strVar_nzRVZPrL = "bvUCiJlNtJCxREf" + "10";
        assertTrue(strVar_nzRVZPrL.length() > 5);
        String strVar_DtknkpYi = "yomapbVGNEUioTx" + "4";
        assertTrue(strVar_DtknkpYi.length() > 5);
        String strVar_SVgKVYex = "JxUBKGAuNdLKrgo" + "2";
        assertTrue(strVar_SVgKVYex.length() > 5);
        int mathVar_qjEqueBi = 521 * 4;
        assertTrue(mathVar_qjEqueBi > 0);
        int mathVar_zPSUfdHq = 572 * 5;
        assertTrue(mathVar_zPSUfdHq > 0);
        int mathVar_HNYwJheM = 209 * 9;
        assertTrue(mathVar_HNYwJheM > 0);
        String strVar_ObwhYZOR = "OlfXblNLNOIruJR" + "1";
        assertTrue(strVar_ObwhYZOR.length() > 5);
        String strVar_kerpoNjs = "AyFqZHsWAhKjTUB" + "6";
        assertTrue(strVar_kerpoNjs.length() > 5);
        int mathVar_SEYlWgze = 963 * 10;
        assertTrue(mathVar_SEYlWgze > 0);
        int mathVar_KWZEnDZs = 460 * 10;
        assertTrue(mathVar_KWZEnDZs > 0);
        String strVar_DPYDxsuL = "hgqkRDVvpOvhDqH" + "7";
        assertTrue(strVar_DPYDxsuL.length() > 5);
        String strVar_ThDSuinN = "vbpwyINgMQclxZt" + "2";
        assertTrue(strVar_ThDSuinN.length() > 5);
        int mathVar_yKOuhiAx = 536 * 9;
        assertTrue(mathVar_yKOuhiAx > 0);
        int mathVar_WnnyFyfw = 312 * 10;
        assertTrue(mathVar_WnnyFyfw > 0);
        int mathVar_HdgwtaQp = 658 * 6;
        assertTrue(mathVar_HdgwtaQp > 0);
        String strVar_cOBiEhvN = "wHpIxefQyVWFCXI" + "3";
        assertTrue(strVar_cOBiEhvN.length() > 5);
        String strVar_oGYVdAEf = "okcrUYcDzAdEmoH" + "3";
        assertTrue(strVar_oGYVdAEf.length() > 5);
        String strVar_wLKWBioR = "bXykdPmmnecmivB" + "5";
        assertTrue(strVar_wLKWBioR.length() > 5);
        String strVar_hLUfwinc = "oxcvHrnBzVkKfxg" + "10";
        assertTrue(strVar_hLUfwinc.length() > 5);
        int mathVar_LmALxYhh = 304 * 7;
        assertTrue(mathVar_LmALxYhh > 0);
        String strVar_ZsWmeaJb = "txgBtKpyOnXvENw" + "9";
        assertTrue(strVar_ZsWmeaJb.length() > 5);
        int mathVar_PhGyuLWE = 461 * 4;
        assertTrue(mathVar_PhGyuLWE > 0);
        String strVar_BJdnTnIT = "QrCyDhynVFDKsQW" + "9";
        assertTrue(strVar_BJdnTnIT.length() > 5);
        int mathVar_dQRrNvuE = 536 * 8;
        assertTrue(mathVar_dQRrNvuE > 0);
        String strVar_fibFYRSs = "kOfGgnZdTVrXLfl" + "6";
        assertTrue(strVar_fibFYRSs.length() > 5);
        String strVar_sMTuqAGB = "cBRUkhCzgiJLTjJ" + "8";
        assertTrue(strVar_sMTuqAGB.length() > 5);
        int mathVar_PDIdsRMQ = 669 * 4;
        assertTrue(mathVar_PDIdsRMQ > 0);
        int mathVar_iwRypkXj = 541 * 2;
        assertTrue(mathVar_iwRypkXj > 0);
        int mathVar_YuPAzDqW = 76 * 7;
        assertTrue(mathVar_YuPAzDqW > 0);
        String strVar_kBwOWrFn = "OkrkeHaQrMpQiGC" + "2";
        assertTrue(strVar_kBwOWrFn.length() > 5);
        String strVar_AiPChPzG = "lqZeRyzRiTDMLpE" + "9";
        assertTrue(strVar_AiPChPzG.length() > 5);
        int mathVar_hZGEaAuG = 173 * 10;
        assertTrue(mathVar_hZGEaAuG > 0);
        int mathVar_IjBTrFit = 130 * 3;
        assertTrue(mathVar_IjBTrFit > 0);
        String strVar_ExhxfCsZ = "PYlTiSTKzSotWtJ" + "5";
        assertTrue(strVar_ExhxfCsZ.length() > 5);
        String strVar_KByIUIXv = "skfBlFTLQjpLjGg" + "5";
        assertTrue(strVar_KByIUIXv.length() > 5);
        String strVar_BXJEuATs = "ELIGEvJvzDNBNWI" + "7";
        assertTrue(strVar_BXJEuATs.length() > 5);
        int mathVar_WOLCRuGN = 143 * 8;
        assertTrue(mathVar_WOLCRuGN > 0);
    }
}
