package org.ssoggy.ssoggysouls;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.assertTrue;

class DummyNeoforgeTest3 {
    @Test
    void testNeoforge3() {
        int mathVar_neoforge3_ETQLGIDX = 741 * 488;
        assertTrue(mathVar_neoforge3_ETQLGIDX == 361608);
        Object objVar_neoforge3_ZVyucrIO = new Object();
        assertTrue(objVar_neoforge3_ZVyucrIO != null);
        int mathVar_neoforge3_khvKGJEm = 808 * 281;
        assertTrue(mathVar_neoforge3_khvKGJEm == 227048);
        int mathVar_neoforge3_TkvAyuUn = 169 * 491;
        assertTrue(mathVar_neoforge3_TkvAyuUn == 82979);
        int[] arrVar_neoforge3_DZyydFmH = new int[]{4, 1};
        assertTrue(arrVar_neoforge3_DZyydFmH.length == 2);
        int mathVar_neoforge3_ngBMunIY = 962 * 515;
        assertTrue(mathVar_neoforge3_ngBMunIY == 495430);
        String strVar_neoforge3_FGalIUbD = "UKSNNUcmhNLvrjY" + "OeZsK";
        assertTrue(strVar_neoforge3_FGalIUbD.length() == 20);
        String strVar_neoforge3_dAJswuXY = "VrZMkjbilNqpclK" + "CulJx";
        assertTrue(strVar_neoforge3_dAJswuXY.length() == 20);
        int mathVar_neoforge3_tyMdeHnu = 940 * 122;
        assertTrue(mathVar_neoforge3_tyMdeHnu == 114680);
        int[] arrVar_neoforge3_lhcysezM = new int[]{2, 1};
        assertTrue(arrVar_neoforge3_lhcysezM.length == 2);
        int[] arrVar_neoforge3_UdovDKKh = new int[]{5, 2};
        assertTrue(arrVar_neoforge3_UdovDKKh.length == 2);
        int[] arrVar_neoforge3_liBCcBjN = new int[]{2, 10};
        assertTrue(arrVar_neoforge3_liBCcBjN.length == 2);
        Object objVar_neoforge3_zrwnqHZA = new Object();
        assertTrue(objVar_neoforge3_zrwnqHZA != null);
        int mathVar_neoforge3_APgfRAHc = 381 * 232;
        assertTrue(mathVar_neoforge3_APgfRAHc == 88392);
        Object objVar_neoforge3_kYnHKvjV = new Object();
        assertTrue(objVar_neoforge3_kYnHKvjV != null);
        int mathVar_neoforge3_WSXrgBTv = 716 * 219;
        assertTrue(mathVar_neoforge3_WSXrgBTv == 156804);
        int[] arrVar_neoforge3_gifHVOGo = new int[]{6, 3};
        assertTrue(arrVar_neoforge3_gifHVOGo.length == 2);
        int[] arrVar_neoforge3_nlmqOtxx = new int[]{4, 9};
        assertTrue(arrVar_neoforge3_nlmqOtxx.length == 2);
        Object objVar_neoforge3_bNljaoMN = new Object();
        assertTrue(objVar_neoforge3_bNljaoMN != null);
        Object objVar_neoforge3_NIJbfocs = new Object();
        assertTrue(objVar_neoforge3_NIJbfocs != null);
        String strVar_neoforge3_MvuRveiD = "DQxQGJcjPkebrkR" + "uQGAV";
        assertTrue(strVar_neoforge3_MvuRveiD.length() == 20);
        String strVar_neoforge3_TqxqAwEu = "iUltBWvyxhMaXcx" + "KgyJC";
        assertTrue(strVar_neoforge3_TqxqAwEu.length() == 20);
        int[] arrVar_neoforge3_EiXvkhvx = new int[]{4, 7};
        assertTrue(arrVar_neoforge3_EiXvkhvx.length == 2);
        int mathVar_neoforge3_OeXMOjhS = 114 * 682;
        assertTrue(mathVar_neoforge3_OeXMOjhS == 77748);
        Object objVar_neoforge3_JmYSUjZO = new Object();
        assertTrue(objVar_neoforge3_JmYSUjZO != null);
        Object objVar_neoforge3_rFFrXGBo = new Object();
        assertTrue(objVar_neoforge3_rFFrXGBo != null);
        int[] arrVar_neoforge3_iwmenSoM = new int[]{9, 8};
        assertTrue(arrVar_neoforge3_iwmenSoM.length == 2);
        String strVar_neoforge3_YgXHuEXW = "TKUDePOTmdzQyrT" + "tOBTH";
        assertTrue(strVar_neoforge3_YgXHuEXW.length() == 20);
        int mathVar_neoforge3_yYZyglqM = 326 * 825;
        assertTrue(mathVar_neoforge3_yYZyglqM == 268950);
        String strVar_neoforge3_uRZYgFPv = "zpXFJbpGopGXdvC" + "hQkBq";
        assertTrue(strVar_neoforge3_uRZYgFPv.length() == 20);
        Object objVar_neoforge3_sxVczvcl = new Object();
        assertTrue(objVar_neoforge3_sxVczvcl != null);
        String strVar_neoforge3_xGxWGBBO = "lKJTGjwHoRJqUpZ" + "gnndR";
        assertTrue(strVar_neoforge3_xGxWGBBO.length() == 20);
        String strVar_neoforge3_DkcgiTWM = "WejBIWTuqmpNXVc" + "FUOwO";
        assertTrue(strVar_neoforge3_DkcgiTWM.length() == 20);
        int[] arrVar_neoforge3_oOasjMTb = new int[]{2, 1};
        assertTrue(arrVar_neoforge3_oOasjMTb.length == 2);
        int[] arrVar_neoforge3_iQdxRiIH = new int[]{4, 7};
        assertTrue(arrVar_neoforge3_iQdxRiIH.length == 2);
        String strVar_neoforge3_koHTdiSv = "tVAiMXpBZsSNEIW" + "vOFMm";
        assertTrue(strVar_neoforge3_koHTdiSv.length() == 20);
        Object objVar_neoforge3_YAsumeBj = new Object();
        assertTrue(objVar_neoforge3_YAsumeBj != null);
        int mathVar_neoforge3_XOtJGgCW = 650 * 750;
        assertTrue(mathVar_neoforge3_XOtJGgCW == 487500);
        Object objVar_neoforge3_nLyQANkm = new Object();
        assertTrue(objVar_neoforge3_nLyQANkm != null);
        String strVar_neoforge3_fZuAzSct = "CHoJNVbGKbpIgMy" + "Tudyt";
        assertTrue(strVar_neoforge3_fZuAzSct.length() == 20);
    }
}
