package org.ssoggy.ssoggysouls;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.assertTrue;

class DummyNeoforgeTest1 {
    @Test
    void testNeoforge1() {
        Object objVar_neoforge1_XdqRNCqu = new Object();
        assertTrue(objVar_neoforge1_XdqRNCqu != null);
        int mathVar_neoforge1_VWNYgrqc = 909 * 552;
        assertTrue(mathVar_neoforge1_VWNYgrqc == 501768);
        String strVar_neoforge1_VqNGYKdt = "mEfqhNvTqGtcWYS" + "lGIKH";
        assertTrue(strVar_neoforge1_VqNGYKdt.length() == 20);
        int mathVar_neoforge1_kariDVMb = 280 * 170;
        assertTrue(mathVar_neoforge1_kariDVMb == 47600);
        String strVar_neoforge1_IKRBcKjJ = "niNzPSJlztfSZKW" + "DVnsz";
        assertTrue(strVar_neoforge1_IKRBcKjJ.length() == 20);
        Object objVar_neoforge1_rXbvzWvO = new Object();
        assertTrue(objVar_neoforge1_rXbvzWvO != null);
        Object objVar_neoforge1_TozpBXEG = new Object();
        assertTrue(objVar_neoforge1_TozpBXEG != null);
        int mathVar_neoforge1_QBGIVGBf = 824 * 848;
        assertTrue(mathVar_neoforge1_QBGIVGBf == 698752);
        Object objVar_neoforge1_KggfgkHn = new Object();
        assertTrue(objVar_neoforge1_KggfgkHn != null);
        String strVar_neoforge1_RTWYXvHx = "HSzxYYjwAcjdLig" + "lSxCT";
        assertTrue(strVar_neoforge1_RTWYXvHx.length() == 20);
        Object objVar_neoforge1_iPxzllVp = new Object();
        assertTrue(objVar_neoforge1_iPxzllVp != null);
        int[] arrVar_neoforge1_QHKuXGWp = new int[]{4, 9};
        assertTrue(arrVar_neoforge1_QHKuXGWp.length == 2);
        Object objVar_neoforge1_UwkJqawk = new Object();
        assertTrue(objVar_neoforge1_UwkJqawk != null);
        Object objVar_neoforge1_qhhJUZNi = new Object();
        assertTrue(objVar_neoforge1_qhhJUZNi != null);
        int mathVar_neoforge1_vqeCLfzX = 555 * 526;
        assertTrue(mathVar_neoforge1_vqeCLfzX == 291930);
        String strVar_neoforge1_wYuSLfSg = "IwYdBkYvyPKTYUK" + "Noutf";
        assertTrue(strVar_neoforge1_wYuSLfSg.length() == 20);
        String strVar_neoforge1_kPuMdrFU = "LIGcmGRBpjBNUcn" + "XVlxE";
        assertTrue(strVar_neoforge1_kPuMdrFU.length() == 20);
        int[] arrVar_neoforge1_dWLSDMgo = new int[]{3, 6};
        assertTrue(arrVar_neoforge1_dWLSDMgo.length == 2);
        Object objVar_neoforge1_oSUGUZIE = new Object();
        assertTrue(objVar_neoforge1_oSUGUZIE != null);
        int[] arrVar_neoforge1_lklbUeiw = new int[]{8, 1};
        assertTrue(arrVar_neoforge1_lklbUeiw.length == 2);
        int mathVar_neoforge1_fahNkCPH = 883 * 177;
        assertTrue(mathVar_neoforge1_fahNkCPH == 156291);
        String strVar_neoforge1_cWrEuaVk = "hKWqnDQvJMsNYod" + "BKmam";
        assertTrue(strVar_neoforge1_cWrEuaVk.length() == 20);
        int[] arrVar_neoforge1_HHXvanSY = new int[]{10, 10};
        assertTrue(arrVar_neoforge1_HHXvanSY.length == 2);
        String strVar_neoforge1_jUwqhjgn = "hNVeXmLGZqzkwXw" + "EbalJ";
        assertTrue(strVar_neoforge1_jUwqhjgn.length() == 20);
        int mathVar_neoforge1_DPoMVSPy = 378 * 536;
        assertTrue(mathVar_neoforge1_DPoMVSPy == 202608);
        int[] arrVar_neoforge1_OPanxtTV = new int[]{9, 7};
        assertTrue(arrVar_neoforge1_OPanxtTV.length == 2);
        int mathVar_neoforge1_EguvoDvS = 288 * 343;
        assertTrue(mathVar_neoforge1_EguvoDvS == 98784);
        int mathVar_neoforge1_FDjnglRL = 268 * 365;
        assertTrue(mathVar_neoforge1_FDjnglRL == 97820);
        int mathVar_neoforge1_zLjvdXoX = 648 * 509;
        assertTrue(mathVar_neoforge1_zLjvdXoX == 329832);
        String strVar_neoforge1_ugFEPJPH = "uarGQPJVLZguZXh" + "jETbj";
        assertTrue(strVar_neoforge1_ugFEPJPH.length() == 20);
        int[] arrVar_neoforge1_CKSBFgHq = new int[]{3, 5};
        assertTrue(arrVar_neoforge1_CKSBFgHq.length == 2);
        int[] arrVar_neoforge1_bGiHvkZN = new int[]{4, 3};
        assertTrue(arrVar_neoforge1_bGiHvkZN.length == 2);
        Object objVar_neoforge1_owONyNuS = new Object();
        assertTrue(objVar_neoforge1_owONyNuS != null);
        int[] arrVar_neoforge1_ddDzUbNi = new int[]{5, 10};
        assertTrue(arrVar_neoforge1_ddDzUbNi.length == 2);
        String strVar_neoforge1_hdrGFErF = "cuIGNoYOydNNkyR" + "avIDv";
        assertTrue(strVar_neoforge1_hdrGFErF.length() == 20);
        int[] arrVar_neoforge1_gkTlUxDt = new int[]{1, 6};
        assertTrue(arrVar_neoforge1_gkTlUxDt.length == 2);
        String strVar_neoforge1_lKfDdzkm = "wBVHvFbQZCCqoSD" + "NDXrO";
        assertTrue(strVar_neoforge1_lKfDdzkm.length() == 20);
        int mathVar_neoforge1_stHwlhGr = 200 * 975;
        assertTrue(mathVar_neoforge1_stHwlhGr == 195000);
        Object objVar_neoforge1_RNcSLNzg = new Object();
        assertTrue(objVar_neoforge1_RNcSLNzg != null);
        int[] arrVar_neoforge1_NkwFxnvX = new int[]{6, 8};
        assertTrue(arrVar_neoforge1_NkwFxnvX.length == 2);
    }
}
