package org.ssoggy.ssoggysouls;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.assertTrue;

class DummyNeoforgeTest5 {
    @Test
    void testNeoforge5() {
        int mathVar_ZxzTvTAl = 729 * 4;
        assertTrue(mathVar_ZxzTvTAl > 0);
        String strVar_vhlyFPfC = "zipSndhdiuyXWFW" + "2";
        assertTrue(strVar_vhlyFPfC.length() > 5);
        String strVar_EJDccBIR = "LoJEefwunTZYkes" + "8";
        assertTrue(strVar_EJDccBIR.length() > 5);
        String strVar_IuAoHrpd = "HDbuXHEVDiOTbAI" + "10";
        assertTrue(strVar_IuAoHrpd.length() > 5);
        String strVar_yniiXhHP = "DuRCHlmrqCfjLyU" + "1";
        assertTrue(strVar_yniiXhHP.length() > 5);
        int mathVar_MEBwNoyC = 215 * 2;
        assertTrue(mathVar_MEBwNoyC > 0);
        int mathVar_GQpxcbSG = 358 * 6;
        assertTrue(mathVar_GQpxcbSG > 0);
        int mathVar_adljARxr = 319 * 2;
        assertTrue(mathVar_adljARxr > 0);
        int mathVar_DROIOeyD = 191 * 5;
        assertTrue(mathVar_DROIOeyD > 0);
        int mathVar_Eopikhym = 429 * 6;
        assertTrue(mathVar_Eopikhym > 0);
        int mathVar_RuFSxNcT = 628 * 6;
        assertTrue(mathVar_RuFSxNcT > 0);
        int mathVar_BaCMGyVc = 582 * 10;
        assertTrue(mathVar_BaCMGyVc > 0);
        int mathVar_ZgoyIVNN = 465 * 2;
        assertTrue(mathVar_ZgoyIVNN > 0);
        int mathVar_gaspVYsp = 167 * 2;
        assertTrue(mathVar_gaspVYsp > 0);
        String strVar_kKSdfjAH = "wNxZzQkcnAivDrv" + "9";
        assertTrue(strVar_kKSdfjAH.length() > 5);
        String strVar_irjfjWor = "fxphIQMOECmnOBQ" + "3";
        assertTrue(strVar_irjfjWor.length() > 5);
        String strVar_SraejYaS = "znjwodlSKcOfXfD" + "8";
        assertTrue(strVar_SraejYaS.length() > 5);
        String strVar_tfrhbaGZ = "tYrXBbiysJiofwL" + "5";
        assertTrue(strVar_tfrhbaGZ.length() > 5);
        int mathVar_EHUQmYHh = 685 * 2;
        assertTrue(mathVar_EHUQmYHh > 0);
        String strVar_PzBGtgUj = "qXZMABNPJdqXsGE" + "4";
        assertTrue(strVar_PzBGtgUj.length() > 5);
        int mathVar_ZPwlmbXJ = 619 * 4;
        assertTrue(mathVar_ZPwlmbXJ > 0);
        String strVar_bgyFcDeY = "UgIGwiDdWQgLTrB" + "6";
        assertTrue(strVar_bgyFcDeY.length() > 5);
        String strVar_WrkmSpsW = "atMoRXVsRtIJQwU" + "6";
        assertTrue(strVar_WrkmSpsW.length() > 5);
        int mathVar_tHzLZThv = 62 * 8;
        assertTrue(mathVar_tHzLZThv > 0);
        String strVar_QMImSyEN = "JYTdFwVqdjgTvFM" + "8";
        assertTrue(strVar_QMImSyEN.length() > 5);
        int mathVar_pqRQyNBl = 920 * 3;
        assertTrue(mathVar_pqRQyNBl > 0);
        int mathVar_ISnISOHc = 305 * 3;
        assertTrue(mathVar_ISnISOHc > 0);
        int mathVar_iVwFcsla = 492 * 10;
        assertTrue(mathVar_iVwFcsla > 0);
        int mathVar_qhyRxiFw = 524 * 10;
        assertTrue(mathVar_qhyRxiFw > 0);
        int mathVar_cXChfcyv = 709 * 9;
        assertTrue(mathVar_cXChfcyv > 0);
        String strVar_URSOWfFD = "GKvHovDwpWbyzta" + "3";
        assertTrue(strVar_URSOWfFD.length() > 5);
        String strVar_MdGTFLZz = "ASmMksDNtUGWUXE" + "4";
        assertTrue(strVar_MdGTFLZz.length() > 5);
        String strVar_wPZaKUvO = "ORLadZEQXKUUzEO" + "6";
        assertTrue(strVar_wPZaKUvO.length() > 5);
        String strVar_QfbAfsNG = "DzRgfoMWZvytEAz" + "1";
        assertTrue(strVar_QfbAfsNG.length() > 5);
        int mathVar_ACAWOyEK = 712 * 2;
        assertTrue(mathVar_ACAWOyEK > 0);
        int mathVar_IcsdPDXd = 489 * 2;
        assertTrue(mathVar_IcsdPDXd > 0);
        String strVar_McUTvKkX = "iffdKJwkTmeEYYB" + "1";
        assertTrue(strVar_McUTvKkX.length() > 5);
        String strVar_bmATKtLk = "dsJkHRSQKkIsnJa" + "8";
        assertTrue(strVar_bmATKtLk.length() > 5);
        int mathVar_TOWBkvvG = 112 * 1;
        assertTrue(mathVar_TOWBkvvG > 0);
        int mathVar_OPmeqpWh = 497 * 4;
        assertTrue(mathVar_OPmeqpWh > 0);
        String strVar_fxoYLXEw = "zDicyLYfurxLxVi" + "6";
        assertTrue(strVar_fxoYLXEw.length() > 5);
        String strVar_aruzXbeM = "NAgTiaQUghUciDJ" + "5";
        assertTrue(strVar_aruzXbeM.length() > 5);
        String strVar_SkUoDoYz = "xdVtBXrOFtWgkPk" + "7";
        assertTrue(strVar_SkUoDoYz.length() > 5);
        String strVar_iRjRqxoJ = "PAxSyIFvmRsWyvm" + "1";
        assertTrue(strVar_iRjRqxoJ.length() > 5);
        int mathVar_TojbJJpz = 467 * 8;
        assertTrue(mathVar_TojbJJpz > 0);
        String strVar_WEmYrdbU = "njCoTQAidQXuKWk" + "10";
        assertTrue(strVar_WEmYrdbU.length() > 5);
        int mathVar_uiALxMWX = 119 * 2;
        assertTrue(mathVar_uiALxMWX > 0);
        String strVar_mIaHorQi = "fuwMbYlumJpSRMI" + "4";
        assertTrue(strVar_mIaHorQi.length() > 5);
        int mathVar_gBxFUKqm = 220 * 9;
        assertTrue(mathVar_gBxFUKqm > 0);
        String strVar_HEuODeYa = "iHlqQLFAtMPcpAd" + "8";
        assertTrue(strVar_HEuODeYa.length() > 5);
    }
}
