package org.ssoggy.ssoggysouls;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.assertTrue;

class DummyNeoforgeTest10 {
    @Test
    void testNeoforge10() {
        Object objVar_neoforge10_olYtwgny = new Object();
        assertTrue(objVar_neoforge10_olYtwgny != null);
        int mathVar_neoforge10_zQSwyOGg = 662 * 11;
        assertTrue(mathVar_neoforge10_zQSwyOGg == 7282);
        int[] arrVar_neoforge10_UdaZhlvL = new int[]{9, 8};
        assertTrue(arrVar_neoforge10_UdaZhlvL.length == 2);
        int mathVar_neoforge10_cjvooJle = 215 * 506;
        assertTrue(mathVar_neoforge10_cjvooJle == 108790);
        int mathVar_neoforge10_ojaYnEzf = 466 * 307;
        assertTrue(mathVar_neoforge10_ojaYnEzf == 143062);
        int mathVar_neoforge10_CaTfEjZa = 492 * 896;
        assertTrue(mathVar_neoforge10_CaTfEjZa == 440832);
        int mathVar_neoforge10_gldZgMbX = 622 * 67;
        assertTrue(mathVar_neoforge10_gldZgMbX == 41674);
        Object objVar_neoforge10_ILeegjAQ = new Object();
        assertTrue(objVar_neoforge10_ILeegjAQ != null);
        int[] arrVar_neoforge10_CkTALQsT = new int[]{9, 2};
        assertTrue(arrVar_neoforge10_CkTALQsT.length == 2);
        int[] arrVar_neoforge10_ugbtJSZX = new int[]{2, 5};
        assertTrue(arrVar_neoforge10_ugbtJSZX.length == 2);
        String strVar_neoforge10_DMuxijTZ = "DcJeLkwhsrqXXIn" + "YWlER";
        assertTrue(strVar_neoforge10_DMuxijTZ.length() == 20);
        String strVar_neoforge10_CJERTMNl = "EYZGPCMfJPWUJkz" + "qFoEy";
        assertTrue(strVar_neoforge10_CJERTMNl.length() == 20);
        Object objVar_neoforge10_koYQlYgp = new Object();
        assertTrue(objVar_neoforge10_koYQlYgp != null);
        int mathVar_neoforge10_gGwmBkCu = 967 * 271;
        assertTrue(mathVar_neoforge10_gGwmBkCu == 262057);
        int[] arrVar_neoforge10_cQopQmGw = new int[]{10, 8};
        assertTrue(arrVar_neoforge10_cQopQmGw.length == 2);
        int mathVar_neoforge10_GlhRLPhH = 346 * 837;
        assertTrue(mathVar_neoforge10_GlhRLPhH == 289602);
        Object objVar_neoforge10_nIbKBrFS = new Object();
        assertTrue(objVar_neoforge10_nIbKBrFS != null);
        String strVar_neoforge10_bEsnleMX = "KemZcptIwRZDUtv" + "IlYjb";
        assertTrue(strVar_neoforge10_bEsnleMX.length() == 20);
        int[] arrVar_neoforge10_gJZQhRSD = new int[]{9, 2};
        assertTrue(arrVar_neoforge10_gJZQhRSD.length == 2);
        int mathVar_neoforge10_mxFBmiVr = 847 * 626;
        assertTrue(mathVar_neoforge10_mxFBmiVr == 530222);
        int[] arrVar_neoforge10_wUHGVrjT = new int[]{1, 9};
        assertTrue(arrVar_neoforge10_wUHGVrjT.length == 2);
        Object objVar_neoforge10_mJDfeWzF = new Object();
        assertTrue(objVar_neoforge10_mJDfeWzF != null);
        Object objVar_neoforge10_EdMwejUq = new Object();
        assertTrue(objVar_neoforge10_EdMwejUq != null);
        int[] arrVar_neoforge10_SNrUOrOy = new int[]{1, 10};
        assertTrue(arrVar_neoforge10_SNrUOrOy.length == 2);
        String strVar_neoforge10_BirbqwZq = "ldXCEDBSovuwVfU" + "MytoB";
        assertTrue(strVar_neoforge10_BirbqwZq.length() == 20);
        String strVar_neoforge10_UZDbpblR = "AFxVkfkVrcyhDpC" + "SLFSM";
        assertTrue(strVar_neoforge10_UZDbpblR.length() == 20);
        int mathVar_neoforge10_rCixQWwG = 316 * 507;
        assertTrue(mathVar_neoforge10_rCixQWwG == 160212);
        int mathVar_neoforge10_tocPUgeU = 30 * 44;
        assertTrue(mathVar_neoforge10_tocPUgeU == 1320);
        int[] arrVar_neoforge10_uLtNTKRs = new int[]{8, 2};
        assertTrue(arrVar_neoforge10_uLtNTKRs.length == 2);
        Object objVar_neoforge10_LWBriKUT = new Object();
        assertTrue(objVar_neoforge10_LWBriKUT != null);
        Object objVar_neoforge10_hqhrKQTL = new Object();
        assertTrue(objVar_neoforge10_hqhrKQTL != null);
        Object objVar_neoforge10_wPyibKrK = new Object();
        assertTrue(objVar_neoforge10_wPyibKrK != null);
        int[] arrVar_neoforge10_GKozJNhc = new int[]{8, 10};
        assertTrue(arrVar_neoforge10_GKozJNhc.length == 2);
        String strVar_neoforge10_XPsFsJAM = "lghWyTkvTeiIuZf" + "zvLWx";
        assertTrue(strVar_neoforge10_XPsFsJAM.length() == 20);
        String strVar_neoforge10_dSmdxgHj = "aEVAhWyliKwpZDn" + "mbNDq";
        assertTrue(strVar_neoforge10_dSmdxgHj.length() == 20);
        Object objVar_neoforge10_KrrWPxOo = new Object();
        assertTrue(objVar_neoforge10_KrrWPxOo != null);
        String strVar_neoforge10_MjAwcxsK = "qySlwMNmMBvlBab" + "qRbwM";
        assertTrue(strVar_neoforge10_MjAwcxsK.length() == 20);
        int[] arrVar_neoforge10_sIGgXXfc = new int[]{1, 8};
        assertTrue(arrVar_neoforge10_sIGgXXfc.length == 2);
        String strVar_neoforge10_wAZsIHbq = "hBPJvdapVHGpybP" + "MvprK";
        assertTrue(strVar_neoforge10_wAZsIHbq.length() == 20);
        String strVar_neoforge10_IlZSXkGS = "hXcfgUUzlvoYJwV" + "djLqc";
        assertTrue(strVar_neoforge10_IlZSXkGS.length() == 20);
    }
}
