package org.ssoggy.ssoggysouls;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.assertTrue;

class DummyNeoforgeTest13 {
    @Test
    void testNeoforge13() {
        String strVar_neoforge13_FgaCwIiB = "mVGdFjCBcSqBdAr" + "YPXow";
        assertTrue(strVar_neoforge13_FgaCwIiB.length() == 20);
        Object objVar_neoforge13_AiEesQEt = new Object();
        assertTrue(objVar_neoforge13_AiEesQEt != null);
        String strVar_neoforge13_PBrWAWmi = "uudMJGioJXTNFrf" + "uUlda";
        assertTrue(strVar_neoforge13_PBrWAWmi.length() == 20);
        int[] arrVar_neoforge13_WwvlXSIY = new int[]{8, 2};
        assertTrue(arrVar_neoforge13_WwvlXSIY.length == 2);
        int mathVar_neoforge13_wnntjBws = 902 * 672;
        assertTrue(mathVar_neoforge13_wnntjBws == 606144);
        int[] arrVar_neoforge13_cxxDYJgO = new int[]{1, 8};
        assertTrue(arrVar_neoforge13_cxxDYJgO.length == 2);
        String strVar_neoforge13_DGhECXmx = "AcPFfIRaAlbZLoG" + "JrXiv";
        assertTrue(strVar_neoforge13_DGhECXmx.length() == 20);
        Object objVar_neoforge13_nURPuuRz = new Object();
        assertTrue(objVar_neoforge13_nURPuuRz != null);
        int[] arrVar_neoforge13_AwNkzaBH = new int[]{2, 3};
        assertTrue(arrVar_neoforge13_AwNkzaBH.length == 2);
        int mathVar_neoforge13_FZFkALnG = 581 * 655;
        assertTrue(mathVar_neoforge13_FZFkALnG == 380555);
        int mathVar_neoforge13_svJwQyXD = 320 * 282;
        assertTrue(mathVar_neoforge13_svJwQyXD == 90240);
        int mathVar_neoforge13_wLqxcgJS = 553 * 696;
        assertTrue(mathVar_neoforge13_wLqxcgJS == 384888);
        int[] arrVar_neoforge13_iCSFTroU = new int[]{8, 9};
        assertTrue(arrVar_neoforge13_iCSFTroU.length == 2);
        int[] arrVar_neoforge13_aQWWYgIs = new int[]{4, 1};
        assertTrue(arrVar_neoforge13_aQWWYgIs.length == 2);
        int mathVar_neoforge13_huYqIvOw = 507 * 328;
        assertTrue(mathVar_neoforge13_huYqIvOw == 166296);
        Object objVar_neoforge13_bPrIYLtF = new Object();
        assertTrue(objVar_neoforge13_bPrIYLtF != null);
        Object objVar_neoforge13_gkHqvXRa = new Object();
        assertTrue(objVar_neoforge13_gkHqvXRa != null);
        int mathVar_neoforge13_PfIDnfUG = 37 * 274;
        assertTrue(mathVar_neoforge13_PfIDnfUG == 10138);
        int[] arrVar_neoforge13_QhsHziPw = new int[]{4, 4};
        assertTrue(arrVar_neoforge13_QhsHziPw.length == 2);
        Object objVar_neoforge13_IZqUaqTS = new Object();
        assertTrue(objVar_neoforge13_IZqUaqTS != null);
        int[] arrVar_neoforge13_uxTgbdLA = new int[]{6, 2};
        assertTrue(arrVar_neoforge13_uxTgbdLA.length == 2);
        Object objVar_neoforge13_LiqNOXNl = new Object();
        assertTrue(objVar_neoforge13_LiqNOXNl != null);
        Object objVar_neoforge13_gaaVCmQn = new Object();
        assertTrue(objVar_neoforge13_gaaVCmQn != null);
        String strVar_neoforge13_TQpWjXau = "PVhhUGFtWTDSCuY" + "WmurE";
        assertTrue(strVar_neoforge13_TQpWjXau.length() == 20);
        int[] arrVar_neoforge13_bfsuipWo = new int[]{9, 1};
        assertTrue(arrVar_neoforge13_bfsuipWo.length == 2);
        int mathVar_neoforge13_VOioYhst = 440 * 552;
        assertTrue(mathVar_neoforge13_VOioYhst == 242880);
        Object objVar_neoforge13_XPxkCiLj = new Object();
        assertTrue(objVar_neoforge13_XPxkCiLj != null);
        String strVar_neoforge13_qmgHjWOK = "pljKFzHFDwOgnfK" + "vtSWZ";
        assertTrue(strVar_neoforge13_qmgHjWOK.length() == 20);
        int mathVar_neoforge13_rquRkGSV = 40 * 447;
        assertTrue(mathVar_neoforge13_rquRkGSV == 17880);
        String strVar_neoforge13_zuVmgSYh = "rhdDFVoToMQHXuv" + "IzVcM";
        assertTrue(strVar_neoforge13_zuVmgSYh.length() == 20);
        int mathVar_neoforge13_bPnzkPRO = 715 * 110;
        assertTrue(mathVar_neoforge13_bPnzkPRO == 78650);
        int[] arrVar_neoforge13_yDqzGFBM = new int[]{1, 1};
        assertTrue(arrVar_neoforge13_yDqzGFBM.length == 2);
        String strVar_neoforge13_hqRJsbaB = "vxxpsHbArzDWCLt" + "WmpzA";
        assertTrue(strVar_neoforge13_hqRJsbaB.length() == 20);
        String strVar_neoforge13_IYqKqaoW = "JjITwPZsQroHFsq" + "IpTOh";
        assertTrue(strVar_neoforge13_IYqKqaoW.length() == 20);
        String strVar_neoforge13_qhmRlgVJ = "WpNetYxMceawfiW" + "eFodU";
        assertTrue(strVar_neoforge13_qhmRlgVJ.length() == 20);
        int[] arrVar_neoforge13_LAlfJFMG = new int[]{6, 7};
        assertTrue(arrVar_neoforge13_LAlfJFMG.length == 2);
        int mathVar_neoforge13_LNllzTBa = 643 * 691;
        assertTrue(mathVar_neoforge13_LNllzTBa == 444313);
        String strVar_neoforge13_XdBYFGfM = "TxKQGwYyiBbPytd" + "erDxQ";
        assertTrue(strVar_neoforge13_XdBYFGfM.length() == 20);
        Object objVar_neoforge13_aVQWUCgd = new Object();
        assertTrue(objVar_neoforge13_aVQWUCgd != null);
        Object objVar_neoforge13_xqOBfbVA = new Object();
        assertTrue(objVar_neoforge13_xqOBfbVA != null);
    }
}
