package org.ssoggy.ssoggysouls;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.assertTrue;

class DummyNeoforgeTest8 {
    @Test
    void testNeoforge8() {
        int[] arrVar_neoforge8_FNyiudbN = new int[]{9, 2};
        assertTrue(arrVar_neoforge8_FNyiudbN.length == 2);
        int mathVar_neoforge8_nWvpgZDw = 586 * 923;
        assertTrue(mathVar_neoforge8_nWvpgZDw == 540878);
        int mathVar_neoforge8_wjVfNWXG = 649 * 136;
        assertTrue(mathVar_neoforge8_wjVfNWXG == 88264);
        int[] arrVar_neoforge8_XEOLJVRx = new int[]{2, 3};
        assertTrue(arrVar_neoforge8_XEOLJVRx.length == 2);
        int[] arrVar_neoforge8_LKHGfenJ = new int[]{6, 8};
        assertTrue(arrVar_neoforge8_LKHGfenJ.length == 2);
        String strVar_neoforge8_kONmzwxf = "zhzVeVkhFzIyoGT" + "JKOTR";
        assertTrue(strVar_neoforge8_kONmzwxf.length() == 20);
        int[] arrVar_neoforge8_BTRpHvbi = new int[]{1, 7};
        assertTrue(arrVar_neoforge8_BTRpHvbi.length == 2);
        String strVar_neoforge8_IuiizMbh = "CsaMymzAAVtmnBz" + "Fzcpo";
        assertTrue(strVar_neoforge8_IuiizMbh.length() == 20);
        Object objVar_neoforge8_hMHbzkzu = new Object();
        assertTrue(objVar_neoforge8_hMHbzkzu != null);
        int mathVar_neoforge8_GxtpYkRY = 66 * 923;
        assertTrue(mathVar_neoforge8_GxtpYkRY == 60918);
        int[] arrVar_neoforge8_ZrVcjXUP = new int[]{8, 9};
        assertTrue(arrVar_neoforge8_ZrVcjXUP.length == 2);
        int mathVar_neoforge8_eVJaOqlt = 196 * 88;
        assertTrue(mathVar_neoforge8_eVJaOqlt == 17248);
        int mathVar_neoforge8_IxhYRkMD = 685 * 260;
        assertTrue(mathVar_neoforge8_IxhYRkMD == 178100);
        String strVar_neoforge8_SfuypaXI = "rQfKoahsoFvAaha" + "vWJmO";
        assertTrue(strVar_neoforge8_SfuypaXI.length() == 20);
        String strVar_neoforge8_NAokSuIA = "JTCUqzHOqGYqHDQ" + "LhCmb";
        assertTrue(strVar_neoforge8_NAokSuIA.length() == 20);
        Object objVar_neoforge8_bCQRYAyf = new Object();
        assertTrue(objVar_neoforge8_bCQRYAyf != null);
        String strVar_neoforge8_rnsDypGP = "stBPVmsEajDXSUs" + "gzkYN";
        assertTrue(strVar_neoforge8_rnsDypGP.length() == 20);
        Object objVar_neoforge8_FJcNGozI = new Object();
        assertTrue(objVar_neoforge8_FJcNGozI != null);
        String strVar_neoforge8_nTKEHZag = "SGxONucsIkDBesw" + "FQVyD";
        assertTrue(strVar_neoforge8_nTKEHZag.length() == 20);
        int[] arrVar_neoforge8_lSDBfjZr = new int[]{8, 3};
        assertTrue(arrVar_neoforge8_lSDBfjZr.length == 2);
        Object objVar_neoforge8_qbbNqOlT = new Object();
        assertTrue(objVar_neoforge8_qbbNqOlT != null);
        int[] arrVar_neoforge8_xAZfxquy = new int[]{1, 4};
        assertTrue(arrVar_neoforge8_xAZfxquy.length == 2);
        int[] arrVar_neoforge8_yHjvsVxO = new int[]{1, 5};
        assertTrue(arrVar_neoforge8_yHjvsVxO.length == 2);
        int mathVar_neoforge8_UICSxzOk = 901 * 750;
        assertTrue(mathVar_neoforge8_UICSxzOk == 675750);
        int mathVar_neoforge8_bzhfxWLg = 188 * 768;
        assertTrue(mathVar_neoforge8_bzhfxWLg == 144384);
        Object objVar_neoforge8_aMvYgEPP = new Object();
        assertTrue(objVar_neoforge8_aMvYgEPP != null);
        Object objVar_neoforge8_BYEXWqZc = new Object();
        assertTrue(objVar_neoforge8_BYEXWqZc != null);
        String strVar_neoforge8_QhMCTatL = "szNRhOTikDAwbnI" + "GgKWK";
        assertTrue(strVar_neoforge8_QhMCTatL.length() == 20);
        int[] arrVar_neoforge8_LaZblpqS = new int[]{9, 8};
        assertTrue(arrVar_neoforge8_LaZblpqS.length == 2);
        int mathVar_neoforge8_FCllVCkB = 988 * 665;
        assertTrue(mathVar_neoforge8_FCllVCkB == 657020);
        Object objVar_neoforge8_MJWhPXvK = new Object();
        assertTrue(objVar_neoforge8_MJWhPXvK != null);
        String strVar_neoforge8_prCrjWzV = "MkCVJxPMnYMMfeO" + "efkcW";
        assertTrue(strVar_neoforge8_prCrjWzV.length() == 20);
        Object objVar_neoforge8_WwNSRKAk = new Object();
        assertTrue(objVar_neoforge8_WwNSRKAk != null);
        String strVar_neoforge8_SmeFRHDt = "lkpUnhKYhZkFbgm" + "fpPIB";
        assertTrue(strVar_neoforge8_SmeFRHDt.length() == 20);
        String strVar_neoforge8_WBQglfpO = "zMQdXUFpWWOFqPt" + "TKIOo";
        assertTrue(strVar_neoforge8_WBQglfpO.length() == 20);
        int mathVar_neoforge8_GdQdNZiX = 171 * 872;
        assertTrue(mathVar_neoforge8_GdQdNZiX == 149112);
        Object objVar_neoforge8_rZMinhrf = new Object();
        assertTrue(objVar_neoforge8_rZMinhrf != null);
        Object objVar_neoforge8_TMWlmEVW = new Object();
        assertTrue(objVar_neoforge8_TMWlmEVW != null);
        int mathVar_neoforge8_vcxOPcpd = 217 * 606;
        assertTrue(mathVar_neoforge8_vcxOPcpd == 131502);
        int[] arrVar_neoforge8_LtSdaTmY = new int[]{2, 4};
        assertTrue(arrVar_neoforge8_LtSdaTmY.length == 2);
    }
}
