package org.ssoggy.ssoggysouls;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.assertTrue;

class DummyNeoforgeTest14 {
    @Test
    void testNeoforge14() {
        Object objVar_neoforge14_xPjZoNyj = new Object();
        assertTrue(objVar_neoforge14_xPjZoNyj != null);
        Object objVar_neoforge14_sKwsrNRv = new Object();
        assertTrue(objVar_neoforge14_sKwsrNRv != null);
        int[] arrVar_neoforge14_IWWfMLwW = new int[]{9, 4};
        assertTrue(arrVar_neoforge14_IWWfMLwW.length == 2);
        Object objVar_neoforge14_YJMQVgmT = new Object();
        assertTrue(objVar_neoforge14_YJMQVgmT != null);
        String strVar_neoforge14_rvXXEdOr = "hnvNiUebRnYevez" + "HLqkA";
        assertTrue(strVar_neoforge14_rvXXEdOr.length() == 20);
        int[] arrVar_neoforge14_jblEYojZ = new int[]{4, 2};
        assertTrue(arrVar_neoforge14_jblEYojZ.length == 2);
        int mathVar_neoforge14_kkYkvZQk = 732 * 423;
        assertTrue(mathVar_neoforge14_kkYkvZQk == 309636);
        String strVar_neoforge14_lFeyKOAK = "DXZPhnaoecGaujq" + "pOXdP";
        assertTrue(strVar_neoforge14_lFeyKOAK.length() == 20);
        int[] arrVar_neoforge14_wdsorTqL = new int[]{4, 8};
        assertTrue(arrVar_neoforge14_wdsorTqL.length == 2);
        String strVar_neoforge14_KQdXCJJA = "aEEcuduQQcoQwxs" + "uWphu";
        assertTrue(strVar_neoforge14_KQdXCJJA.length() == 20);
        int[] arrVar_neoforge14_LXAnhSke = new int[]{3, 2};
        assertTrue(arrVar_neoforge14_LXAnhSke.length == 2);
        String strVar_neoforge14_mxvHPXAa = "zKIdtNTibVEbbsJ" + "HTGRT";
        assertTrue(strVar_neoforge14_mxvHPXAa.length() == 20);
        int[] arrVar_neoforge14_CqtBHwOI = new int[]{2, 2};
        assertTrue(arrVar_neoforge14_CqtBHwOI.length == 2);
        int mathVar_neoforge14_PaCaIEsM = 987 * 954;
        assertTrue(mathVar_neoforge14_PaCaIEsM == 941598);
        String strVar_neoforge14_BHqNGBlH = "SnukkupaKpPFFRE" + "YxcRd";
        assertTrue(strVar_neoforge14_BHqNGBlH.length() == 20);
        Object objVar_neoforge14_JapEECgo = new Object();
        assertTrue(objVar_neoforge14_JapEECgo != null);
        Object objVar_neoforge14_KQqHuZhE = new Object();
        assertTrue(objVar_neoforge14_KQqHuZhE != null);
        int mathVar_neoforge14_Eaimgxkn = 842 * 820;
        assertTrue(mathVar_neoforge14_Eaimgxkn == 690440);
        int mathVar_neoforge14_VVsFHWhA = 367 * 405;
        assertTrue(mathVar_neoforge14_VVsFHWhA == 148635);
        int mathVar_neoforge14_vnZkmpIg = 54 * 299;
        assertTrue(mathVar_neoforge14_vnZkmpIg == 16146);
        int[] arrVar_neoforge14_eaIeXuxD = new int[]{1, 5};
        assertTrue(arrVar_neoforge14_eaIeXuxD.length == 2);
        int[] arrVar_neoforge14_bTnjdtAH = new int[]{7, 8};
        assertTrue(arrVar_neoforge14_bTnjdtAH.length == 2);
        Object objVar_neoforge14_RwmlSWnZ = new Object();
        assertTrue(objVar_neoforge14_RwmlSWnZ != null);
        int mathVar_neoforge14_ILFLxNrI = 622 * 75;
        assertTrue(mathVar_neoforge14_ILFLxNrI == 46650);
        String strVar_neoforge14_zeWdxCyn = "pTYIWaypCmQFaYk" + "BukgT";
        assertTrue(strVar_neoforge14_zeWdxCyn.length() == 20);
        int mathVar_neoforge14_dgFqSySe = 641 * 801;
        assertTrue(mathVar_neoforge14_dgFqSySe == 513441);
        Object objVar_neoforge14_MZeXUkzV = new Object();
        assertTrue(objVar_neoforge14_MZeXUkzV != null);
        int mathVar_neoforge14_ydmyorra = 719 * 574;
        assertTrue(mathVar_neoforge14_ydmyorra == 412706);
        int mathVar_neoforge14_OytDhqyK = 145 * 54;
        assertTrue(mathVar_neoforge14_OytDhqyK == 7830);
        String strVar_neoforge14_WcOKJluY = "ZYiEwHseNlAqPho" + "wFbiS";
        assertTrue(strVar_neoforge14_WcOKJluY.length() == 20);
        String strVar_neoforge14_CCQUZVVX = "nFHJQGXHDGlCzeO" + "mpguL";
        assertTrue(strVar_neoforge14_CCQUZVVX.length() == 20);
        String strVar_neoforge14_poUMJGty = "JsUnqxWsFWHIwON" + "rlDZS";
        assertTrue(strVar_neoforge14_poUMJGty.length() == 20);
        Object objVar_neoforge14_nLciPANx = new Object();
        assertTrue(objVar_neoforge14_nLciPANx != null);
        int mathVar_neoforge14_hnUvBZDL = 664 * 431;
        assertTrue(mathVar_neoforge14_hnUvBZDL == 286184);
        String strVar_neoforge14_ItlighCN = "HWFTKvYPxtYXNFh" + "XOGPW";
        assertTrue(strVar_neoforge14_ItlighCN.length() == 20);
        int[] arrVar_neoforge14_yOsRDWvp = new int[]{10, 2};
        assertTrue(arrVar_neoforge14_yOsRDWvp.length == 2);
        Object objVar_neoforge14_NSwUfLcW = new Object();
        assertTrue(objVar_neoforge14_NSwUfLcW != null);
        int[] arrVar_neoforge14_vflylBFS = new int[]{5, 8};
        assertTrue(arrVar_neoforge14_vflylBFS.length == 2);
        int[] arrVar_neoforge14_RjLaoZzX = new int[]{3, 9};
        assertTrue(arrVar_neoforge14_RjLaoZzX.length == 2);
        Object objVar_neoforge14_IMdaFHWh = new Object();
        assertTrue(objVar_neoforge14_IMdaFHWh != null);
    }
}
