package org.ssoggy.ssoggysouls;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.assertTrue;

class DummyNeoforgeTest9 {
    @Test
    void testNeoforge9() {
        String strVar_neoforge9_ffRqRCpy = "rgWRYHEnuOJzYvF" + "kJnHf";
        assertTrue(strVar_neoforge9_ffRqRCpy.length() == 20);
        int mathVar_neoforge9_HZJcjame = 984 * 505;
        assertTrue(mathVar_neoforge9_HZJcjame == 496920);
        Object objVar_neoforge9_OADmnvBP = new Object();
        assertTrue(objVar_neoforge9_OADmnvBP != null);
        int mathVar_neoforge9_qFdVtNzJ = 146 * 757;
        assertTrue(mathVar_neoforge9_qFdVtNzJ == 110522);
        Object objVar_neoforge9_thPjeAIl = new Object();
        assertTrue(objVar_neoforge9_thPjeAIl != null);
        String strVar_neoforge9_UfnaLcHi = "CstbuHlZiYiSHYr" + "FzqyC";
        assertTrue(strVar_neoforge9_UfnaLcHi.length() == 20);
        String strVar_neoforge9_abwaXEjj = "TGPLVFnhKZHEBKe" + "QMDUz";
        assertTrue(strVar_neoforge9_abwaXEjj.length() == 20);
        String strVar_neoforge9_DaVMsYBh = "yqBYiNcELnMwCDO" + "tOmZX";
        assertTrue(strVar_neoforge9_DaVMsYBh.length() == 20);
        int[] arrVar_neoforge9_AMOqCrBV = new int[]{6, 5};
        assertTrue(arrVar_neoforge9_AMOqCrBV.length == 2);
        int[] arrVar_neoforge9_UIAWtiMk = new int[]{2, 3};
        assertTrue(arrVar_neoforge9_UIAWtiMk.length == 2);
        int[] arrVar_neoforge9_bWOdkuJp = new int[]{4, 6};
        assertTrue(arrVar_neoforge9_bWOdkuJp.length == 2);
        Object objVar_neoforge9_QgwfEFke = new Object();
        assertTrue(objVar_neoforge9_QgwfEFke != null);
        String strVar_neoforge9_jRlAKgZT = "KfGapqNHrwQOIFE" + "hFBsc";
        assertTrue(strVar_neoforge9_jRlAKgZT.length() == 20);
        int mathVar_neoforge9_CvUvAhlT = 838 * 629;
        assertTrue(mathVar_neoforge9_CvUvAhlT == 527102);
        Object objVar_neoforge9_OUNriDpE = new Object();
        assertTrue(objVar_neoforge9_OUNriDpE != null);
        int[] arrVar_neoforge9_JHHQBQyw = new int[]{8, 8};
        assertTrue(arrVar_neoforge9_JHHQBQyw.length == 2);
        int[] arrVar_neoforge9_HiFlcISz = new int[]{8, 8};
        assertTrue(arrVar_neoforge9_HiFlcISz.length == 2);
        int mathVar_neoforge9_XALveuEJ = 381 * 82;
        assertTrue(mathVar_neoforge9_XALveuEJ == 31242);
        Object objVar_neoforge9_lKDzpSSR = new Object();
        assertTrue(objVar_neoforge9_lKDzpSSR != null);
        int[] arrVar_neoforge9_KPiJWbVH = new int[]{8, 7};
        assertTrue(arrVar_neoforge9_KPiJWbVH.length == 2);
        Object objVar_neoforge9_ijrthuPO = new Object();
        assertTrue(objVar_neoforge9_ijrthuPO != null);
        int[] arrVar_neoforge9_kxKNwKzf = new int[]{1, 7};
        assertTrue(arrVar_neoforge9_kxKNwKzf.length == 2);
        Object objVar_neoforge9_UybRExDI = new Object();
        assertTrue(objVar_neoforge9_UybRExDI != null);
        String strVar_neoforge9_eMvWetRV = "XyUzODJZnXpQfsx" + "snnIF";
        assertTrue(strVar_neoforge9_eMvWetRV.length() == 20);
        Object objVar_neoforge9_fbiKHDvG = new Object();
        assertTrue(objVar_neoforge9_fbiKHDvG != null);
        int[] arrVar_neoforge9_JAkBvinA = new int[]{4, 6};
        assertTrue(arrVar_neoforge9_JAkBvinA.length == 2);
        int[] arrVar_neoforge9_mdvIgAJH = new int[]{10, 1};
        assertTrue(arrVar_neoforge9_mdvIgAJH.length == 2);
        Object objVar_neoforge9_CcMuehpp = new Object();
        assertTrue(objVar_neoforge9_CcMuehpp != null);
        String strVar_neoforge9_OTDugHdS = "ShTUHtrfgsxDCNf" + "LrWJy";
        assertTrue(strVar_neoforge9_OTDugHdS.length() == 20);
        int mathVar_neoforge9_TJsngjoi = 926 * 650;
        assertTrue(mathVar_neoforge9_TJsngjoi == 601900);
        String strVar_neoforge9_cGXMYCBS = "PDtUInOZkhgNmVl" + "vYWxc";
        assertTrue(strVar_neoforge9_cGXMYCBS.length() == 20);
        int mathVar_neoforge9_yfYeTOET = 939 * 27;
        assertTrue(mathVar_neoforge9_yfYeTOET == 25353);
        String strVar_neoforge9_NznKlJXV = "RyQbkScHLdcTFPj" + "dKhWn";
        assertTrue(strVar_neoforge9_NznKlJXV.length() == 20);
        int mathVar_neoforge9_zjNOEiwP = 585 * 954;
        assertTrue(mathVar_neoforge9_zjNOEiwP == 558090);
        Object objVar_neoforge9_UJuGlWFl = new Object();
        assertTrue(objVar_neoforge9_UJuGlWFl != null);
        int mathVar_neoforge9_cFwWbZdY = 213 * 453;
        assertTrue(mathVar_neoforge9_cFwWbZdY == 96489);
        int mathVar_neoforge9_etAdPFbq = 666 * 55;
        assertTrue(mathVar_neoforge9_etAdPFbq == 36630);
        String strVar_neoforge9_zYSsNapf = "qOKtbIawJkZwvRb" + "JgUPe";
        assertTrue(strVar_neoforge9_zYSsNapf.length() == 20);
        int[] arrVar_neoforge9_lAWdtsSC = new int[]{10, 2};
        assertTrue(arrVar_neoforge9_lAWdtsSC.length == 2);
        int mathVar_neoforge9_WnRZXdVt = 869 * 170;
        assertTrue(mathVar_neoforge9_WnRZXdVt == 147730);
    }
}
