package org.ssoggy.ssoggysouls;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.assertTrue;

class DummyNeoforgeTest3 {
    @Test
    void testNeoforge3() {
        int mathVar_ATCBOELu = 409 * 2;
        assertTrue(mathVar_ATCBOELu > 0);
        int mathVar_vhlJqMwo = 557 * 8;
        assertTrue(mathVar_vhlJqMwo > 0);
        String strVar_nwcmcBRG = "ggIAUZQRiTxfFtZ" + "1";
        assertTrue(strVar_nwcmcBRG.length() > 5);
        String strVar_yPahAteP = "ePyHACiqoysniFm" + "9";
        assertTrue(strVar_yPahAteP.length() > 5);
        int mathVar_EuvoKJTA = 16 * 7;
        assertTrue(mathVar_EuvoKJTA > 0);
        int mathVar_WSSZkSSj = 439 * 10;
        assertTrue(mathVar_WSSZkSSj > 0);
        int mathVar_xEfCDRzR = 890 * 10;
        assertTrue(mathVar_xEfCDRzR > 0);
        String strVar_LPlgFedw = "CViFnzCmkiBRXok" + "8";
        assertTrue(strVar_LPlgFedw.length() > 5);
        int mathVar_fQXDUDbr = 281 * 4;
        assertTrue(mathVar_fQXDUDbr > 0);
        String strVar_fmXnTACD = "tTeOkvzMxSERTjr" + "1";
        assertTrue(strVar_fmXnTACD.length() > 5);
        String strVar_GsxrMdaa = "AZLJwDSLnBNywWW" + "6";
        assertTrue(strVar_GsxrMdaa.length() > 5);
        String strVar_QneATrGm = "SFpgfgwVvDxPPAE" + "10";
        assertTrue(strVar_QneATrGm.length() > 5);
        int mathVar_xokdXOvN = 995 * 2;
        assertTrue(mathVar_xokdXOvN > 0);
        int mathVar_EBZyKhXt = 702 * 2;
        assertTrue(mathVar_EBZyKhXt > 0);
        String strVar_CGGhrZSc = "jkCOrQGJRsWDZBG" + "7";
        assertTrue(strVar_CGGhrZSc.length() > 5);
        int mathVar_fHSbgAJs = 820 * 6;
        assertTrue(mathVar_fHSbgAJs > 0);
        int mathVar_XDwCxTev = 174 * 8;
        assertTrue(mathVar_XDwCxTev > 0);
        int mathVar_ayQzzhha = 179 * 9;
        assertTrue(mathVar_ayQzzhha > 0);
        String strVar_LACCvaMX = "jmKAyTBiOiANJQb" + "1";
        assertTrue(strVar_LACCvaMX.length() > 5);
        String strVar_mntSHYrC = "HUfkzEDMvASSuXK" + "3";
        assertTrue(strVar_mntSHYrC.length() > 5);
        String strVar_GyrlvdyE = "TFkIFZFJdJZgTKS" + "8";
        assertTrue(strVar_GyrlvdyE.length() > 5);
        String strVar_sKsakwXM = "aItILimBaRqLEmk" + "7";
        assertTrue(strVar_sKsakwXM.length() > 5);
        int mathVar_bOpBoJWM = 90 * 2;
        assertTrue(mathVar_bOpBoJWM > 0);
        int mathVar_xTFfoiut = 347 * 3;
        assertTrue(mathVar_xTFfoiut > 0);
        int mathVar_VmwYyxBU = 245 * 5;
        assertTrue(mathVar_VmwYyxBU > 0);
        int mathVar_cPrQZhRf = 633 * 2;
        assertTrue(mathVar_cPrQZhRf > 0);
        int mathVar_jenGsNqj = 660 * 4;
        assertTrue(mathVar_jenGsNqj > 0);
        String strVar_fWQixNkD = "DYoUKdVXWWswNlz" + "9";
        assertTrue(strVar_fWQixNkD.length() > 5);
        String strVar_hiOXAXuz = "TrwtqMuYoNtLCIP" + "2";
        assertTrue(strVar_hiOXAXuz.length() > 5);
        String strVar_ZsvePbcV = "GUIXArzNjQnmbrA" + "4";
        assertTrue(strVar_ZsvePbcV.length() > 5);
        String strVar_halgegYb = "sbTcYLEmoPIeBbk" + "7";
        assertTrue(strVar_halgegYb.length() > 5);
        String strVar_ZWKkVeVd = "saYnypFlSIqYlMo" + "6";
        assertTrue(strVar_ZWKkVeVd.length() > 5);
        int mathVar_WmcEpAKW = 455 * 6;
        assertTrue(mathVar_WmcEpAKW > 0);
        int mathVar_UlkPVZkc = 368 * 6;
        assertTrue(mathVar_UlkPVZkc > 0);
        int mathVar_xqvdAyKj = 36 * 10;
        assertTrue(mathVar_xqvdAyKj > 0);
        String strVar_DXrIoZHo = "LCUpOyPmYYpCDgA" + "2";
        assertTrue(strVar_DXrIoZHo.length() > 5);
        String strVar_vQsHuELG = "lSbGwqjAWlvpmUC" + "10";
        assertTrue(strVar_vQsHuELG.length() > 5);
        String strVar_gcesEHAm = "nEFtkecpTRFgLlU" + "4";
        assertTrue(strVar_gcesEHAm.length() > 5);
        String strVar_jYcjwJsY = "eKFCYazyxDsFyrU" + "7";
        assertTrue(strVar_jYcjwJsY.length() > 5);
        int mathVar_RmxjHxFV = 700 * 6;
        assertTrue(mathVar_RmxjHxFV > 0);
        String strVar_VoczgLwb = "SnlammXAnktoPoq" + "3";
        assertTrue(strVar_VoczgLwb.length() > 5);
        String strVar_UKheRldh = "uUZtRbgmOswjfrR" + "9";
        assertTrue(strVar_UKheRldh.length() > 5);
        String strVar_ARMbEoaE = "qqXKqBgqhyBJtXk" + "6";
        assertTrue(strVar_ARMbEoaE.length() > 5);
        int mathVar_VowoKKPG = 314 * 5;
        assertTrue(mathVar_VowoKKPG > 0);
        int mathVar_PLeYUYRB = 995 * 1;
        assertTrue(mathVar_PLeYUYRB > 0);
        int mathVar_jSMcATZb = 800 * 1;
        assertTrue(mathVar_jSMcATZb > 0);
        int mathVar_boHTxdOe = 304 * 2;
        assertTrue(mathVar_boHTxdOe > 0);
        int mathVar_oqlnKWIf = 234 * 4;
        assertTrue(mathVar_oqlnKWIf > 0);
        String strVar_iqLPFetg = "gAZKhVdpFzCjZqG" + "3";
        assertTrue(strVar_iqLPFetg.length() > 5);
        String strVar_yCFMVnTt = "zpDeyVtKLixKdnv" + "7";
        assertTrue(strVar_yCFMVnTt.length() > 5);
    }
}
