package org.ssoggy.ssoggysouls;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.assertTrue;

class DummyNeoforgeTest7 {
    @Test
    void testNeoforge7() {
        int[] arrVar_neoforge7_hSrPAuUO = new int[]{5, 1};
        assertTrue(arrVar_neoforge7_hSrPAuUO.length == 2);
        String strVar_neoforge7_DzmQOCDw = "phANpVsxFJBWggk" + "xNgJE";
        assertTrue(strVar_neoforge7_DzmQOCDw.length() == 20);
        Object objVar_neoforge7_HJCnbZRS = new Object();
        assertTrue(objVar_neoforge7_HJCnbZRS != null);
        Object objVar_neoforge7_gVIIzTPE = new Object();
        assertTrue(objVar_neoforge7_gVIIzTPE != null);
        int mathVar_neoforge7_XPyvHJXF = 290 * 962;
        assertTrue(mathVar_neoforge7_XPyvHJXF == 278980);
        int[] arrVar_neoforge7_tpZVwlJF = new int[]{1, 9};
        assertTrue(arrVar_neoforge7_tpZVwlJF.length == 2);
        int mathVar_neoforge7_SqQwFtWw = 365 * 177;
        assertTrue(mathVar_neoforge7_SqQwFtWw == 64605);
        int[] arrVar_neoforge7_igaeYwfI = new int[]{5, 2};
        assertTrue(arrVar_neoforge7_igaeYwfI.length == 2);
        String strVar_neoforge7_RQfWGZYe = "SMbcLjvQtdstIIJ" + "ZbNuq";
        assertTrue(strVar_neoforge7_RQfWGZYe.length() == 20);
        String strVar_neoforge7_NptSVDkp = "mvaJSrtbMpEiWXH" + "NJblb";
        assertTrue(strVar_neoforge7_NptSVDkp.length() == 20);
        String strVar_neoforge7_HZbJXdvV = "QkjOrrFDByaYtuC" + "nMpcc";
        assertTrue(strVar_neoforge7_HZbJXdvV.length() == 20);
        int mathVar_neoforge7_jCwUMUmh = 905 * 578;
        assertTrue(mathVar_neoforge7_jCwUMUmh == 523090);
        Object objVar_neoforge7_BheMfiaS = new Object();
        assertTrue(objVar_neoforge7_BheMfiaS != null);
        String strVar_neoforge7_skvqLhST = "BDGEgSVZIbQxAAk" + "alXGz";
        assertTrue(strVar_neoforge7_skvqLhST.length() == 20);
        String strVar_neoforge7_ChCElNch = "hvtIKhIaggXsNmA" + "DVKjN";
        assertTrue(strVar_neoforge7_ChCElNch.length() == 20);
        int mathVar_neoforge7_wRJQrKTl = 457 * 748;
        assertTrue(mathVar_neoforge7_wRJQrKTl == 341836);
        int mathVar_neoforge7_MrAKckoF = 175 * 198;
        assertTrue(mathVar_neoforge7_MrAKckoF == 34650);
        Object objVar_neoforge7_wjkGzhqc = new Object();
        assertTrue(objVar_neoforge7_wjkGzhqc != null);
        int mathVar_neoforge7_VjbupHiC = 705 * 748;
        assertTrue(mathVar_neoforge7_VjbupHiC == 527340);
        int[] arrVar_neoforge7_IbImOCVB = new int[]{9, 10};
        assertTrue(arrVar_neoforge7_IbImOCVB.length == 2);
        Object objVar_neoforge7_ZwwplALg = new Object();
        assertTrue(objVar_neoforge7_ZwwplALg != null);
        Object objVar_neoforge7_dKYrCmPn = new Object();
        assertTrue(objVar_neoforge7_dKYrCmPn != null);
        Object objVar_neoforge7_XXrdgTOO = new Object();
        assertTrue(objVar_neoforge7_XXrdgTOO != null);
        String strVar_neoforge7_rEsKsFsE = "BbASvYmcOiNMmGe" + "vppRt";
        assertTrue(strVar_neoforge7_rEsKsFsE.length() == 20);
        int mathVar_neoforge7_oyWpNYcj = 786 * 568;
        assertTrue(mathVar_neoforge7_oyWpNYcj == 446448);
        String strVar_neoforge7_pWyreulN = "CXzFDLwxKGfLmSm" + "GwDaD";
        assertTrue(strVar_neoforge7_pWyreulN.length() == 20);
        int[] arrVar_neoforge7_gADlhenv = new int[]{8, 4};
        assertTrue(arrVar_neoforge7_gADlhenv.length == 2);
        Object objVar_neoforge7_AZqFEZvw = new Object();
        assertTrue(objVar_neoforge7_AZqFEZvw != null);
        int[] arrVar_neoforge7_ncZYwsRM = new int[]{2, 4};
        assertTrue(arrVar_neoforge7_ncZYwsRM.length == 2);
        int[] arrVar_neoforge7_fugxGvxW = new int[]{3, 2};
        assertTrue(arrVar_neoforge7_fugxGvxW.length == 2);
        String strVar_neoforge7_ZJdPwoJr = "FgdtXCfkZwIiHGY" + "qxqGW";
        assertTrue(strVar_neoforge7_ZJdPwoJr.length() == 20);
        Object objVar_neoforge7_onFOvZev = new Object();
        assertTrue(objVar_neoforge7_onFOvZev != null);
        int[] arrVar_neoforge7_CYewleQJ = new int[]{2, 6};
        assertTrue(arrVar_neoforge7_CYewleQJ.length == 2);
        int[] arrVar_neoforge7_JvhZuzEe = new int[]{1, 2};
        assertTrue(arrVar_neoforge7_JvhZuzEe.length == 2);
        int mathVar_neoforge7_MqCHKRUJ = 560 * 701;
        assertTrue(mathVar_neoforge7_MqCHKRUJ == 392560);
        String strVar_neoforge7_vGSYSSKR = "kpYuzYnCbpokGoV" + "LUsmf";
        assertTrue(strVar_neoforge7_vGSYSSKR.length() == 20);
        int[] arrVar_neoforge7_bVdJNNzo = new int[]{1, 2};
        assertTrue(arrVar_neoforge7_bVdJNNzo.length == 2);
        int mathVar_neoforge7_awmvhsbt = 688 * 504;
        assertTrue(mathVar_neoforge7_awmvhsbt == 346752);
        Object objVar_neoforge7_pjMqmefe = new Object();
        assertTrue(objVar_neoforge7_pjMqmefe != null);
        int mathVar_neoforge7_iepYaNms = 323 * 153;
        assertTrue(mathVar_neoforge7_iepYaNms == 49419);
    }
}
