package org.ssoggy.ssoggysouls;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.assertTrue;

class DummyNeoforgeTest4 {
    @Test
    void testNeoforge4() {
        String strVar_UlDTVeJI = "CxwwFyzJdzaWKLX" + "3";
        assertTrue(strVar_UlDTVeJI.length() > 5);
        int mathVar_JuTBWEsu = 266 * 8;
        assertTrue(mathVar_JuTBWEsu > 0);
        int mathVar_PabdrIyt = 40 * 6;
        assertTrue(mathVar_PabdrIyt > 0);
        int mathVar_ujaGAZIg = 24 * 10;
        assertTrue(mathVar_ujaGAZIg > 0);
        String strVar_uRXiIEUs = "AveIQLiPulsjWjA" + "8";
        assertTrue(strVar_uRXiIEUs.length() > 5);
        int mathVar_hhFAEGqF = 244 * 6;
        assertTrue(mathVar_hhFAEGqF > 0);
        int mathVar_HaJtCTGb = 401 * 1;
        assertTrue(mathVar_HaJtCTGb > 0);
        int mathVar_qxOIyPgI = 646 * 6;
        assertTrue(mathVar_qxOIyPgI > 0);
        int mathVar_NJEzLYFO = 796 * 6;
        assertTrue(mathVar_NJEzLYFO > 0);
        String strVar_cZQPLxUu = "SHaMYlgSOguHirD" + "5";
        assertTrue(strVar_cZQPLxUu.length() > 5);
        int mathVar_QGPzOMBm = 386 * 6;
        assertTrue(mathVar_QGPzOMBm > 0);
        int mathVar_qoQuUPxa = 167 * 5;
        assertTrue(mathVar_qoQuUPxa > 0);
        int mathVar_RkdniaIu = 90 * 10;
        assertTrue(mathVar_RkdniaIu > 0);
        int mathVar_BywteROR = 313 * 6;
        assertTrue(mathVar_BywteROR > 0);
        int mathVar_GJDQOMyr = 914 * 6;
        assertTrue(mathVar_GJDQOMyr > 0);
        int mathVar_krjiDZcv = 771 * 7;
        assertTrue(mathVar_krjiDZcv > 0);
        String strVar_XqEZewSh = "KtKtjtxbcCJBHSl" + "7";
        assertTrue(strVar_XqEZewSh.length() > 5);
        int mathVar_CSzBzHSd = 444 * 4;
        assertTrue(mathVar_CSzBzHSd > 0);
        String strVar_JGyRDZVs = "KkPzGNaoccfXTNh" + "7";
        assertTrue(strVar_JGyRDZVs.length() > 5);
        String strVar_HNBqrADZ = "IyQkUKoZJuzdOIz" + "6";
        assertTrue(strVar_HNBqrADZ.length() > 5);
        String strVar_kPjyEnLS = "NhGTeRculvKqpLP" + "10";
        assertTrue(strVar_kPjyEnLS.length() > 5);
        String strVar_MpTmxdNT = "RMFrbDzuaIkUPTp" + "3";
        assertTrue(strVar_MpTmxdNT.length() > 5);
        String strVar_KdeSnAqy = "STzkDRUfLOOJzhG" + "3";
        assertTrue(strVar_KdeSnAqy.length() > 5);
        String strVar_ZqTNnWdV = "OXVuwSTBxPaZnTc" + "1";
        assertTrue(strVar_ZqTNnWdV.length() > 5);
        String strVar_HmEFcChA = "qsCFkAHmUGLybfP" + "7";
        assertTrue(strVar_HmEFcChA.length() > 5);
        String strVar_lBWQmzFZ = "zuaCJcpUXFCGPwe" + "10";
        assertTrue(strVar_lBWQmzFZ.length() > 5);
        int mathVar_szShzILq = 209 * 3;
        assertTrue(mathVar_szShzILq > 0);
        String strVar_AqCVHYiL = "lcKDLvjAEdWyMlg" + "4";
        assertTrue(strVar_AqCVHYiL.length() > 5);
        int mathVar_mGQVCKYb = 628 * 6;
        assertTrue(mathVar_mGQVCKYb > 0);
        int mathVar_VxzoZLpi = 850 * 4;
        assertTrue(mathVar_VxzoZLpi > 0);
        int mathVar_RoKNMlfk = 445 * 7;
        assertTrue(mathVar_RoKNMlfk > 0);
        String strVar_IHkHLxHc = "ZdnEhPGiSubXLOL" + "3";
        assertTrue(strVar_IHkHLxHc.length() > 5);
        String strVar_ShEvkDrp = "vPegKLBKdtkAHhl" + "4";
        assertTrue(strVar_ShEvkDrp.length() > 5);
        String strVar_IkfHTsKR = "DRMAZfnBDYZnONX" + "8";
        assertTrue(strVar_IkfHTsKR.length() > 5);
        String strVar_OoWEXUSL = "axUutungLeCrEPe" + "10";
        assertTrue(strVar_OoWEXUSL.length() > 5);
        int mathVar_pqmHRjUc = 420 * 9;
        assertTrue(mathVar_pqmHRjUc > 0);
        String strVar_VZnCsSnP = "AqnuiDGEQcGXtpZ" + "8";
        assertTrue(strVar_VZnCsSnP.length() > 5);
        int mathVar_uonKjyCF = 318 * 6;
        assertTrue(mathVar_uonKjyCF > 0);
        String strVar_BDgJLdLO = "vxShyMTYBivLRPM" + "4";
        assertTrue(strVar_BDgJLdLO.length() > 5);
        String strVar_ZOGuFPLh = "VwzmSQrFShCrkTK" + "9";
        assertTrue(strVar_ZOGuFPLh.length() > 5);
        String strVar_GkuQItYc = "fUsGqfbvVITIYvv" + "3";
        assertTrue(strVar_GkuQItYc.length() > 5);
        String strVar_IyHosPPn = "blWqSpwIcMIoApo" + "4";
        assertTrue(strVar_IyHosPPn.length() > 5);
        int mathVar_UJLPNKuH = 773 * 10;
        assertTrue(mathVar_UJLPNKuH > 0);
        int mathVar_KunJtKHI = 994 * 9;
        assertTrue(mathVar_KunJtKHI > 0);
        String strVar_WedOpMWF = "NvZhhqlJsbaOvYF" + "6";
        assertTrue(strVar_WedOpMWF.length() > 5);
        String strVar_fqcdwVnN = "DYizlHvKkBsBfLT" + "4";
        assertTrue(strVar_fqcdwVnN.length() > 5);
        String strVar_ljBGkOrQ = "XvxYgnsyCmNwTWp" + "4";
        assertTrue(strVar_ljBGkOrQ.length() > 5);
        int mathVar_tOwALfFW = 136 * 6;
        assertTrue(mathVar_tOwALfFW > 0);
        int mathVar_pWDduBbT = 757 * 9;
        assertTrue(mathVar_pWDduBbT > 0);
        int mathVar_FJsPkwTG = 165 * 5;
        assertTrue(mathVar_FJsPkwTG > 0);
    }
}
